ministryofjustice/hmpps-education-and-work-plan-ui

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
The PR corrects the redis secret referenced in the helm chart to the correct value, as [setup in this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/14157) (which needs to be merged before this one)
=> Corrected reference to redis secret

integration_tests/mockApis/auth.ts, integration_tests/pages/page.ts, integration_tests/support/index.ts, package-lock.json, package.json, server/views/pages/goal/create/index.njk
This PR adds cypress-axe and configures the integration tests to perform basic accessibility tests on each rendered page.
This will mean that we catch and can fix basic accessibility tests at development time, rather than waiting for the formal accessibility tests as part of GDS sign off etc
=> Cypress tests now do basic accessibility tests

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This PR references the secret that I setup earlier in Cloud Platform Env for the SSL cert for the UI.
Of note, the certificate DNS name does not include the the `-ui` suffix , hence the changes to the ingress rules in this PR.
What that means for us is that the URL for our UI on dev will change to `https://hmpps-education-and-work-plan-dev.hmpps.service.justice.gov.uk/`
=> Ingress config for UI SSL cert

server/routes/createGoal/createGoalController.ts, server/services/prisonerSearchService.test.ts, server/services/prisonerSearchService.ts
This PR attempts to call prisoner-search using the user token rather than the system token.
If this works then we can consider which is the right token that we _should_ be using (it might be that the system token is the right token, but we need to give it some additional roles. Or we might decide the user token is the right token)
=> Try using user token rather than systemToken when calling prisoner-search

cypress.config.ts, integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/e2e/login.cy.ts, integration_tests/mockApis/auth.ts, integration_tests/pages/authorisationError.ts, server/app.ts, server/middleware/roleBasedAccessControl.ts, server/routes/createGoal/index.ts
This PR uses the `authorisationMiddleware` to ensure that requests to our pages (routes) are appropriately secured.
I've set our 3 create pages to require the user is an EDITOR
=> RR-2 - Add role based access controls for page requests

integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, server/@types/forms/index.d.ts, server/routes/createGoal/createGoalController.ts, server/routes/createGoal/index.ts, server/routes/createGoal/routerRequestHandlers.test.ts, server/routes/createGoal/routerRequestHandlers.ts, server/views/pages/goal/create/index.njk
This PR implements form session handling code to prevent the user navigating to pages in the Create A Goal journey out of sequence.
See the integration tests for specific examples of the user interactions that this code protects against
Currently the redirect is to the first page in our Create Goal journey. Once we have more screens, perhaps a better screen to redirect to would be the Overview page for the prisoner identified in the URL . Perhaps we make that change when we do RR-69 🤔
=> RR-2 - Implement form session handling to prevent page navigation out of sequence

integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/pages/authManageDetails.ts, integration_tests/pages/authSignIn.ts, integration_tests/pages/authorisationError.ts, integration_tests/pages/goal/AddNotePage.ts, integration_tests/pages/goal/AddStepPage.ts, integration_tests/pages/goal/CreateGoalPage.ts, integration_tests/pages/index.ts, integration_tests/pages/overview/OverviewPage.ts, integration_tests/pages/page.ts, server/views/autherror.njk, server/views/pages/goal/add-note/index.njk, server/views/pages/goal/add-step/index.njk, server/views/pages/goal/create/index.njk, server/views/pages/index.njk, server/views/pages/overview/index.njk, server/views/partials/layout.njk
This PR refactors the integrations tests (before we get too far with them!) so that the page assertion is based on pageId rather than page title. We did this in SLM, and the thinking was that asserting the current page on page title was fragile as content is likely to change
=> Refactor integration tests to use pageId rather than page title

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
This PR adds the IP ranges to the UI allow list for the MoJ computers that some of the team are using (they are using MoJ laptops that are the same as those used in prisons; therefore they are coming up as a prison IP address)
The ranges that I'm adding here is enough to get the team started; though we will likely add more once we get into private/public beta.
The ranges are as used in other UI projects, such as:
* https://github.com/ministryofjustice/hmpps-incentives-ui/blob/main/helm_deploy/hmpps-incentives-ui/values.yaml#L74
* https://github.com/ministryofjustice/hmpps-education-employment-ui/blob/e8fefd7a2512b14547235741988ba90914002a92/helm_deploy/hmpps-education-employment-ui/values.yaml#L58
=> RR-2 - Additional entries in allow list (not the full set yet)

integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/e2e/overview/overview.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/routes/createGoal/createGoalController.test.ts, server/routes/createGoal/createGoalController.ts, server/routes/createGoal/index.ts, server/routes/createGoal/routerRequestHandlers.test.ts, server/routes/createGoal/routerRequestHandlers.ts, server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts
This PR integrates the new Overview page with the other pages in our journey.
It is now set as being the first page in the Create Goal journey, in that you have to start on this page and click the `Add a goal` button. You can no longer navigate directly to the Create Goal page.
The only consideration with this PR is when we should merge it in relation to the testing that the team are doing for RR-2 - we will probably need to liaise with them to let them know about the screen flow change
=> RR-69 - Integrate Overview page in journey of other pages

.eslintrc.json, integration_tests/e2e/overview/overview.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/middleware/populateUserAuthorities.ts, server/middleware/roleBasedAccessControl.ts, server/middleware/setUpCurrentUser.ts, server/routes/createGoal/index.ts, server/routes/overview/index.ts, server/views/pages/overview/partials/overviewTabContents.njk
This PR makes the display of the `Add a goal` button on the Overview Page conditional based on the user's role/authorities - you need to be an editor in order to add a goal (as per one of the ACs in the story)
As part of the implementation for this an enum has been introduced (an enum of the user roles), which has meant I have had to fix the linting bug re: enums. TLDR; we can now use enums in the UI project 👍
=> RR-69 - Conditional display of Add Goal button based on role

assets/scss/application-ie8.scss, assets/scss/application.scss, assets/scss/components/_search-page.scss, server/routes/index.test.ts, server/views/pages/index.njk
Implementation of a stub search results page (to replace the "This site is under construction" page)
A hardcoded list of prisoners, known to exist in `dev`, which will make "seeing" then end-to-end a little easier, plus will help testing stories whilst we do not have a functioning search page
=> RR-68 - Stub search results page

server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/services/prisonerSearchService.test.ts, server/services/prisonerSearchService.ts
The PR is based on the outcome of a number slack conversations, but [mainly this one](https://mojdt.slack.com/archives/CDK7ECU3W/p1689326272000459)
The PR refactors our integration with `prisoner-search` so that it uses the system client token rather than the authenticated users token.
The reason for this change is that we don't want to have to give all the possible user's of this service the roles `GLOBAL_SEARCH` and `VIEW_PRISONER_DATA` as this is both an admin burden, but more importantly has the potential to expose prisoner data to users who are not entitled to view it.
The preferred approach (as per the slack conversation above) is to use the system token, but with the authenticated users username. This means the roles are only applied to the system client (being requested separately …
=> RR-105 - Refactored to use the systemToken with the authenticated username

server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/overview/prisonerSummaryRequestHandler.test.ts, server/routes/overview/prisonerSummaryRequestHandler.ts, server/routes/overview/supportNeedsView.ts, server/views/pages/overview/index.njk, server/views/pages/overview/partials/navigation.njk, server/views/pages/overview/partials/supportNeedsTabContents.njk
This PR adds the route, controller and basic view for the Support Needs tab on the Overview page
The code to retrieve the prisoner from prisoner-search and marshall into a PrisonerSummary in the session has been refactored out of the controller and moved into a RequestHandler so that it can be used as part of the route definition for all Overview page routes; meaning we dont need to duplicate it
=> RR-107 - Route, controller, and basic view for Support Needs

package-lock.json, package.json
- Install the latest version of  `govuk-frontend` (https://github.com/alphagov/govuk-frontend/releases/tag/v4.7.0) which doesn't require any code changes in our codebase, but will give us access to the latest bug fixes and components if we need them
- Install the latest version of `typescript`
- Ensure that `moment` is in `package-lock.json`
This should fix the CircleCI failures on `main` (https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-and-work-plan-ui/140/workflows/83bea5e1-a119-41f9-89cc-53b731287d75/jobs/625)
=> install latest version of govuk-frontend and typescript

server/views/pages/error.njk, server/views/pages/goal/add-note/index.njk, server/views/pages/goal/add-step/index.njk, server/views/pages/goal/create/index.njk, server/views/pages/goal/review/index.njk, server/views/pages/index.njk, server/views/pages/overview/index.njk, server/views/pages/overview/partials/overviewTabContents.njk, server/views/partials/breadCrumb.njk, server/views/partials/layout.njk
From https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/52 only implement changes that don't have an impact on the UI, as these changes require a JIRA ticket, these changes are just the under the hood improvements.
- Remove redundant mainClasses, these weren't having any impact on the page and aren't required
- Import all the GOVUK Nunjucks macros in the layout file to reduce duplication in templates
https://dsdmoj.atlassian.net/browse/RR-139
=> Frontend code improvements

server/@types/viewModels/index.d.ts, server/routes/overview/index.ts, server/routes/overview/mappers/prisonerSupportNeedsMapper.test.ts, server/routes/overview/mappers/prisonerSupportNeedsMapper.ts, server/routes/overview/prisonerSupportNeedsRequestHandler.test.ts, server/routes/overview/prisonerSupportNeedsRequestHandler.ts, server/services/curiousService.test.ts, server/services/curiousService.ts, server/views/pages/overview/partials/supportNeedsTabContents.njk
This PR adds some initial error handling for when we get an unexpected error from Curious (other than a 404). This has been easy to test since Curious has been unavailable since yesterday morning! 🤦 
Hopefully Curious will be back soon or it's going to be difficult to check what's returned in certain scenarios and complete the Support Needs view accordingly. I've asked for help in the `#meganexus-collaboration` channel but no joy yet: https://mojdt.slack.com/archives/C02497NS0HK/p1689771706876089
=> RR-135 Handle unexpected error from Curious

README.md, integration_tests/e2e/overview/educationAndTrainingTab.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/filters/formatFunctionalSkillTypeFilter.test.ts, server/filters/formatFunctionalSkillTypeFilter.ts, server/utils/nunjucksSetup.ts, server/views/pages/overview/partials/educationAndTrainingTabContents.njk, server/views/pages/overview/partials/educationAndTrainingTabContents.test.ts
This PR handles the happy path for the Education and Training tab - Functional Skills data returned from Curious is now rendered to the page.
Contrary to the design in the prototype and story (which is a hybrid GDS component), I have chosen to use a simple govuk table for this data. Semantically it's correct (it's rows of tabular data 🤷‍♂️ ), and personally I think it looks clean and elegant (but I'm no designer!) - will create a subtask for @chrimesdev to choose and implement a suitable component if necessary.
Which ever component / design we use; we will update the story accordingly
=> RR-116 - Flesh out view; cypress integration test

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This PR corrects the curious api URL endpoints for the deployed envs in the helm deployments
The spurious trailing slash is causing the Curious API some issues! 🙄
=> RR-116 - Corrected Curious API endpoint URLs

server/@types/viewModels/index.d.ts, server/routes/overview/prisonerSummaryRequestHandler.ts, server/views/partials/prisonerBanner.njk
- Used “string” in the interface as its coming out of the API as a string 
- Removed prisoner location as this is no longer used in the summary bar
- Added a visually hidden text paragraph above the prison summary bar for screen readers context (confirmed with Johanna)
- After speaking with Johanna, she said to leave the text as is if there is no data for a label, she is going to check with content community and other projects for consistency on the labelling and handling of no data
=> add reception date and DOB to the prisoner summary bar

server/views/pages/goal/create/index.njk
Markup for a Textarea when the question label is the page heading (`h1`) was slightly incorrect, uses the correct markup from the [GOV.UK Design System - Text area](https://design-system.service.gov.uk/components/textarea/) guidance.
=> use the correct markup for textarea with label as heading

integration_tests/mockData/actionPlanByPrisonNumberData.ts, server/@types/dto/index.d.ts, server/@types/viewModels/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/data/mappers/actionPlanMapper.test.ts, server/data/mappers/actionPlanMapper.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewView.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/testsupport/actionPlanTestDataBuilder.ts, server/testsupport/createGoalRequestTestDataBuilder.ts, server/views/pages/overview/partials/overviewTabContents.njk
This PR handles unexpected errors from the education-and-work-plan-api. As part of this change, I've avoided the use of a DTO in the view model, as it didn't fit the pattern we've used elsewhere.
=> RR-161 - Handle unexpected error from education-and-work-plan-api

server/@types/educationAndWorkPlanApi/index.d.ts
Re-import Education and Work Plan API's swagger spec, following the removal of `category` from a goal
=> RR-3 - Update EWP API swagger spec

server/@types/educationAndWorkPlanApiClient/index.d.ts, server/data/curiousClient.test.ts, server/data/curiousClient.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/data/restClient.ts, server/services/educationAndWorkPlanService.ts, server/testsupport/createGoalRequestTestDataBuilder.ts, server/testsupport/updateGoalFormTestDataBuilder.ts, server/testsupport/updateGoalRequestTestDataBuilder.ts
This PR introduces a method in `educationAndWorkPlanClient.ts` to invoke the Update Goal API.
Because the API is a `PUT` method operation, `restClient.ts` needed some refactoring because it does not currently support `PUT` or `DELETE` (which we will need later on in the project). The changes made to the rest client in keeping with (copy and paste 😁 ) what we did on a previous project for the same reasons (Send Legal Mail)
Unit tests have been written for the new method in `educationAndWorkPlanClient.ts`; and whilst doing so I realised that both the implementation (in respect of returning promises) and the tests for the existing methods in `educationAndWorkPlanClient.ts` and `curiousClient.ts` were incorrect, so I've taken the opportunity to fix them here.
=> RR-3 - Client method and associated code to call Update Goal API

integration_tests/pages/overview/OverviewPage.ts, server/routes/functionalSkills/functionalSkillsController.ts, server/routes/functionalSkillsResolver.test.ts, server/routes/functionalSkillsResolver.ts, server/routes/overview/overviewController.ts, server/views/pages/functionalSkills/index.njk, server/views/pages/overview/partials/educationAndTrainingTabContents.njk, server/views/pages/overview/partials/educationAndTrainingTabContents.test.ts, server/views/pages/overview/partials/overviewTabContents.njk
This PR adds the "Assessment history" table to the Functional Skills page; and also the "View all" links on the Overview and Education & Training tab
=> RR-31 - Display All Functional Skills; add "View all" links to get to page

cypress.config.ts, integration_tests/pages/functionalSkills/FunctionalSkillsPage.ts, package.json
This PR enables cypress video recording; keeping only those that are for failed tests; and exporting them as circleCI artefacts.
See here as an example:
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-and-work-plan-ui/358/workflows/76350956-14ad-43e3-964c-3d79ebce02be/jobs/1577/artifacts
=> RR-31 - Enable video artefacts for failed cypress tests

integration_tests/pages/goal/UpdateGoalPage.ts, server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/forms/index.d.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/testsupport/updateGoalFormTestDataBuilder.ts, server/views/pages/goal/update/index.njk
This PR adds the basic (but functional 😁 ) changes to support adding new steps as part of Updating a Goal
No cypress tests as yet - they will come in the next PR
=> RR-32 - Basic controller and view for Add Another Step

server/views/pages/goal/update/index.njk
This PR makes a few minor markup changes to the Update Goal nunjucks template so that each Step is rendered as per the design (more accurately the simplified design as agreed in RR-3)
=> RR-3 - Updated markup for steps when Updating a Goal

assets/scss/local.scss, server/views/pages/goal/update/review.njk, server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
Not usually a fan of adding custom CSS, but in this case it is recommended by GOVUK Design System
> If the [width override classes](https://design-system.service.gov.uk/styles/layout/#width-override-classes) do not meet your needs you can create your own width classes and apply them to the cells in the table head. These can be added using the classes option in the Nunjucks macro or adding the class directly to the individual cells within govuk-table__head as below.
Source: https://design-system.service.gov.uk/components/table/#custom-column-widths
https://dsdmoj.atlassian.net/browse/RR-219
=> add custom column widths to fix the styling of steps tables

server/views/partials/layout.njk
`jquery-ui` isn't used within our service and there was a console error around crossorigin requests from the CDN. The version of `jquery-ui` we were referencing was also from 2016!
=> remove jquery UI from the project

server/views/pages/overview/partials/functionalSkillsSidebar.njk, server/views/pages/overview/partials/functionalSkillsSidebar.test.ts, server/views/pages/overview/partials/overviewTabContents.njk
If there was a problem getting curious data, render some message in the functional skills sidebar on the Overview page in place of where we would otherwise display the Functional Skills data.
https://dsdmoj.atlassian.net/browse/RR-210
=> RR-201 - add error handling to functional skills display on overview page

server/views/autherror.njk
use the correct page layout markup for the auth error page for semantics and consistency across our pages.
=> use the correct page layout markup for the auth error page

integration_tests/e2e/goal/updateGoal.cy.ts, integration_tests/e2e/overview/overview.cy.ts, integration_tests/mockApis/prisonerSearchApi.ts, server/routes/overview/prisonerSummaryRequestHandler.test.ts, server/routes/overview/prisonerSummaryRequestHandler.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts
Render 404 page when user tries to update a goal that does not exist
Also rendering a 404 page when Prisoner Search API returns a 404 when we load the prisoner summary (ie. most pages, but the test is for the Overview page)
=> RR-188 - Render 404 page when user tries to update a goal that does not exist

integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/e2e/goal/review.cy.ts, integration_tests/e2e/goal/reviewUpdateGoal.cy.ts, integration_tests/e2e/goal/updateGoal.cy.ts, integration_tests/e2e/overview/overview.cy.ts, integration_tests/e2e/overview/supportNeedsTab.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/routes/inPrisonEducationRecordsResolver.test.ts, server/routes/inPrisonEducationRecordsResolver.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/overview/overviewView.ts, server/views/pages/overview/partials/overviewTabContents.njk
This PR wires in the Curious service call into the Overview tab to get the latest completed qualifications/achievements; then populate the view model with the data.
Adam had already created the nunjucks, this was just a case of un-commenting it
Integration tests updated (most required a stub setting to get the Curious Learner Education because those tests go via the Overview tab). New tests written for the Overview tab to assert various behaviours for the Most Recent Qualifications sidebar
=> RR-179 - Wired in service call, mapped to view model, integration tests

README.md, feature.env, helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, server/config.ts, server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
This PR removes the EDIT_GOALS_ENABLED feature toggle.
It was only ever a temporary feature toggle, to prevent us delivering half-baked code whilst we did the Update Goal stories
Now those stories are delivered and have been tested successfully, we can remove the feature toggle 👍
=> RR-204 - Removed EDIT_GOALS_ENABLED feature toggle

server/@types/viewModels/index.d.ts, server/data/ciagInductionClient.ts, server/data/index.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/overview/workAndInterestsView.ts, server/services/ciagInductionService.test.ts, server/services/ciagInductionService.ts, server/services/index.ts, server/views/pages/overview/partials/workAndInterestsTabContents.njk
This PR adds the CIAG Induction Service class, with a service method to get the CIAG Induction.
The returned CIAGInduction is mapped to a WorkAndInterests object (detail still to be fleshed out)
The view has been updated to show an error if the CIAG API is down altogether (our usual "some other service is down" type message). 
We also handle the scenario where the CIAG API is up, but there is no CIAG Induction for the prisoner. The content team have specified the message they wish to show in the case (though it might need some 'flourish' 😁 )
(Note also that this is basically a 404 scenario. I've coded it based around a 404, but we know that at the moment the CIAG API returns this as a 400. I will ask them to correct this in their API)
=> RR-115 - Basic CIAG Induction Service, with error handling

cypress.config.ts, feature.env, integration_tests/e2e/overview/workAndInterestsTab.cy.ts, integration_tests/mockApis/ciagInducationApi.ts, integration_tests/pages/overview/OverviewPage.ts, server/views/pages/overview/partials/workAndInterestsTabContents.njk
This PR introduces the cypress tests for the Work And Interests tab, specifically the 2 sad path cases (CIAG API is down; and CIAG API returns a 404)
=> RR-115 - Cypress tests for sad paths on Work and Interests tab

server/@types/ciagInductionApiClient/index.d.ts, server/@types/viewModels/index.d.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/testsupport/ciagInductionTestDataBuilder.ts
This PR define our WorkExperience view model object; and maps into it from the CIAG Induction data
This type definition (WorkExperience) and its mapping is one third of the data required for the Work and Interests screen. In total we need Work Experience, Work Interests and Skills and Interests.
The others will be done in my next PRs, but I felt that seeing / reviewing these in smaller chunks should help visualize the data a little 🤞 
Bear in mind also that this mapping and the test data builders are pure guesswork at the moment because we are yet to see any actual data the the CIAG Induction API
=> RR-115 - Define our WorkExperience view model object

package-lock.json, package.json
Fix the `npm outdated` error in CircleCI https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-and-work-plan-ui/516/workflows/8cc93033-0487-4438-90f5-aba18ce1ec3c/jobs/2270
=> fix outdated dependencies reported by npm outdated

assets/scss/components/_print-link.scss, server/views/partials/printThisPage.njk
Following testing on the print link button, improve the alignment of the print link with the `<h1>`, rather than the caption.
See: https://dsdmoj.atlassian.net/browse/RR-262?focusedCommentId=320142
=> RR-263 - improve the print link button alignment with the h1

server/filters/formatAdditionalTrainingFilter.test.ts, server/filters/formatAdditionalTrainingFilter.ts, server/filters/formatEducationLevelFilter.test.ts, server/filters/formatEducationLevelFilter.ts, server/utils/nunjucksSetup.ts, server/views/pages/overview/partials/educationAndTrainingOtherQualifications.njk, server/views/pages/overview/partials/educationAndTrainingOtherQualifications.test.ts
As if by magic, the enum values have been converted to human readable text:
=> RR-264 - Filters for "other qualifications" related enums

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts, server/filters/formatPersonalInterestsFilter.test.ts, server/filters/formatPersonalInterestsFilter.ts, server/filters/formatSkillFilter.test.ts, server/filters/formatSkillFilter.ts, server/utils/nunjucksSetup.ts, server/views/pages/overview/partials/workAndInterestsTabContents.njk
Populate the Work & Interests tab view with the data from the CIAG API. This also includes the "Change" answer URLs into the CIAG UI.
Note: Add `CIAG_INDUCTION_UI_URL=http://ciag-induction-dev.hmpps.service.justice.gov.uk` to your `.env` file.
https://dsdmoj.atlassian.net/browse/RR-246
https://dsdmoj.atlassian.net/browse/RR-247
=> RR-246 & RR-247 - populate the Work & Interests tab with data from the CIAG API

server/filters/formatAdditionalTrainingFilter.test.ts, server/filters/formatAdditionalTrainingFilter.ts, wiremock/README.md, wiremock/mappings/002-single-learner-neurodivergence-not-found-mapping.json, wiremock/mappings/003-single-learner-neurodivergence-curious-unavailable-mapping.json, wiremock/mappings/012-single-learner-profile-not-found-mapping.json, wiremock/mappings/013-single-learner-profile-curious-unavailable-mapping.json, wiremock/mappings/042-ciag-induction-not-found-mapping.json, wiremock/mappings/043-ciag-induction-service-unavailable-mapping.json, wiremock/mappings/053-learner-education-not-found-mapping.json, wiremock/mappings/054-learner-education-curious-unavailable-mapping.json
Wiremock stubs to simulate Curious and CIAG induction service errors.
For example, this page is rendered when Curious is down:
Clearly these scenarios need looking at, which will require collaboration with Karen & Jo and separate stories to be created.
=> RR-269 - Wiremock stubs

.circleci/config.yml, server/@types/dto/index.d.ts, server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/viewModels/index.d.ts, server/data/mappers/createGoalMapper.test.ts, server/data/mappers/createGoalMapper.ts, server/data/mappers/updateGoalMapper.test.ts, server/data/mappers/updateGoalMapper.ts, server/routes/createGoal/createGoalController.test.ts, server/routes/createGoal/createGoalController.ts, server/routes/createGoal/mappers/createGoalFormToCreateGoalDtoMapper.test.ts, server/routes/createGoal/mappers/createGoalFormToCreateGoalDtoMapper.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/prisonerSummaryRequestHandler.test.ts, server/routes/overview/prisonerSummaryRequestHandler.ts, server/routes/routerRequestHandlers.test.ts, server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.test.ts, server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/testsupport/createGoalDtoTestDataBuilder.ts, server/testsupport/createGoalRequestTestDataBuilder.ts, server/testsupport/prisonerSummaryTestDataBuilder.ts, server/testsupport/updateGoalDtoTestDataBuilder.ts, server/testsupport/updateGoalRequestTestDataBuilder.ts, server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.test.ts, server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.test.ts, server/views/pages/overview/partials/educationAndTrainingOtherQualifications.test.ts, server/views/pages/overview/partials/functionalSkillsSidebar.test.ts, server/views/pages/overview/partials/supportNeedsTabContents.test.ts
This PR (which is massive (!!!), sorry (!!!) ) imports the latest API swagger spec which changes the CreateGoal and UpdateGoal API request bodies to include the prison ID of the prisoner. Changes are made to the various DTOs, controller and mappers etc to provide the prisonID. 
The prisonID is taken from the Prison record that we retrieve from `prisoner-offender-search` and mapped into a new field in our `PrisonerSummary` object.
Because of the scope of this change, especially changing `PrisonerSummary`, the number of files that have changed is large! All I can do is apologise!
=> RR-226 - Send prison ID in create and update goal API requests

.circleci/config.yml
This PR uncomments the CircleCI pre-prod config for the UI project (same as my [previous PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/82) for the API)
=> RR-269 - Enable the CircleCI pre-prod config

server/views/pages/goal/add-note/index.njk, server/views/pages/goal/update/index.njk, server/views/partials/layout.njk
For the ‘Edit goal page’ we would want the note field instruction text to have ‘Add to this note’ on the 'Create a goal page' we want a warning text with a message to say that other staff and prisoners can see the note
https://dsdmoj.atlassian.net/browse/RR-284
https://dsdmoj.atlassian.net/browse/RR-285
=> Updates to the "Note" form field on Update and Create a goal

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts
In preparation for the DPS Header and Footer changes, add the API endpoints for the different environments for the DPS frontend components.
Add `FRONTEND_COMPONENT_API_URL=https://frontend-components-dev.hmpps.service.justice.gov.uk` to your `.env` file.
https://dsdmoj.atlassian.net/browse/RR-143
=> RR-143 add the API endpoints for the DPS frontend components

server/views/pages/overview/partials/navigation.njk
This PR removes (comments out) the Timeline tab heading/link because it is not in scope for MVP
=> RR-302 - Commented out Timeline tab heading/link

README.md, feature.env, helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml, server/config.ts, server/routes/index.test.ts, server/routes/index.ts
This PR feature toggles the stub prisoner list page, so that it is only enabled in `dev` and integration tests. It is not enabled in preprod or prod.
You will need to add this to your local `.env` file for local development:
`STUB_PRISONER_LIST_PAGE_ENABLED=true`
=> RR-304 - Feature toggle the stub prisoner list page

server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/createGoal/createGoalController.test.ts, server/routes/createGoal/createGoalController.ts, server/routes/overview/overviewController.ts, server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts
This PR does some initial refactoring to group all forms associated with creating a goal into a single object.
The story that this is part of is about supporting creating multiple goals as part of the Create Goal process.
Currently we only support creating a single Goal at a time, and that single Goal (inc all of its steps) is shown on the Review Your Goals (check your answers) page.
The business objective of the story is to allow creating many Goals as part of the process, and showing each Goal on the check your answers page. In order to do this we need to refactor the data structures etc of how we store the Goal in session before we send it to the API
Currently we have a number of form types (one for each page in the multi-page 'wizard' process), and each of these form objects is held …
=> RR-153 - Initial refactoring of "create goal" form types

server/config.ts
This PR fixes `config.ts` to properly support booleans (we had the same problem in Send Legal Mail !)
Basically the problem is because javascript is meh! This definitely counts as one of [Javascript's weird parts](https://www.google.com/search?q=javascript+the+weird+parts&rlz=1C5GCEM_enGB1060GB1060&oq=javascript+the+w&aqs=chrome.1.69i57j0i512l2j0i22i30l2j69i60l3.3270j0j4&sourceid=chrome&ie=UTF-8)! 
Anyway, the problem is that the env variables are all read as strings. No matter what they are meant to represent, they are strings:
```
SOME_URL=http://localhost/...
SOME_NUMBER=4
SOME_BOOLEAN=false
```
They are all strings!
Now, here's the fun (weird!) part. Previously we had this kind of syntax in our `config.ts`:
```
frontendComponentsApiToggleEnabled: Boolean( …
```
=> RR-143 - Fix config.ts to properly support booleans

server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/createGoal/createGoalController.test.ts, server/routes/createGoal/createGoalController.ts, server/routes/createGoal/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts
This PR continues the refactoring of the session objects used in order to support creating multiple Goals as part of the Create Goal flow.
The refactoring here adds an array of NewGoal to the session, as well as the single NewGoal. At the end of the journey, when Add Note is submitted, the NewGoal that has been populated is pushed onto the array of NewGoals, so that (in theory) the Review Goals screen has access to an array of NewGoals.
At the moment we only reference element 0 in the array, so it still only supports 1 goal; but holding the Goals in an array structure is part of the changes we need to support multiples
=> RR-153 - Refactoring to support an array of NewGoal

assets/scss/print.scss
The “View note” link should be black so that it doesn’t use colour ink, usually we would hide links all together as they're not clickable on paper. But I think in this instance it needs the View note as a heading for context.
=> RR-303 make the view note link black on print

server/views/pages/overview/partials/supportNeedsTabContents.njk, server/views/pages/overview/partials/supportNeedsTabContents.test.ts
This PR restructures the Neurodiversity panel on the Support Needs page as per the new design (note - this PR only address the Neurodiversity panel - [the previous PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/173) has already refactored the LDD & Health needs panel).
=> RR-315 - Refactor Neurodiversity panel based on new design

assets/scss/print.scss
Hide the new DPS footer on print
We can't pass in CSS classes like we usually do (`govuk-!-display-none-print`) so we need to use the Sass mixin `@include govuk-visually-hidden();` in the print stylesheet instead.
Before:
After:
Hidden (not much to screenshot!)
=> RR-339 hide the new DPS footer on print

server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts, server/views/pages/functionalSkills/index.njk, server/views/pages/goal/add-note/index.njk, server/views/pages/goal/add-step/index.njk, server/views/pages/goal/create/index.njk, server/views/pages/goal/review/index.njk, server/views/pages/goal/update/index.njk, server/views/pages/goal/update/review.njk, server/views/pages/overview/index.njk, server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.njk, server/views/pages/overview/partials/qualificationsAndAchievementsSidebar.njk, server/views/pages/overview/partials/supportNeedsTabContents.njk, server/views/pages/overview/partials/workAndInterestsTabContents.njk, server/views/partials/breadcrumb.njk, server/views/partials/prisonerBanner.njk
Trim the whitespace from the Prisoners first and last name.
There was also an opportunity to reduce duplication by creating a shared Breadcrumb partial for a number of pages, so I have made the change so that don't repeat ourselves across a number of pages.
https://dsdmoj.atlassian.net/browse/RR-331
=> RR-331 trim whitespace from prisoner names and use a shared breadcrumb

server/routes/createGoal/createGoalController.test.ts, server/routes/createGoal/createGoalController.ts, server/testsupport/createGoalDtoTestDataBuilder.ts, server/testsupport/createGoalFormTestDataBuilder.ts
This PR changes the `submitReviewGoal` controller function so that it submits each Goal to the `createGoal` service/API
Previously it only submitted the first in the array, and I'd forgotten we need to do this as well! 🙄
=> RR-152 - Submit each goal to the API

server/config.ts
Use a more realistic time of 5 seconds for the frontend components timeout.
https://mojdt.slack.com/archives/C69NWE339/p1695206539474209
=> RR-146 use a more realistic time of 5 seconds for the frontend components timeout

server/views/pages/functionalSkills/index.njk, server/views/partials/breadcrumb.njk
fix incorrect page link in the breadcrumb partial that was introduced in https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/185/commits/e783b72ea8ab967823e92a21ebf05fe05e4ba229
This was easier than reverting the changes introduced due to various file changes in the commit.
Makes the shared partial breadcrumb use the correct link for the Overview page, but the "View all functional skills" page should link back to Education and training tab as its a sub section of that page.
=> fix incorrect page link in the breadcrumb partial

server/routes/index.test.ts, server/routes/index.ts, server/utils/nunjucksSetup.ts, server/views/pages/functionalSkills/index.njk, server/views/pages/overview/index.njk, server/views/partials/breadcrumb.njk
This PR uses the CIAG prisoner list page everywhere we would otherwise show our stub prisoner list page. 
Even though we have a feature toggle to control whether to show our stub prisoner list page or not, we know that we can only really use it as a development support page (ie. for our dev environments and integration tests)
The objective is to turn the feature toggle off in `dev`, `preprod` and `prod` (the last 2 are already done) and for those envs that do not have the feature toggle enabled to use the prisoner list page from CIAG. 
If the feature toggle is enabled (our dev machines and integration tests) then it should use out stub prisoner list page (we dont want our local dev or integration tests being dependent on a CIAG UI environment)
At the moment I've left `dev` with the …
=> RR-350 - Use CIAG prisoner list page

helm_deploy/values-prod.yaml
Production URL for curious API should be `.com`, not `.net`
=> Correct the URL for curious API in production

integration_tests/pages/page.ts
Now we plan to use conditional radio buttons from `govuk-frontend`, we were getting an accessibility error which were preventing the tests from passing.
The only time we use `aria` attributes is when we're using `govuk-frontend` components, so we're safe to disable this rule, as these components have been tested by the GDS team.
=> RR-368 disable the  rule in Axe to allow us to use conditional radios

server/@types/dto/index.d.ts, server/@types/forms/index.d.ts, server/@types/viewModels/index.d.ts, server/data/mappers/actionPlanMapper.test.ts, server/data/mappers/actionPlanMapper.ts, server/data/mappers/updateGoalMapper.test.ts, server/data/mappers/updateGoalMapper.ts, server/routes/updateGoal/mappers/goalToUpdateGoalFormMapper.test.ts, server/testsupport/actionPlanResponseTestDataBuilder.ts, server/testsupport/actionPlanTestDataBuilder.ts, server/testsupport/updateGoalDtoTestDataBuilder.ts
This PR follows on from the fine work @chrimesdev is currently doing with `targetCompletionDate` for the create goal journey.
It changes `targetCompletionDate` on the various Update Goal related classes and mappers to be a Date rather than a string.
As with the create goal related classes, its still an optional field at the moment. Once all the UI stuff is done we can go back to the API and make it mandatory
=> RR-338 - targetCompletionDate set as Date in Update Goal related view object, form & DTOs

server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
The list of Goals heading should be a level 3 heading as it sits under "Goals in progress" which is a level 2 heading.
=> use the correct heading level for goals overview list

server/@types/dto/index.d.ts
Make `targetGoalCompletionDate` mandatory in the create goal DTO.
Leaving the update goal DTO and Goal interface, until the work on update a goal is complete.
https://dsdmoj.atlassian.net/browse/RR-371
=> RR-371 make targetGoalCompletionDate mandatory in create goal dto

integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/e2e/goal/review.cy.ts, integration_tests/e2e/goal/updateGoal.cy.ts, integration_tests/pages/goal/CreateGoalPage.ts, integration_tests/pages/goal/UpdateGoalPage.ts, server/views/pages/goal/update/index.njk
This PR shows the error bars on the Update Goal `targetCompletionDate` when the field is in error (forgot to do it in my last PR) and adds some cypress tests to prove
=> RR-338 - Show error bars on `targetCompletionDate` on validation error

server/routes/updateGoal/reviewUpdateGoalView.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/views/pages/goal/update/review.njk
This PR adds the `targetCompletionDate` field to the Update Goal "review your answers" page.
We don't have any clear direction in the ticket as to where the field should be positioned / what the text should be (there are no links to the prototype or other screenshots), so I've followed my nose a little and based it on the review your answers page for Create Goal. If its wrong we can always change it 🤷
=> RR-338 - Added target completion date to the Update Goal Review screen

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
This PR configures the helm deployment so that the UI service pod is automatically shutdown and restarted in `dev` and `preprod` outside of working hours in order to save some AWS running costs.
The UI on `dev` and `preprod` has been configured to automatically 
* shutdown at 9pm UTC Monday to Friday
* startup at 6:30am UTC Monday to Friday
Therefore the UI in `dev` and `preprod` will be unavailable overnight between 9pm and 6:30 the next morning; and all weekend.
There will be a similar PR for the API shortly ....
=> RR-299 - Automatic shutdown/startup for dev and preprod

server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
Add hidden text to the goal overview update links, so that a screen reader has context as to what goal number they are updating.
https://dsdmoj.atlassian.net/browse/RR-389
=> RR-389 add hidden text to the goal overview update links

server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.njk
Add visually hidden text to the view all functional skills link, so that a screen reader has context to what the "View all" link is.
https://dsdmoj.atlassian.net/browse/RR-390
=> RR-390 add visually hidden text to the view all functional skills link

server/@types/forms/index.d.ts, server/routes/updateGoal/mappers/goalToUpdateGoalFormMapper.test.ts, server/routes/updateGoal/mappers/goalToUpdateGoalFormMapper.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/routes/updateGoal/updateGoalFormValidator.test.ts, server/testsupport/updateGoalFormTestDataBuilder.ts, server/validators/goalTargetCompletionDateValidator.test.ts, server/validators/goalTargetCompletionDateValidator.ts, server/views/pages/goal/update/index.njk
This PR fixes the bug that James found whilst testing the Update Goal screen in respect of the target completion date validation.
There were 2 problems:
* The date validator itself needed a little beefing up, in that it allowed some date values which where clearly invalid!!! (ie. apparently `][-08-2024` is a valid date! 🤣 
* We were not holding the original value of the target completion date (ie. from the goal's original state before any updates) - so when we submitted an invalid date, the value on screen became `Invalid date` 😢
=> RR-338 - Fix targetCompletionDate validation on Update Goal screen

server/views/pages/overview/partials/functionalSkillsSidebar.njk, server/views/pages/overview/partials/functionalSkillsSidebar.test.ts, server/views/pages/overview/partials/qualificationsAndAchievementsSidebar.njk
Update the overview sidebar content when curious is down.
Also use the correct heading level `<h3>` because it sits under a `<h2>` in the sidebar (Accessibility)
https://dsdmoj.atlassian.net/browse/RR-346
=> RR-346 update the overview sidebar content when curious is down

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, server/config.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
This PR adds google tag manager as per the code snippet/instructions provided in the story (albeit with a slight variant based on what we did in SLM to add the nonce and only include the code if there is a container ID in the config)
The container ID is fed into the config from the env var `GOOGLE_TAG_MANAGER_CONTAINER_ID` which in turn is provided by the kubernetes container secret `GOOGLE_TAG_MANAGER_CONTAINER_ID`
I have set the secret up for all 3 envs already 👍
=> RR-382 - Add Google Tag Manager

server/validators/goalTargetCompletionDateValidator.test.ts, server/validators/goalTargetCompletionDateValidator.ts
This PR fixes a problem with our date validation where it previously allowed a 2 digit year, but then got very confused when turning it into a date object, which in turn caused at error at the API (which wants a 4 digit year)
Date validation now checks for a 4 digit year:
=> RR-338 - Fix date validation so that years have to be entered as 4 digit years

server/@types/viewModels/index.d.ts, server/data/mappers/prisonerSummaryMapper.test.ts, server/data/mappers/prisonerSummaryMapper.ts, server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts, server/testsupport/prisonerSummaryTestDataBuilder.ts, server/testsupport/prisonerTestDataBuilder.ts
This PR is an enabler for some code we need to introduce in RR-395
In RR-395 we need to introduce a view model type to represent each prisoner record shown on the Prisoner List screen. The new type will be very similar to our existing `PrisonerSummary` type, so I am planning on creating a new type that extends `PrisonerSummary` with a few extra fields.
Crucially the new type needs to have the same date fields that `PrisonerSummary` has, but they need to be sortable, so they need to be proper `Date` instances rather than `string`s - hence this refactoring.
As it happens we already thought we'd need to do this at some point as evidence by the TODO (that is now addressed)
My next PR will look to add the new type that extends `PrisonerSummary`, but I wanted to get this in first as an enabled …
=> RR-395 - Refactor date fields in PrisonerSummary

server/views/partials/prisonerBanner.njk
Change the word for Reception date to Entered prison on in the Prisoner summary bar.
> Note: There some comments on the JIRA ticket around the widths and styling; this is out of scope and should be another ticket if we want to change the styling.
https://dsdmoj.atlassian.net/browse/RR-361
=> RR-361 change the wording for reception date

server/views/pages/goal/update/review.njk
Use tag component for the status of goals/steps on update review. Includes moving the "Status" of the goal to the top of the Summary list.
I've changed the Step status logic to a similar approach to the Goal status for consistency.
https://dsdmoj.atlassian.net/browse/RR-417
=> RR-417 use tag component for the status of goals/steps on update review

server/routes/prisonerList/pagedPrisonerSearchSummary.test.ts, server/routes/prisonerList/pagedPrisonerSearchSummary.ts, server/testsupport/prisonerSearchSummaryTestDataBuilder.ts
This PR introduces the class `PagedPrisonerSearchSummary` which has methods to sort, filter and pagination a list of `PrisonerSearchSummary`
The idea is that `PagedPrisonerSearchSummary` is essentially a "view model" class and it will be used by the (yet to be developed) Prisoner List controller and nunjucks view. 
Normally we do "view models" as types (interfaces) in the `@types` folder, but this needs to be more than just an interface because it needs to have some behaviours. Specifically it needs to do sorting, filtering and pagination.
My thinking is that the controller (yet to be written) will call a service (yet to be written) that returns a collection of `PrisonerSearchSummary` instances. (`PrisonerSearchSummary` already exists).
The controller will then new up a …
=> RR-400 - introduced PagedPrisonerSearchSummary 

server/@types/educationAndWorkPlanApiClient/index.d.ts, server/@types/prisonerSearchApiClient/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/data/prisonerSearchClient.test.ts, server/data/prisonerSearchClient.ts, server/routes/routerRequestHandlers.test.ts, server/services/index.ts, server/services/prisonerListService.ts, server/testsupport/actionPlanSummaryListResponseTestDataBuilder.ts, server/testsupport/actionPlanSummaryResponseTestDataBuilder.ts, server/testsupport/pagedCollectionOfPrisonersTestDataBuilder.ts, server/testsupport/prisonerSearchSummaryTestDataBuilder.ts, server/testsupport/prisonerTestDataBuilder.ts
This PR adds the skeleton Prisoner List Service class (but no methods in it yet), and makes the changes to the client classes in order to get API data we will need.
Specifically we need to call the "get all prisoners in the specified prison" API from `prisoner-search-api`; and the "get action plan summaries for specified prison numbers" from `education-and-work-plan-api`
(We will also need to call a similar API on the CIAG API - to get all CIAG Induction summaries for the specified prison numbers - but that does not exist yet. The CIAG API dev team are working on it as we speak 🤞 )
The basic idea is that the new Prisoner List Service class will need a method that:
* Calls the `prisoner-search-api` to get all prisoners in the specified prison. 
* With the resulting list of prisoners it …
=> RR-395 - Added skeleton Prisoner List Service, and supporting client class methods

server/@types/ciagInductionApi/index.d.ts, server/@types/ciagInductionApiClient/index.d.ts, server/data/ciagInductionClient.test.ts, server/data/ciagInductionClient.ts, server/testsupport/ciagInductionListResponseTestDataBuilder.ts
This PR re-imports the CIAG API spec to get their new endpoint that returns the CIAG Inductions for a given list of prisoners; then adds the corresponding method to the `CiagInductionClient` class
=> RR-395 - Imported latest CIAG API swagger spec; added client method to get CIAG Inductions for prisoner list

assets/js/mojukFrontendInit.js, assets/scss/application.scss, assets/scss/components/_prisoner-list.scss, server/routes/index.ts, server/routes/prisonerList/index.ts, server/routes/prisonerList/prisonerListController.ts, server/views/pages/prisonerList/index.njk, server/views/pages/prisonerList/partials/searchBox.njk, server/views/pages/prisonerList/partials/searchTable.njk, server/views/partials/layout.njk
> This is still in progress, just opening a draft PR to keep track and be able to annotate changes as we go.
Setup the routing for the new Prisoner list view, which is behind the `plpPrisonerListAndOverviewPagesEnabled` feature toggle.
For now, the Prisoner list is just really an "enhanced" version of stubbed prisoner list, showing 2 stubbed prisoners (one with a plan and one without). Once we've got some data coming through, this will change.
There was a little bit of missing configuration needed for the MoJ Frontend library JavaScript, to ensure that the JavaScript is initialised. 
https://dsdmoj.atlassian.net/browse/RR-399
Without the Search box:
With the Search box:
=> RR-399 setup prisoner list views with basic prisoner search table

server/utils/nunjucksSetup.ts
This PR makes the 'Manage learning and work progress' breadcrumb URL dependent on our new `plpPrisonerListAndOverviewPagesEnabled` feature toggle.
The logic is that the breadcrumb URL is `/` (ie. the root page on our service) if either `plpPrisonerListAndOverviewPagesEnabled` or `stubPrisonerListPageEnabled` are `true`; else the URL is the CIAG Induction URL from the config.
In respect of 2 feature toggles resulting in the same URL (`/`), this is then subsequently handled in the routing config in @chrimesdev 's fine work in [PR #252](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/252)
=> RR-409 - Made the 'Manage learning and work progress' breadcrumb URL dependent on feature toggle

server/views/pages/goal/create/index.njk
Bugfix to treat the prisoner's name as safe markup (trusted), which means special characters are correctly rendered.
This is how the page now renders, with the apostrophe in `'Incentine`'s name being correctly rendered (see jira ticket for screenshot of how it renders without this fix)
=> RR-445 - Correctly render prisoner name on Create Goal screen

server/@types/viewModels/index.d.ts, server/data/mappers/inductionQuestionSetMapper.test.ts, server/data/mappers/inductionQuestionSetMapper.ts, server/data/mappers/otherQualificationsMapper.test.ts, server/data/mappers/otherQualificationsMapper.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/services/ciagInductionService.test.ts, server/services/ciagInductionService.ts, server/services/index.ts, server/testsupport/ciagInductionTestDataBuilder.ts, server/testsupport/workAndInterestsTestDataBuilder.ts
This PR introduces a new field `inductionQuestionSet` to the view models `WorkAndInterests` and `OtherQualifications`, and maps it from the `hopingToGetWork` answer in the CIAG data.
This is an enabler PR where the new field `inductionQuestionSet` is required for us to render different content on the "Work and interests" tab and "Education and training" tab based on whether the prisoner did the "short" or "long" route/flow in their CIAG Induction.
I've tried to steer clear from using terminology like "route" or "flow", and indeed "CIAG" Induction. Instead I've seen it as the type of question set that was presented at the Induction. It was either the short or long question set. The problem with "flow" is that it implies a specific route or flow through the system, and we've already seen …
=> RR-439 - Map `inductionQuestionSet` from `hopingToGetWork` from CIAG data

assets/scss/print.scss, server/views/pages/functionalSkills/index.njk, server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.njk, server/views/pages/overview/partials/educationAndTrainingTab/_inPrisonQualifications.njk, server/views/pages/overview/partials/educationAndTrainingTab/_otherQualifications.njk, server/views/pages/overview/partials/overviewTab/overviewTabPostInduction.njk, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
Use full width on print on all pages to prevent text overrunning, also reduce the spacing of the page margins on print.
https://dsdmoj.atlassian.net/browse/RR-449
=> RR-449 use full width to prevent text overrunning

server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/testsupport/ciagInductionTestDataBuilder.ts
This PR correctly sets the last updated by/at fields on the Work & Interest tab, based on whether the main 'top level' induction, or the future Work Interests were the last thing to be updated.
=> RR-439 - Correctly set the last updated by/at fields on the Work & Interest tab

server/@types/viewModels/index.d.ts, server/data/mappers/educationAndTrainingMapper.test.ts, server/data/mappers/educationAndTrainingMapper.ts, server/testsupport/educationAndTrainingTestDataBuilder.ts, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
Move the `Updated at` & `Updated by` values out of the parent and duplicate them into the `EducationAndTrainingLongQuestionSet` and `EducationAndTrainingShortQuestionSet`. 
Then separate out the `inPrisonInterestsEducation` to allow for individual `updatedAt` and `updatedBy` for the "Training and education interests in prison" section
The data displayed remains the same as before, until we do the work for the mapping/data sources.
=> RR-441 duplicate the updated at/by in education and training 

server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk
This PR corrects the change link for qualifications on the Education and Training tab, for both the long and short question set.
Having spoken with Gary there is only 1 change link, regardless of whether its the long or short question set, and regardless of whether the Induction already has qualifications recorded or not.
The target of the change link is `{{ ciagInductionUrl }}/plan/create/{{ prisonerSummary.prisonNumber }}/qualifications-list/update`
The difference that we need to cater for, and that this PR corrects, is the non-visual text for screen readers.
I have changed is so that:
* If there are already qualifications, the text (inc. non-visible) is `Change qualifications by adding or removing qualifications`
* If there are no qualifications (irrespective of why / question set), …
=> RR-457 - Correct change link for qualifications

server/data/mappers/educationAndTrainingMapper.test.ts, server/data/mappers/educationAndTrainingMapper.ts
Correctly set the last updated by/at fields on the Education & training tab for the "Training and education interests in prison" section (short question set).
This scenario shows the Training and education interests in prison section was updated Today by me, but the Qualifications and education history section was updated yesterday by Nathan
=> RR-441 correctly set the last updated by/at fields on the Education & training tab

server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
Prefix the phrase `Other - ` everywhere where we render an answer for “other”
=> RR-462 prefix other answers with Other -

server/@types/viewModels/index.d.ts, server/data/mappers/jobComparator.test.ts, server/data/mappers/jobComparator.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/testsupport/ciagInductionTestDataBuilder.ts, server/testsupport/workAndInterestsTestDataBuilder.ts, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR implements a comparator function to sort a prisoners post-release work interests alphabetically by job type with Other always at the end.
There was a little related refactoring that needed doing; plus testing locally identified a related problem with how and where we map/render "Other" for these future work interests.
=> RR-459 - Sort a prisoner's work interests based on job type

server/@types/viewModels/index.d.ts, server/data/mappers/educationAndTrainingMapper.ts, server/data/mappers/educationalQualificationComparator.test.ts, server/data/mappers/educationalQualificationComparator.ts
This PR sorta a prisoner's educational qualifications based on qualification level, subject and grade.
This is slightly complex in that there are 3 comparison operations in order to achieve the correct sort:
1. Compare based on level - alphabetically reversed (so that LEVEL_8 comes before LEVEL_7 which comes before ENTRY_LEVEL)
2. Compare based on subject - alphabetically so that French comes before Maths
3. Compare based on grade - alphabetical so that A comes before B (though note the comments in the function re: this comparison field)
=> RR-459 - Sort a prisoner's educational qualifications based on qualification level, subject and grade

server/views/pages/goal/add-note/index.njk
Associate `textarea` of the Note with the warning message.
Had to move away from the Nunjucks macro here as the Nunjuck macro does not allow you to pass an `id` (because we're not using the correct component in the designs)
https://dsdmoj.atlassian.net/browse/RR-454
=> RR-454 associate textarea with warning message

server/views/pages/functionalSkills/index.njk, server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.njk
Display visually hidden table column to all users as this is likely to be confusing for several user groups, in particular low-vision screen reader users, who will be able to partially see the screen and not understand why the screen reader is reading out elements that aren’t visible.
https://dsdmoj.atlassian.net/browse/RR-455
=> RR-455 display visually hidden table column

server/views/pages/functionalSkills/index.njk, server/views/pages/overview/index.njk, server/views/pages/prisonerList/index.njk, server/views/partials/breadcrumb.njk
Improve the Breadcrumb navigation markup, by using a semantic `<nav>` element and `aria-label="Breadcrumb"`
As mentioned in the Accessibility report, this is actually different to how GDS markup the Breadcrumb and needs to be reported.
Interestingly its the same as how the NHS Design System does it!
https://dsdmoj.atlassian.net/browse/RR-452
=> RR-452 improve the Breadcrumb navigation markup

server/routes/prisonerList/prisonerListController.test.ts, server/routes/prisonerList/prisonerListView.ts, server/views/pages/prisonerList/partials/searchTable.njk
Initial UI implementation for pagination
`renderPaginationControls` checks to see if there are more than 1 `totalPages` from the `pagedPrisonerSearchSummary` to determine whether to render the MoJ pagination component in the Nunjucks template.
`items` is the main array of data required to render the MoJ pagination, built from the `pagedPrisonerSearchSummary`, this includes the Page number and Link href for the pagination 
`results` is the data needed to show the `Showing X to Y of Z results` text, again built from `pagedPrisonerSearchSummary` 
`previousPage` and `nextPage` is the href value required for the Next/Previous pages
- Look at rendering the different pages of results using the query parameters `?page=X` used in the `items` array
- Handle displaying "a window" of 10 pagination …
=> RR-438 initial UI implementation for pagination

server/routes/prisonerList/prisonerListView.ts
Return 10 pages, showing 5 pages before and after the current page
Rules taken from: https://github.com/ministryofjustice/hmpps-manage-users/blob/main/backend/services/paginationService.js#L6C24-L6C49 which the CIAG service uses.
Showing 10 from the start (as there aren't 5 previous pages)
Showing 5 either side
Showing 10 from the end (as there aren't 5 next pages)
=> RR-438 return 10 pages in the pagination showing 5 before/after

server/@types/express/index.d.ts, server/routes/prisonerList/prisonerListController.test.ts, server/routes/prisonerList/prisonerListController.ts
This PR corrects the default sort order on the Prisoner List page (should have been reception-date descending, as per the ticket)
Also (as per the ticket), persist the last used sort order in the session, so that when the CIAG goes to an Induction or Action Plan of a prisoner, when they come back to the Prisoner List page their last sort order is maintained.
=> RR-467 - Corrected default sort order; maintain sort order in session

cypress.config.ts, integration_tests/e2e/prisonerList/prisonerList.cy.ts, integration_tests/mockApis/ciagInducationApi.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, integration_tests/mockApis/prisonerListApi.ts, integration_tests/mockData/prisonerSearchSummaryMockDataGenerator.ts, integration_tests/tsconfig.json
This PR sets up stubs with large numbers of prisoner records (725) for the Prisoner List page so that we can write tests that make assertions about the functionality of the page, such as paging, sorting, filtering etc (These new tests are not in this PR, this is just about setting up the data so that we can write those tests)
The result of this PR is that the Prisoner List cypress tests now render lots of data like this:
...
=> RR-436 - Setup stubs of large numbers of prisoners for the Prisoner List page cypress tests

server/routes/prisonerList/pagedPrisonerSearchSummary.test.ts, server/routes/prisonerList/pagedPrisonerSearchSummary.ts
This PR updates the filtering by name functionality for the Prisoner List page so that it is functionally equivalent to the current CIAG UI Prisoner List page. Specifically this means that when filtering prisoners by name we will consider:
* prisonNumber // eg: A1234BB
* firstName // eg: JIMMY
* lastName // eg: LIGHTFINGERS
* firstName, lastName // eg: JIMMY, LIGHTFINGERS
* firstName lastName // eg: JIMMY LIGHTFINGERS
* lastName, firstName // eg: LIGHTFINGERS, JIMMY
* lastName firstName // eg: LIGHTFINGERS JIMMY
* firstName.charAt(0) lastName // eg: J LIGHTFINGERS
The only unusual / controversial part of this is that filtering by name includes the prisoner's prison number 🤔 
This is what the CIAG UI currently does though 🤷‍♂️
=> RR-400 - Enhance prisoner list filtering to be in line with current CIAG UI

integration_tests/e2e/prisonerList/prisonerList.cy.ts, integration_tests/mockData/prisonerSearchSummaryMockDataGenerator.ts, integration_tests/pages/prisonerList/PrisonerListPage.ts, server/routes/prisonerList/prisonerListController.test.ts, server/routes/prisonerList/prisonerListView.ts, server/views/pages/prisonerList/partials/searchTable.njk
This PR adds cypress tests for sorting and filtering operations on the Prisoner List page.
It also makes a change to the nunjucks markup and view file so that the count of records is always present, even if there is only 1 page to display:
=> RR-436 - Cypress tests for sorting and filtering

server/services/ciagInductionService.test.ts, server/services/ciagInductionService.ts
RR-444 needs to show different content on the Overview screen depending on whether there is a CIAG induction or not for the prisoner.
In order to do this we need a service method that determines if there is a CIAG Induction or not for the specified prison number.
This PR introduces the service method (but does not wire it in yet)
=> RR-444 - Service method to determine if a CIAG Induction exists or not

server/config.ts
This PR is one of the subtasks for RR-484 (configure App Insights in the UI), and adds the App Insights connection string to the config object.
(It was actually easier than I thought because the `APPLICATIONINSIGHTS_CONNECTION_STRING` env var is already setup in the helm values file (I was assuming I'd have to do that and some k8s stuff as well), so arguably does not warrant it's own subtask, but I've done it now 😁 )
=> RR-484 - Add app insights connection string to the config

assets/scss/application.scss, assets/scss/components/_add-another.scss, server/views/pages/goal/add-step/index.njk, server/views/pages/goal/create/index.njk, server/views/pages/goal/update/index.njk, server/views/partials/layout.njk
Use a character count component with a text limit of 512 on the Add & Update a goal flow.
There was also an issue with the spacing on the MoJ Add another component conflicting with the GOVUK error message styling; so there is an admittedly horrible CSS fix in here to resolve it.
Before: 
After:
https://dsdmoj.atlassian.net/browse/RR-340
=> RR-340 use a character count component on the add/update goal flows

assets/js/applicationinsights.js, package-lock.json, package.json, server/middleware/setUpStaticResources.ts, server/middleware/setUpWebSecurity.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
This PR adds the Application Insights client code to the rendered page markup that the application serves.
It adds it in the `layout.njk` file (so that all pages get it) and it adds it to the bottom of the page with all the other javascript includes so as to not block rendering of the page.
=> RR-484 - Add app insights client code

assets/js/applicationinsights.js, package-lock.json, package.json, server/middleware/setUpStaticResources.ts, server/views/partials/layout.njk
This PR adds the MS App Insights `ClickAnalyticsPlugin` to the page so that click events are sent to App Insights (as well as page views)
Click Events are recorded in App Insights as Custom Events. This story is to record clicks to the "Print this page" link. Whilst many page click events are recorded, it is easy to query and filter for just the ones of interest:
=> RR-470 - configured ClickAnalyticsPlugin to send click events to App Insights

integration_tests/e2e/overview/postInductionOverview.cy.ts, integration_tests/e2e/overview/preInductionOverview.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/views/pages/overview/index.njk
This PR is for our new Overview tab, and in particular the pre-induction version of the screen. On the pre-induction Overview tab we do not show the `Print this page` link
=> RR-492 - Remove `Print this page` from pre-induction Overview tab

integration_tests/e2e/overview/preInductionOverview.cy.ts, integration_tests/e2e/prisonerList/prisonerList.cy.ts, integration_tests/pages/ciagUi/createCiagInductionPage.ts, server/routes/prisonerList/prisonerListController.test.ts, server/routes/prisonerList/prisonerListController.ts
This PR handles errors from the 3 APIs that the Prisoner List page calls (`prisoner-search`, `ciag-api`, `plp-api`) and displays the generic error screen
(The data from all 3 APIs is required to be able to display the Prisoner List page, so if any of the 3 fail there is nothing that the user can do at that point. Its pretty much an end game and all we can do is show the error page)
=> RR-490 - Catch errors when calling APIs for prisoner-list page and redirect to error page

server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
Hide change links on print for education and training
Example: 
[Prisoner's learning and work progress - Digital Prison Services.pdf](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/files/13427018/Prisoner.s.learning.and.work.progress.-.Digital.Prison.Services.pdf)
https://dsdmoj.atlassian.net/browse/RR-495
=> RR-495 hide change links on print for education and training

server/filters/formatTimelineEvent.test.ts, server/filters/formatTimelineEvent.ts, server/services/timelineService.ts
Display "Learning and work progress plan updated" events on the Timeline UI which is the `INDUCTION_UPDATED` event in the API.
https://dsdmoj.atlassian.net/browse/RR-474
=> RR-474 display learning and work progress plan updated events on timeline

server/data/index.ts, server/data/prisonRegisterClient.ts, server/routes/overview/overviewController.ts, server/services/index.ts, server/services/prisonService.test.ts, server/services/prisonService.ts, server/services/timelineService.test.ts, server/services/timelineService.ts
This PR completes the prison name lookup, populating the prison name into each `TimelineEvent`
=> RR-480 - Wired PrisonService into timelineService to lookup prison names for each TimelineEvent

server/config.ts
Removed `PRISON_REGISTER_API_DEFAULT_PAGE_SIZE` which was added by accident previously (copy and paste error!) and is preventing the pods starting up!
=> RR-480 - Removed PRISON_REGISTER_API_DEFAULT_PAGE_SIZE

server/routes/timelineResolver.test.ts, server/routes/timelineResolver.ts, server/services/timelineService.ts
Error handling in the `timelineResolver` if there is no Timeline data passed or there was a problem retrieving data. Previously the page would completely crash but now it just returns an empty page.
Error messaging and further tests for handling "empty states" or "error states" will be done as part of https://dsdmoj.atlassian.net/browse/RR-481 when its ready for dev.
The prisoner in the screenshot has no Timeline, because they have no plan, so an empty page is shown (ready for empty state messaging) which will be separate to the `problemRetrievingData` messaging.
=> RR-475 handle no timeline data in the timelineResolver

server/views/pages/overview/partials/timelineTab/timelineTabContents.njk
Add content for displaying no timeline and content for error state 
https://dsdmoj.atlassian.net/browse/RR-528
https://dsdmoj.atlassian.net/browse/RR-481
=> RR-481 add content for displaying no timeline and content for error state

server/filters/formatFunctionalSkillTypeFilter.test.ts, server/filters/formatFunctionalSkillTypeFilter.ts, server/filters/formatGoalStatusValueFilter.test.ts, server/filters/formatGoalStatusValueFilter.ts, server/filters/formatStepStatusValueFilter.test.ts, server/filters/formatStepStatusValueFilter.ts, server/filters/formatTimelineEventFilter.test.ts, server/filters/formatTimelineEventFilter.ts, server/utils/nunjucksSetup.ts
PR to make a minor correction to the "Goal added" and "Goals added" wording on the timeline.
This is a small change to the filter and it's test, but I also took the opportunity to rename the last few filter classes and functions that did not have the `Filter` suffix. They now all have the suffix `Filter` in the filename and function name, so are all consistent 👍
=> RR-475 - Corrected wording in filter; renamed filters for consistency

assets/scss/print.scss
Display the line on print, for the Timeline.
Because of how the Timeline component is built in the MoJ Design System, the Timeline "line" isn't show on print. This is because it uses `::before` pseudo-elements to style the line, which gets ignored by print, because its a pseudo-element.
https://dsdmoj.atlassian.net/browse/RR-539
=> RR-539 display the line on print timeline

assets/scss/print.scss, server/views/pages/overview/partials/timelineTab/timelineTabContents.njk
Hide the timeline description on print to prevent whitespace and remove extra spacing between timeline events
=> RR-539 hide the timeline description on print to prevent whitespace

assets/scss/components/_prisoner-list.scss, assets/scss/local.scss, server/views/pages/prisonerList/macros/sortableTableHeader.njk, server/views/pages/prisonerList/partials/searchBox.njk, server/views/pages/prisonerList/partials/searchTable.njk
Use the DPS homepage search component for prisoner search. 
https://github.com/ministryofjustice/hmpps-digital-prison-services/blob/main/server/views/partials/homepage/search.njk
https://github.com/ministryofjustice/hmpps-digital-prison-services/blob/main/assets/scss/pages/_homepage.scss#L60-L102
Also remove `aria-label` on the sortable button in favour of a `table > caption` as recommended by the audit.
https://dsdmoj.atlassian.net/browse/RR-465
=> RR-465 use the DPS homepage search component for prisoner search

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml
This PR moves the modsec config to handle false positives for rule 942440 (that we added to `dev` only right before the Xmas code freeze) from `dev` to the main config so that it gets applied to all envs
=> RR-538 - Handle modsec false positives for rule 942440 in all envs

integration_tests/e2e/postInductionCreation/postInductionCreation.cy.ts, integration_tests/mockData/actionPlanByPrisonNumberData.ts, server/routes/index.ts, server/routes/postInductionCreation/index.ts
This PR create a new PLP route `/plan/:prisonNumber/induction-created` that is designed to be the redirect URL from the CIAG UI at the end of creating an induction (rather than the current redirect to start the create a goal journey)
The new route is simply a middleware handler that calls the PLP API to see if the prisoner has any goals or not. If the prisoner has no goals then redirect to the create goal journey (IE. as the CIAG UI does currently). 
If the prisoner has goal(s) (ie. one or more goals have been created before the CIAG Induction was completed) then redirect to the overview screen.
There will be a corresponding PR on the CIAG UI codebase to redirect to this new route, but this change can be reviewed and merged without any impact.
=> RR-544 - New route for post (after) create induction

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
This PR (hopefully) fixes the modsec config so that:
a) Our GH team (farsight-devs) have access to read the logs
b) the response codes are 406
It seems that this functionality regressed when I added the `modsecurity_snippet` in my last PR, and that (based on what other projects are doing) if you dont specify a `modsecurity_snippet` you get all this functionality for free, but if you do specify one you need to specify everything in it!
Doh!
=> RR-538 - Update modsec config

server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/educationAndWorkPlanApiClient/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/testsupport/inductionResponseTestDataBuilder.ts
This PR imports the latest Education and Work Plan API swagger spec, and implements the `getInduction` method in the client class.
A basic test data builder has been added to build `InductionResponse` instances - the child fields will be built upon and improved over the course of subsequent PRs for this story
=> RR-526 - Update swagger spec; add client method for `getInduction`

server/@types/educationAndWorkPlanApiClient/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/mappers/educationAndTrainingMapper.test.ts, server/data/mappers/educationAndTrainingMapper.ts, server/data/mappers/inductionQuestionSetMapper.test.ts, server/data/mappers/inductionQuestionSetMapper.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/testsupport/inductionResponseTestDataBuilder.ts
This PR adds the mappers to map from the PLP API's `InductionResponse` to the view models `EducationAndTraining` and `WorkAndInterests`
The mappers and tests are based heavily on the existing `CiagInduction` mappers (that were moved to a separate source file in the last PR). The tests are the exact same tests as the originals (in respect of test scenarios and expected outcomes), and the source files and exports, and test files, are the same filenames are the originals.
At the moment nothing uses these new mappers - that will come in the next PR 🤞
=> RR-526 - Added Induction mappers

server/@types/educationAndWorkPlanApi/index.d.ts, server/services/index.ts, server/services/inductionService.test.ts, server/services/inductionService.ts, server/testsupport/inductionResponseTestDataBuilder.ts
This PR adds a new service class `InductionService`
In terms of it's interface it is equivalent to the existing `CiagInductionService` having methods to get the work & interests, education & training, and to determine if a prisoner has an induction or not, but in terms of it's implementation it uses the PLP API client rather than the CIAG API client
At the moment this just introduces this new service class and it's unit tests. It is not wired in yet. That will be my next PR where I remove the `CiagInductionService` and replace its use with this new service class etc.
Also in this PR I've re-imported the PLP API swagger spec to get the recently added `prisonNumber` field in the `InductionResponse` 👍
=> RR-526 - Added inductionService

helm_deploy/hmpps-education-and-work-plan-ui/Chart.yaml
This PR bumps the version of the dependencies in the helm chart to the latest versions:
```
➜  hmpps-education-and-work-plan-ui git:(main) helm search repo hmpps-helm-charts
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
hmpps-helm-charts/clamav                                0.1.7           1.0             A Helm chart for Kubernetes                       
hmpps-helm-charts/generic-data-analytics-extractor      1.1.0                           Runs a daily cron job which extracts and sends ...
hmpps-helm-charts/generic-prometheus-alerts             1.3.3           1.0.0           Creates a set of standard prometheus alert rule...
hmpps-helm-charts/generic-service                       2.9.0 …
```
=> RR-540 - Update dependencies in helm chart

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml
This PR enables the `USE_NEW_INDUCTION_API_ENABLED` feature toggle in all environments which tells the PLP UI to use the new Induction API to retrieve inductions, rather than the old/migrated CIAG API
This feature has been enabled in `dev` for over a week now, so I am confident we can roll this out and promote to the other environments
=> RR-526 - Enable feature toggle in all envs to use new Induction API

server/routes/timelineResolver.test.ts, server/routes/timelineResolver.ts
Now that we will soon be displaying Prison movement related events on the Timeline, the existing logic of always ensuring that the `ACTION_PLAN_CREATED` event appears last is no longer valid. Instead, we need to ensure that it appears after any related `GOAL_CREATED` events (i.e. events that occurred at exactly the same time), but still in reverse chronological order in relation to other unconnected events.
=> RR-611 Update timelineResolver ensure correct ordering

server/filters/formatPrisonMovementEventFilter.test.ts, server/filters/formatPrisonMovementEventFilter.ts, server/services/timelineService.test.ts, server/services/timelineService.ts, server/testsupport/timelineEventTestDataBuilder.ts, server/utils/nunjucksSetup.ts, server/views/pages/overview/partials/timelineTab/timelineTabContents.njk
This PR modifies the nunjucks template for the Timeline, so that a prisoner's history of prisons is included in the view as follows:
As can be seen, the formatting for the prison movements is different to other events and does not include the name of the user who performed an action.
I will add an integration test in my next PR and also enable the `INCLUDE_PRISON_TIMELINE_EVENTS_ENABLED` feature toggle.
=> RR-612 Timeline prison movements nunjucks template

server/@types/viewModels/index.d.ts, server/data/mappers/ciagInductionResponseMappers.test.ts, server/data/mappers/ciagInductionResponseMappers.ts, server/data/mappers/workAndInterestMapper.test.ts, server/data/mappers/workAndInterestMapper.ts, server/testsupport/ciagInductionTestDataBuilder.ts, server/testsupport/workAndInterestsTestDataBuilder.ts, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
Display first name and last name for the "Last updated" on the Work and Skills tab. This is instead of displaying the DPS username. 
https://dsdmoj.atlassian.net/browse/RR-414
**Long question set**
**Short question set**
=> RR-414 display first name and last name on the work and skills

server/services/inductionService.test.ts, server/services/inductionService.ts
This PR is based on a conversation that @mattwills-moj-digital and I had earlier, and is to improve the error handling and logic of `InductionService`, specifically around `getInduction`
Contrary to what I originally committed, getInduction needs to throw an exception from the client, even if it is a 404. Unlike the other methods, a 404 is not a "happy" or "handled" scenario, so we need to throw the exception back.
The other methods in this class have also been changed. Their method signatures are correct, but their implementation was wrong in the case of a 404 (induction not found). They should always return an object, and should not return `undefined`
=> RR-647 - Improve error handling of getInduction in inductionService

server/routes/induction/common/personalInterestsController.ts, server/routes/induction/common/personalInterestsView.ts, server/routes/induction/common/skillsController.ts, server/routes/induction/common/skillsView.ts, server/routes/induction/update/index.ts, server/routes/induction/update/personalInterestsUpdateController.ts, server/routes/induction/update/skillsUpdateController.ts
This PR defines the routes and basic skeleton controllers for updating 'Skills' and 'Personal Interests' on the Induction. (ie. the 2 questions in the PLP 'Skills & interests' section.
@chrimesdev will need these routes and basic GET controller methods to be able to complete the subtask he is working on (nunjucks templates for these 2 pages)
=> RR-645 - Routes and basic controllers

server/routes/induction/update/personalInterestsFormValidator.test.ts, server/routes/induction/update/personalInterestsFormValidator.ts, server/routes/induction/update/skillsFormValidator.test.ts, server/routes/induction/update/skillsFormValidator.ts
This PR defines the form validators for `SkillsForm` and `PersonalInterestsForm`
The validation rules and messages have been copied verbatim from the CIAG UI, though the implementation is different (being based on our patterns, not theirs)
=> RR-645 - Form validators

server/views/pages/induction/hasWorkedBefore/index.njk
This PR migrates the nunjucks template for the "Has <name> worked before?" screen from the CIAG UI
Note: it is just the nunjucks template - the route def and controller etc will come in my next PR
=> RR-646 - Added nunjucks template for the "Has <name> worked before?" screen

server/views/pages/induction/workedBefore/index.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR makes use of the `workExperienceSectionEnabled` feature toggle to either use the legacy CIAG UI, or this one when updating a prisoner's "has worked before" question.
=> RR-661 Update "has worked before" view

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Temporarily increasing mod security log level to log, errors, warnings and notices with information.
Will revert after testing in dev. **This change should not be deployed to production**
=> Temporarily increase modsec log level to investigate request blocking

server/views/pages/induction/previousWorkExperience/workExperienceDetail.njk, server/views/pages/induction/previousWorkExperience/workExperienceTypes.njk
This PR migrates the nunjucks template for previous work experience details (called `workDetails` in the CIAG UI). Here we have decided to call it `previousWorkExperience/workExperienceDetails.njk`
As discussed and agreed with @mattwills-moj-digital I have also renamed the previously merged `previousWorkExperience/index.njk` file to `previousWorkExperience/workExperienceTypes.njk`
=> RR-646 - Migrated nunjucks for previous work experience details page

server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/enums/workInterestTypeValue.ts, server/routes/induction/common/inPrisonWorkController.ts, server/routes/induction/common/personalInterestsController.ts, server/routes/induction/common/skillsController.ts, server/routes/induction/common/workInterestTypesController.ts, server/routes/induction/common/workInterestTypesView.ts, server/routes/induction/common/workedBeforeController.ts, server/routes/induction/update/index.ts, server/routes/induction/update/previousWorkExperienceDetailUpdateController.ts, server/routes/induction/update/workInterestTypesFormValidator.test.ts, server/routes/induction/update/workInterestTypesFormValidator.ts, server/routes/induction/update/workInterestTypesUpdateController.test.ts, server/routes/induction/update/workInterestTypesUpdateController.ts, server/testsupport/inductionDtoTestDataBuilder.ts, server/testsupport/updateInductionDtoTestDataBuilder.ts, server/testsupport/updateInductionRequestTestDataBuilder.ts, server/views/pages/induction/workInterests/workInterestTypes.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR adds the controller etc for the future work interest "types" page (which is distinct from a separate page for providing "details" of the work type):
I'll add cypress tests in a separate PR, but this appears to work ok on my local machine.
=> RR-680 Route, controller and validator for Future Work Interest Types

server/views/pages/induction/personalInterests/index.njk, server/views/pages/induction/workInterests/workInterestRoles.njk, server/views/pages/induction/workInterests/workInterestTypes.njk
This PR adds the nunjucks template for the Future Work Interest Roles page:
=> RR-671 View template for future work interest roles

server/@types/dto/index.d.ts, server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/induction/common/workInterestRolesController.ts, server/routes/induction/common/workInterestRolesView.ts, server/routes/induction/update/index.ts, server/routes/induction/update/workInterestRolesUpdateController.test.ts, server/routes/induction/update/workInterestRolesUpdateController.ts, server/views/pages/induction/workInterests/workInterestRoles.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR adds the route and controllers for submitting an optional `role` for each previously selected future work interest, as per this screenshot:
=> RR-687 Controllers for updating work interest roles

integration_tests/pages/inPrisonCoursesAndQualifications/InPrisonCoursesAndQualificationsPage.ts, server/routes/functionalSkills/index.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsView.ts, server/routes/inPrisonCoursesAndQualifications/index.ts, server/routes/index.ts, server/views/pages/inPrisonCoursesAndQualifications/index.njk
This PR introduces the initial skeleton route, controller and view for In Prison Courses & Qualifications
The route is sat behind the feature toggle; and the view is basic and pretty much empty.
But this allows us to complete the work preceding this page, and to be able to link to this page. The rest of RR-673 will start to flesh out the rest of the functionality of this page.
@chrimesdev The URL that this route sets up is `/plan/{{ prison number }}/in-prison-courses-and-qualifications` - this is what you will want to link to on the "View all" link in your current story 👍
=> RR-673 - Initial skeleton route, controller and view for In Prison Courses & Qualifications

integration_tests/e2e/goal/addNote.cy.ts, integration_tests/e2e/goal/addStep.cy.ts, integration_tests/e2e/goal/createGoal.cy.ts, integration_tests/e2e/goal/review.cy.ts, integration_tests/e2e/goal/reviewUpdateGoal.cy.ts, integration_tests/e2e/overview/postInductionOverview.cy.ts, integration_tests/e2e/postInductionCreation/postInductionCreation.cy.ts, integration_tests/pages/goal/AddNotePage.ts, integration_tests/pages/goal/AddStepPage.ts, integration_tests/pages/goal/CreateGoalPage.ts, integration_tests/pages/goal/ReviewPage.ts, integration_tests/pages/goal/ReviewUpdateGoalPage.ts, integration_tests/pages/goal/UpdateGoalPage.ts, server/views/pages/goal/add-note/index.njk, server/views/pages/goal/add-step/index.njk, server/views/pages/goal/create/index.njk, server/views/pages/goal/review/index.njk, server/views/pages/goal/update/index.njk, server/views/pages/goal/update/review.njk
This PR removes the Prisoner Summary bar from the PLP Goals screens (they now look like the Induction screens)
Most of the change was actually in the cypress integration tests. The tests for the various Goal related pages and flows used to have a method `isForPrisoner` which made an assertion that the prison number in the Prisoner Summary bar was the same one that we were working on.
This clearly no longer works, and looking at the tests in question, for the most part was a little bit redundant. So I removed it all 😁
=> RR-690 - Remove prisoner summary bar from Goals screens

assets/scss/local.scss, server/utils/nunjucksSetup.ts, server/views/pages/goal/review/index.njk, server/views/pages/goal/update/review.njk, server/views/pages/overview/partials/overviewTab/_goalsList.njk
This PR replaces the use of the `formatMultilineText` and `safe` filters with a pure css solution.
The problem with using `formatMultilineText` is that it replaces `\n` with `<br />`. Because the text now contains html that needs to be rendered we needed to use the `safe` filter. And because we are using the `safe` filter on user entered text (eg: Goal title), it means that any html that the user has entered into the field is rendered as markup, rather than being escaped. This is essentially a XSS vulnerability.
Because of how the styles are inherited and cascaded through the elements, I've had to replace a couple of GDS components with their handwritten html equivalent so that I could apply the style on the correct element. (Otherwise it was being applied to a parent/grandparent element, …
=> RR-706 - Replaced multiline text filter with css

integration_tests/e2e/induction/updateInPrisonWorkInterests.cy.ts, integration_tests/e2e/overview/educationAndTrainingTab.cy.ts, integration_tests/e2e/overview/workAndInterestsTab.cy.ts, integration_tests/pages/overview/EducationAndTrainingPage.ts, integration_tests/pages/overview/WorkAndInterestsPage.ts, server/config.ts, server/routes/induction/update/inPrisonWorkUpdateController.test.ts, server/routes/induction/update/inPrisonWorkUpdateController.ts, server/routes/induction/update/index.ts, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
I appear to have had some initial confusion between in-prison `work` and in-prison `training and education` early on when I picked up RR-647 (which was meant to focus on the latter!). My bad. This PR fixes the links and routes to in-prison work (which should have been done under RR-704 and RR-705).
=> RR-704 - Fixes to in-prison work route and links

server/@types/forms/index.d.ts, server/routes/induction/common/highestLevelOfEducationController.ts, server/routes/induction/common/highestLevelOfEducationView.ts, server/routes/induction/update/highestLevelOfEducationFormValidator.test.ts, server/routes/induction/update/highestLevelOfEducationFormValidator.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.ts
This PR adds the validator and controller for updating Highest Level of Education.
There is one scenario, marked with a todo and an "unsupported operation" exception that has not been implemented yet. That is the scenario that starts a mini-flow to take the user through asking about previous qualifications. Those screens have not yet been implemented, so this scenario will be implemented at a later time.
=> RR-694 - Highest Level of Education validator & controller

integration_tests/e2e/induction/updateEducationalQualifications.cy.ts, integration_tests/e2e/overview/educationAndTrainingTab.cy.ts, integration_tests/pages/induction/QualificationsListPage.ts, integration_tests/pages/overview/EducationAndTrainingPage.ts, server/routes/induction/update/index.ts, server/routes/induction/update/qualificationsListUpdateController.test.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/views/pages/induction/prePrisonEducation/qualificationsList.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk
This PR adds the submit handling for the Previous Qualifications page.
There are 4 possible submission scenarios / routings, and this PR adds the skeleton code to support them, but only fully implements one.
The 4 possible scenarios are:
* Page is submitted by pressing a remove qualification link
* Page is submitted by pressing the Add qualification button
* Page is submitted by pressing the main Continue button, but where there are no qualifications recorded
* Page is submitted by pressing the main Continue button, but where there is at least 1 qualification recorded
This PR implements the last scenario - "Page is submitted by pressing the main Continue button, but where there is at least 1 qualification recorded". This scenario is basically the user saying they have completed their …
=> RR-694 - Form submission for the main Submit button on the Previous Qualifications induction page

server/views/pages/inPrisonCoursesAndQualifications/index.njk, server/views/pages/inPrisonCoursesAndQualifications/macros/sortableTable.njk
Boilerplate nunjucks template for the In progress courses and qualifications tab, ready for data when we have it.
Plus additional logic in the macro to handle optional columns from the design, I think once we have data, we may be able to come up with a better approach for this. Tried to keep the Nunjucks template clean as possible whilst moving the logic into the macro - open to thoughts on this!
https://dsdmoj.atlassian.net/browse/RR-674
=> RR-674 template for in progress courses with new column logic

integration_tests/e2e/induction/updateEducationalQualifications.cy.ts, integration_tests/pages/induction/QualificationsListPage.ts, server/routes/induction/common/qualificationsListController.ts
This PR fixes the error handling for when Curious is down/unavailable when displaying the Qualifications List page
=> RR-694 - Fixed error handling for Curious API call on Qualifications List page

server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/induction/common/qualificationDetailsController.ts, server/routes/induction/common/qualificationDetailsView.ts, server/routes/induction/update/index.ts, server/routes/induction/update/qualificationDetailsFormValidator.test.ts, server/routes/induction/update/qualificationDetailsFormValidator.ts, server/routes/induction/update/qualificationDetailsUpdateController.test.ts, server/routes/induction/update/qualificationDetailsUpdateController.ts, server/routes/induction/update/qualificationLevelFormValidator.ts, server/routes/induction/update/qualificationLevelUpdateController.test.ts, server/routes/induction/update/qualificationLevelUpdateController.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/views/pages/induction/prePrisonEducation/qualificationDetails.njk
This PR finishes off the submit functionality for the "Qualification Level" page and then adds the view template and functionality for the "Qualification Details" page. I'll add cypress tests in a subsequent PR.
These two pages are part of a simple flow, which ends up updating the Induction in the session with a newly added qualification. However, the API it not called to persist the updated Induction until the user clicks on the "Continue" button on the main Qualifications page.
=> RR-723 - Qualification details page functionality

integration_tests/e2e/induction/updateAdditionalTraining.cy.ts, integration_tests/e2e/induction/updateAffectAbilityToWork.cy.ts, integration_tests/e2e/induction/updateWorkedBefore.cy.ts, integration_tests/pages/induction/AdditionalTrainingPage.ts, integration_tests/pages/induction/AffectAbilityToWorkPage.ts, integration_tests/pages/induction/FutureWorkInterestRolesPage.ts, integration_tests/pages/induction/FutureWorkInterestTypesPage.ts, integration_tests/pages/induction/HighestLevelOfEducationPage.ts, integration_tests/pages/induction/InPrisonTrainingPage.ts, integration_tests/pages/induction/InPrisonWorkPage.ts, integration_tests/pages/induction/InductionPage.ts, integration_tests/pages/induction/PersonalInterestsPage.ts, integration_tests/pages/induction/PreviousWorkExperienceDetailPage.ts, integration_tests/pages/induction/PreviousWorkExperienceTypesPage.ts, integration_tests/pages/induction/QualificationsListPage.ts, integration_tests/pages/induction/ReasonsNotToGetWorkPage.ts, integration_tests/pages/induction/SkillsPage.ts, integration_tests/pages/induction/WorkedBeforePage.ts, integration_tests/pages/page.ts
This PR adds support for testing back links in our cypress tests
I've created an `InductionPage` superclass that all of the Induction based pages now extend; and in `InductionPage` I've added some basic functions for testing and asserting the back links
And I've added a couple of calls to the assertion methods in some of the tests as examples.
The work we are doing in RR-731 (@chrimesdev) and RR-732 (when we get to it) will make use of this 👍
=> RR-731 - Support for back links in cypress tests

integration_tests/e2e/induction/updateHopingToWorkOnRelease.cy.ts, server/routes/induction/update/hopingToWorkOnReleaseFormValidator.test.ts, server/routes/induction/update/hopingToWorkOnReleaseFormValidator.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts, server/routes/induction/update/index.ts
This PR creates the basic submit handler (POST) for the Hoping To Work On Release update controller.
It caters for the easy path, in that it caters for when the form is submitted with values that do not require a new flow / question set.
In this case we can simply update the Induction and return the user to the Work & Interests page.
The more complex scenario, where the answer is changed such that the Induction is now invalid and requires a new flow / question set, will be addressed in subsequent PRs.
=> RR-736 - Basic controller submit (POST) handler

integration_tests/e2e/induction/updateEducationalQualificationsAddQualification.cy.ts, integration_tests/pages/induction/QualificationDetailsPage.ts, integration_tests/pages/induction/QualificationLevelPage.ts, server/routes/induction/common/qualificationDetailsController.ts, server/routes/induction/common/qualificationLevelController.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.ts, server/routes/induction/update/qualificationDetailsUpdateController.test.ts, server/routes/induction/update/qualificationDetailsUpdateController.ts, server/routes/induction/update/qualificationLevelUpdateController.test.ts, server/routes/induction/update/qualificationLevelUpdateController.ts, server/routes/induction/update/qualificationsListUpdateController.test.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/routes/pageFlowQueue.test.ts, server/routes/pageFlowQueue.ts
This PR implements the `getBackLinkUrl()` methods for the add qualification related pages (i.e. "Qualification Level" and "Qualification Details").
Since these pages are part of a mini flow, I'm reusing the excellent `PageFlowQueue` that @nathanrussell-moj-digital added in a previous PR for the previous work experience functionality. It took me a while to grasp that the key thing here is to add the current and previous page when first building the `PageFlowQueue`. However, rather than defining the complete set of pages initially, I'm adding the "Qualification Detail" page to the array of pages when the user goes to that page, as I think this makes the flow simpler and potentially more dynamic for other flows in the future.
I aim to implement the `getBackLinkAriaText()` functionality in my …
=> RR-732 - Dynamic back links for add qualification screens

helm_deploy/values-dev.yaml
Temporarily set modsec anomaly score for rule 921110 to 5 in dev to test request blocking logic
=> Temporarily set anomaly score for rule 921110 to 5 in dev

integration_tests/pages/induction/WantToAddQualificationsPage.ts, server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts, server/views/pages/induction/prePrisonEducation/wantToAddQualifications.njk
This PR migrates the nunjucks template for "Do you want to add qualifications", along with a basic form definition for it.
We've not needed this screen so far as it's not asked/accessed directly via a Change link; but now we are looking at the "Do you want to work on release" which will change the flow, the question will be asked when you change to a "short question set"
We'll also need this screen when we do the Create journey
=> RR-736 - Migrated CIAG UI view for "Do you want to add qualifications"

server/routes/inPrisonCoursesAndQualifications/index.ts, server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/routerRequestHandlers.test.ts, server/routes/routerRequestHandlers.ts
This PR changes the way we retrieve the Curious In Prison Courses; from being a responsibility of the controller method, to being a router request handler that puts the result in [`res.locals`](https://expressjs.com/en/api.html#res.locals)
This is a better pattern, especially for data like this where we simply want to pass it to the view. It means the controller is not responsible for this and can just assume the data is already there on `res.locals`. Some of our controllers and associated unit tests are getting a little "fat" in this respect, so this is a good thing.
For the time being I'm only doing this for retrieving the Curious In Prison Course data, but there are other similar service requests that we currently make in the controller that we could refactor in a similar manner. I'll …
=> RR-590 - Retrieve curious In Prison Courses via router request handler

integration_tests/e2e/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualifications.cy.ts, integration_tests/pages/functionalSkills/FunctionalSkillsPage.ts, integration_tests/pages/inPrisonCoursesAndQualifications/InPrisonCoursesAndQualificationsPage.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.test.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsView.ts, server/routes/inPrisonCoursesAndQualifications/index.ts, server/services/curiousService.ts, server/views/pages/inPrisonCoursesAndQualifications/index.njk, server/views/pages/inPrisonCoursesAndQualifications/macros/sortableTable.njk
This PR populates the "Completed courses" tab on the new In Prison Courses & Qualifications page
(note the tab heading applies the correct plural to the word "course")
=> RR-673 - Populated "Completed Courses" tab

server/routes/induction/common/qualificationsListController.ts, server/routes/induction/common/wantToAddQualificationsController.ts, server/routes/induction/common/wantToAddQualificationsView.ts, server/routes/induction/update/index.ts, server/routes/induction/update/wantToAddQualificationsFormValidator.test.ts, server/routes/induction/update/wantToAddQualificationsFormValidator.ts, server/routes/induction/update/wantToAddQualificationsUpdateController.test.ts, server/routes/induction/update/wantToAddQualificationsUpdateController.ts
A previous PR had added the nunjucks template for the `Want to Add Qualifications` page, but we didn't have the corresponding controllers & route. 
Note that the submit currently doesn't work without a `pageFlowQueue`, since it will only ever be called when switching from the long question set to the short one (i.e. when it is part of this main flow).
=> RR-738 - Controllers and route for Want to Add Qualifications page

package-lock.json, package.json, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/createGoal/index.ts, server/routes/futureGoalTargetDateCalculator.test.ts, server/routes/futureGoalTargetDateCalculator.ts
This PR continues the work that Adam started re: the new create goals journey. Specifically it:
* Corrects the route for the new form / controller endpoints.
Adam had assumed the route would be the same as the existing journey, where the goal number and step number are path elements. This is not true as it's now a single page journey where each new goal and step are added to the same page (it will still be a full page request/response model; it's not being done with client side javascript / SPA). The correct route is `/plan/:prisonNumber/goals/create`
* Adds a unit test class for the controller that Adam started
Unit tests for the GET handler method, and form validation on the POST submit handler method.
Further tests will be added as we write more functionality into the controller.
* …
=> RR-748 - Fix routes and basic controller with tests

assets/scss/local.scss, server/routes/induction/common/checkYourAnswersController.ts, server/routes/induction/common/checkYourAnswersView.ts, server/routes/induction/update/checkYourAnswersUpdateController.ts, server/views/pages/induction/checkYourAnswers/index.njk, server/views/pages/induction/checkYourAnswers/partials/_educationAndTrainingLite.njk, server/views/pages/induction/checkYourAnswers/partials/_inPrisonInterests.njk, server/views/pages/induction/checkYourAnswers/partials/_workOnRelease.njk
This PR carries on with the work that Matt was working on to do with porting the Induction screens from the CIAG UI.
Specifically this addresses something he did not have time to complete last week re: populating the values on the Check Your Answers page. Matt had previously ported the nunjucks template from the CIAG UI, and written the controller etc, but had not got round to ensuring the values were populated.
This PR addresses that **but for the short question set journey only** as this was the area that Matt was working on. Managing and populating the long question set will come in subsequent PRs.
=> RR-736 - Populate Check Your Answers page with values

server/routes/functionalSkills/functionalSkillsController.test.ts, server/routes/functionalSkills/functionalSkillsController.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/services/curiousService.test.ts, server/services/curiousService.ts, server/services/prisonService.test.ts, server/services/prisonService.ts, server/services/timelineService.test.ts, server/services/timelineService.ts
This PR improves the existing `prisonService`
The reason I'm doing this improvement is because we need the same `prisonService` in DPS Prisoner Profile for the work we are doing there, and I went to simply copy and paste it.
However, on doing so I identified some areas where it was not clear what the class and it's functions were doing. Namely:
* the `getPrisonByPrisonId` and `lookupPrison` methods were essentially doing the same thing; but it was not clear which should be used (not clear why you would use one function over the other)
* lack of class/function doc that would have helped explain
The refactoring here basically:
* keeps `lookupPrison` as that was the method that all dependent code used (but renames it)
* moves the code in `getPrisonByPrisonId` into `lookupPrison` …
=> RR-650 - Improve prisonService

integration_tests/e2e/goal/createGoals.cy.ts, integration_tests/pages/goal/CreateGoalsPage.ts, server/data/mappers/createGoalDtoMapper.test.ts, server/data/mappers/createGoalDtoMapper.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/createGoal/index.ts
This PR completes the story that Adam started by implementing the submit handler for the new Create Goals journey
The submit hander takes the `CreateGoalsForm` (the validation has already been done, in a previous PR), maps it into the `CreateGoalDto` array, and passes the array into the existing service.
The new code in this PR is the final part of the controller method, and a new mapper class (and the relevant unit and cypress tests)
=> RR-734 - createGoalsController submit form handler

helm_deploy/values-dev.yaml, integration_tests/e2e/goal/createGoals.cy.ts, integration_tests/pages/goal/CreateGoalsPage.ts, integration_tests/pages/overview/OverviewPage.ts, integration_tests/pages/page.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/overview/postInductionOverviewView.ts, server/routes/overview/preInductionOverviewView.ts, server/views/pages/overview/index.njk, server/views/partials/layout.njk
This PR adds the success notification banner when a new goal(s) has been created:
It also corrects something in my previous PR re: adding steps, in that the new empty step title field must be focussed when it is added.
=> RR-742 - Add 'Goals created successfully' message

integration_tests/e2e/goal/createGoals.cy.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/futureGoalTargetDateCalculator.test.ts, server/routes/futureGoalTargetDateCalculator.ts, server/validators/goalTargetCompletionDateValidator.test.ts, server/validators/goalTargetCompletionDateValidator.ts, server/validators/goalTitleValidator.test.ts, server/validators/goalTitleValidator.ts, server/validators/stepTitleValidator.test.ts, server/validators/stepTitleValidator.ts, server/views/pages/createGoals/index.njk
This PR corrects the validation messages in the new Create Goal journey (I'd not seen that they'd changed the validation messages in the screenshots in the Jira ticket! 🙄 )
As well as correcting the messages, it also fixes a problem where validation was happening too early and that you could not add a new step or goal until the entire form was valid. You can now add (and remove) goals and steps with the form in any state, and it is only when you submit the form with the main CTA that the form is validated.
I also took the opportunity to remove `moment` and replace it with `date-fns` functions in one of the validators
=> RR-734 - Corrected validation messages

server/data/hmppsAuditClient.test.ts, server/data/hmppsAuditClient.ts
Audit SQS messages are being published, but not being received by the audit service. We think this could be because the details object isn't stringified.
If this is the reason an update will be needed to the template.
=> Stringify audit details

server/routes/induction/common/checkYourAnswersController.ts, server/routes/induction/update/additionalTrainingUpdateController.test.ts, server/routes/induction/update/additionalTrainingUpdateController.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts, server/routes/induction/update/personalInterestsUpdateController.test.ts, server/routes/induction/update/personalInterestsUpdateController.ts, server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts, server/routes/induction/update/qualificationsListUpdateController.test.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/routes/induction/update/skillsUpdateController.test.ts, server/routes/induction/update/skillsUpdateController.ts, server/routes/induction/update/workInterestRolesUpdateController.test.ts, server/routes/induction/update/workInterestRolesUpdateController.ts, server/routes/induction/update/workInterestTypesUpdateController.test.ts, server/routes/induction/update/workInterestTypesUpdateController.ts, server/routes/induction/update/workedBeforeUpdateController.test.ts, server/routes/induction/update/workedBeforeUpdateController.ts, server/routes/pageFlowHistory.test.ts, server/routes/pageFlowHistory.ts
This PR does some refactoring of how we build the page flow history object for pages in the Induction flow.
Previously each controller had their own version of the method, which basically just build/initialised a new history object containing the current page path. I needed to add this same functionality to the Check Your Answers page (as a enabler for supporting the Change links), so rather than add yet another very similar copy of the method, I refactored it out into a common location.
This PR looks quite big, but its basically the same change in each controller and test
=> RR-736 - Refactor page flow history

integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts, integration_tests/index.d.ts, integration_tests/pages/induction/CheckYourAnswersPage.ts, integration_tests/support/commands.ts, server/routes/induction/common/hopingToWorkOnReleaseController.ts, server/routes/induction/common/inductionController.ts, server/routes/induction/dynamicAriaTextResolver.ts, server/routes/induction/update/additionalTrainingUpdateController.test.ts, server/routes/induction/update/additionalTrainingUpdateController.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts, server/routes/induction/update/inPrisonWorkUpdateController.test.ts, server/routes/induction/update/inPrisonWorkUpdateController.ts, server/routes/induction/update/reasonsNotToGetWorkUpdateController.test.ts, server/routes/induction/update/reasonsNotToGetWorkUpdateController.ts, server/views/pages/induction/checkYourAnswers/partials/_educationAndTraining.njk, server/views/pages/induction/checkYourAnswers/partials/_educationAndTrainingLite.njk, server/views/pages/induction/checkYourAnswers/partials/_inPrisonInterests.njk, server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk, server/views/pages/induction/checkYourAnswers/partials/_workOnRelease.njk
This PR implements the code and cypress tests for (most of) the Short Question Set Induction questions.
The ones not currently implemented are the 2 to do with Education as they can be a little complicated, but I'll tackle those next.
I've also left a skeleton Cypress test for the Change links for the Long Question Set Induction, so that we can work on both Short and Long question set change links independently.
The Check Your Answers page for the Short Question Set Induction is as per the following screenshot; and I have done all of the Change links except the 2 highlighted education questions:
=> RR-736 - Cypress tests for Change links for most of the Short Question Set Induction questions

integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts, integration_tests/pages/induction/CheckYourAnswersPage.ts, server/routes/induction/common/inductionController.ts, server/routes/induction/common/qualificationsListController.ts, server/routes/induction/common/wantToAddQualificationsController.ts, server/routes/induction/update/qualificationDetailsUpdateController.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/routes/induction/update/wantToAddQualificationsUpdateController.test.ts, server/routes/induction/update/wantToAddQualificationsUpdateController.ts, server/routes/pageFlowHistory.test.ts, server/routes/pageFlowHistory.ts
This PR is for the Change link handling and cypress test for the educational qualifications question "Do they want to record any qualifications"
This is Change link 3 of 3 for the education questions.
There is some minor complexity in this one:
* "Do they want to record any qualifications" is only asked on the Short Question Set (I have never understood why!)
* The answer to the question is not actually saved as part of the Induction (it never was from the original CIAG UI and API that we inherited)
Therefore on the Check Your Answers page we infer the answer by looking at the qualifications - if there are qualifications then the answer is inferred as Yes (as in Yes they wanted to add qualifications). Otherwise it is inferred as No
* On the Check Your Answers page, if you change "Do they …
=> RR-736 - Change links for Do You Want To Add Qualifications

integration_tests/e2e/induction/createLongQuestionSetInduction.cy.ts, server/routes/induction/common/additionalTrainingController.ts, server/routes/induction/common/workInterestTypesController.ts, server/routes/induction/common/workedBeforeController.ts, server/routes/induction/create/additionalTrainingCreateController.test.ts, server/routes/induction/create/additionalTrainingCreateController.ts, server/routes/induction/create/hopingToWorkOnReleaseCreateController.ts, server/routes/induction/create/previousWorkExperienceDetailCreateController.test.ts, server/routes/induction/create/previousWorkExperienceDetailCreateController.ts, server/routes/induction/create/previousWorkExperienceTypesCreateController.test.ts, server/routes/induction/create/previousWorkExperienceTypesCreateController.ts, server/routes/induction/create/qualificationsListCreateController.test.ts, server/routes/induction/create/qualificationsListCreateController.ts, server/routes/induction/create/workInterestTypesCreateController.test.ts, server/routes/induction/create/workInterestTypesCreateController.ts, server/routes/induction/create/workedBeforeCreateController.test.ts, server/routes/induction/create/workedBeforeCreateController.ts
This PR simplifies the use of (and the need for) the page flow history on the create journey (though some of this will be re-introduced when we do the Change links from Check Your Answers)
The Page Flow History is used to track the history of pages a user has been through in order to display the correct Back link
At the moment, without the complication of Check Your Answers, we have a fairly linear page flow:
For the most part we know what the previous page was, even with the complexity of the branching for the short vs. long journey.
EG: If you are on the Qualifications List page (the 2nd page of the long question set), we know the previous page in the flow would be Do You Want To Work On Release. We can hard-code that, and don't need anything complicated to track the state (until we get …
=> RR-775 - Simplified the use of (and the need for) the page flow history on the create journey

server/views/pages/induction/checkYourAnswers/index.njk, server/views/pages/induction/checkYourAnswers/partials/_abilityToWork.njk, server/views/pages/induction/checkYourAnswers/partials/_educationAndTraining.njk, server/views/pages/induction/checkYourAnswers/partials/_educationAndTrainingLite.njk, server/views/pages/induction/checkYourAnswers/partials/_inPrisonInterests.njk, server/views/pages/induction/checkYourAnswers/partials/_skillsAndInterests.njk, server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk, server/views/pages/induction/checkYourAnswers/partials/_workOnRelease.njk
This PR is the first step in getting the Change links working on the Check Your Answers page for the Create journey.
The Check Your Answers page template is used for both Update and Create, and currently the Change link urls have the full path for the Update journey in them.
Rather than add some convoluted logic etc for the template to know what journey it's being used for, I've changed the links to use relative urls.
There is already a cypress test that exercises all of the Change links for the Update journey. This test still passes, which proves this change is OK 👍
=> RR-775 - Use relative URLs for Change links on Check Your Answers

integration_tests/mockApis/auth.ts, integration_tests/mockApis/manageUsersApi.ts, integration_tests/mockData/prisonerSearchSummaryMockDataGenerator.ts, server/@types/viewModels/index.d.ts, server/data/manageUsersApiClient.test.ts, server/data/manageUsersApiClient.ts, server/data/mappers/prisonerSummaryMapper.test.ts, server/data/mappers/prisonerSummaryMapper.ts, server/middleware/checkPrisonerInCaseloadMiddleware.test.ts, server/middleware/checkPrisonerInCaseloadMiddleware.ts, server/middleware/populateCurrentUser.ts, server/middleware/roleBasedAccessControl.ts, server/middleware/setUpCurrentUser.ts, server/services/userService.test.ts, server/services/userService.ts, server/testsupport/prisonerSearchSummaryTestDataBuilder.ts, server/testsupport/prisonerSummaryTestDataBuilder.ts, server/testsupport/prisonerTestDataBuilder.ts, server/utils/userCaseLoads.test.ts, server/utils/userCaseLoads.ts, server/utils/userRoles.test.ts, server/utils/userRoles.ts
This PR implements the middleware to:
1. retrieve the user's caseloads from the manage users API
2. check the user is authorised to view the prisoner based on caseload and other role memberships
The first middleware (retrieve the user's caseloads) is wired in and will be called for each user request once this PR is merged.
The 2nd middleware (check the user is authorised to view the prisoner) is not wired into any routes yet
The code in this PR is based very heavily on the code in [HMPPS Prisoner Profile](https://github.com/ministryofjustice/hmpps-prisoner-profile/blob/main/server/middleware/checkPrisonerInCaseloadMiddleware.ts), though a few differences were made based on the fact that our object models and approach to utility functions is slightly different. Having said this, …
=> RR-784 - Middleware to check prisoner is in users caseload

integration_tests/e2e/induction/createChangeInductionQuestionSet.cy.ts, integration_tests/e2e/induction/createShortQuestionSetInduction.cy.ts, server/routes/induction/common/highestLevelOfEducationController.ts, server/routes/induction/create/highestLevelOfEducationCreateController.test.ts, server/routes/induction/create/wantToAddQualificationsCreateController.test.ts, server/routes/induction/create/wantToAddQualificationsCreateController.ts
This PR fixes a bug with the migrated Induction process, specifically for short question set inductions where the user says "no" to wanting to record educational qualifications.
Without this bug fix the data that is sent to the API to create the Induction is:
```
{
....
"prisonNumber": "G1608UL",
"workOnRelease": {
"hopingToWork": "NO",
"notHopingToWorkReasons": [
"NO_RIGHT_TO_WORK",
"OTHER"
],
....
},
....
"previousQualifications": null,
.... 
}
```
Notice how `previousQualifications` is `null`. Whilst the induction is saved OK by the API, when it is later retrieved for display by the UI there is effectively a NPE because `previousQualifications` is `null`.
Based on what the CIAG UI does in this scenario (short question set, No to do you want to record qualifications), we need the …
=> RR-785 - Fix null qualifications when creating Inductions with no qualifications

integration_tests/e2e/induction/createChangeInductionQuestionSet.cy.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts, server/routes/induction/update/highestLevelOfEducationUpdateController.ts
This PR fixes a problem when updating a short question set Induction with no qualifications to a long question set Induction.
The bug was that when you changed it do long question set, you are asked about qualifications and the prisoner's Highest Level Of Education. If you selected a highest level of education that did not require exams, then the Induction was saved too early (and in a partial state).
From the jira ticket:
* Create a Short question set induction with no qualifications and save it. 
* On the Work & Interests tab, click the Change link for “Do you want to work on release”.
* Change the answer from No (or Not Sure) to Yes, meaning it now becomes a Long question set induction
* At the screen that asks Highest Level of Education, choose any that do not require qualifications …
=> RR-786 - Fix short to long journey

assets/scss/components/_summary-card.scss, assets/scss/print.scss, server/views/pages/overview/partials/overviewTab/qualificationsAndAchievementsSidebar.njk
Small PR to update the colour (from green to standard text colour) and some text, on the Overview screen:
=> RR-777 - Updated text & colour on Overview screen

server/@types/forms/index.d.ts, server/data/mappers/createGoalDtoMapper.test.ts, server/data/mappers/createGoalDtoMapper.ts, server/enums/goalTargetCompletionDateOption.ts, server/routes/createGoal/createGoalFormValidator.test.ts, server/routes/createGoal/createGoalFormValidator.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/createGoal/createGoalsFormValidator.test.ts, server/routes/createGoal/createGoalsFormValidator.ts, server/routes/createGoal/createGoalsView.ts, server/routes/updateGoal/updateGoalFormValidator.test.ts, server/routes/updateGoal/updateGoalFormValidator.ts, server/utils/nunjucksSetup.ts, server/validators/goalTargetCompletionDateValidator.test.ts, server/validators/goalTargetCompletionDateValidator.ts, server/views/pages/createGoals/index.njk
This PR implements an approach in [this POC](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/599) re: using an enum for the goal target completion date, rather than having the controller work out the dates to pass to the view.
The basic idea is that we have an enum that describes the target date completion options (3 months, 6 months, 12 months and another/manually entered date). The enum value set is passed to the view for use with the radio buttons, and the view is responsible for working out the dates to use as labels for the radios (because that is very much a presentation concern 👍 )
On form submission the controller uses a mapper to map for the submitted form into a DTO, and it is the job of that mapper to work out what 3/6/12 months from today is 👍 …
=> RR-789 - Refactored CreateGoalsForm to use enum for goal target completion date

integration_tests/mockApis/curiousApi.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, integration_tests/mockApis/prisonerListApi.ts, integration_tests/mockData/prisonerSearchSummaryMockDataGenerator.ts
This PR replaces all uses of moment.js with corresponding date-fns function calls in our cypress integration tests.
There is still work to do re: replacing moment with date-fns; but its all in the main code now. All date related stuff in the integration tests is now using date-fns 👍
=> RR-491 - Replace all uses of moment.js with date-fns in cypress tests

server/data/mappers/createGoalMapper.test.ts, server/data/mappers/createGoalMapper.ts
This PR fixes a date formatting issue that I inadvertently introduced in my last PR re: changing the `targetCompletionDate` field to use an enum
Basically I introduced a problem with any target completion date that would be in BST (and the current date is not in BST) - in this scenario the target completion date ended up being 1 day less (I hate dates and timezones! 🤣 )
Anyway, the problem was in the mapper that maps the CreateGoals form into the DTO that is sent to the API, in that it takes the targetCompletionDate (which is a `Date` instance) and formats it into a string.
The fix is to use `date-fns` to format the date; and the new unit test is there to prove 👍
=> RR-789 - Fix date formatting for BST dates

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/pages/induction/CheckYourAnswersPage.ts, server/routes/induction/common/wantToAddQualificationsController.ts, server/routes/induction/create/wantToAddQualificationsCreateController.test.ts, server/routes/induction/create/wantToAddQualificationsCreateController.ts, server/routes/induction/update/wantToAddQualificationsUpdateController.ts
This PR fixes a bug that Karen found with the Induction journey.
This PR fixes the bug and implements the Expected Behaviour
From the Jira ticket:
* Create a new Induction
* On the first question (do they want to work on release) choose No or Not Sure to make it a Short question set Induction
* When asked whether they want to add any qualifications choose Yes
* Enter at least 1 qualification
* Complete the rest of the Induction, no special or significant answers need to be provided. Answer as you feel fit
* Arrive on Check Your Answers
* Observe that the answer to “do they want to record any qualifications” is Yes and that the qualifications previously entered are correctly displayed
* Click the change link for “do they want to record any qualifications”
* On the “do they want to record …
=> RR-801 - Fix routing when changing "Do they want to record qualifications" from Check Your Answers

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/pages/induction/PreviousWorkExperienceDetailPage.ts, server/routes/induction/create/previousWorkExperienceTypesCreateController.test.ts, server/routes/induction/create/previousWorkExperienceTypesCreateController.ts
This PR fixes a bug when clicking Back from a "previous work experience detail" page in the Create induction journey
From the jira ticket:
* Create a new Induction
* Answer “do they want to work on release” as Yes to make it a Long question set Induction
* When asked if the prisoner has worked before, answer Yes
* On the “previous work experience types” screen select one or more work types. Submit the page
* One the next screen (the work detail page for a work type) click the application Back button
* Observe that the “previous work experience types” screen is redisplayed with the previously made selections retained
* Do not change the work experience types, and simply click “Continue”
* The work detail page should be displayed
* A “page not found” error page is displayed
=> RR-805 - Fix routing when clicking back from previous work experience detail page

server/routes/induction/common/workedBeforeController.ts
This PR fixes a bug when clicking Back from the "previous work experience types" page in the Create induction journey
From the jira ticket:
* Create a new Induction
* Answer “do they want to work on release” as Yes to make it a Long question set Induction
* When asked if the prisoner has worked before, answer Yes
* On the “previous work experience types” screen click the application Back button
* The “have they worked before” page should be displayed
* The “additional training” page is displayed
=> RR-807 - Fix Back link on Previous Work Experiences Type page

assets/js/applicationinsights.js, server/views/pages/functionalSkills/index.njk, server/views/pages/inPrisonCoursesAndQualifications/dpsTemplate.njk, server/views/pages/inPrisonCoursesAndQualifications/plpTemplate.njk, server/views/pages/overview/partials/timelineTab/timelineTabContents.njk, server/views/pages/prisonerList/partials/searchTable.njk, server/views/partials/breadcrumb.njk, server/views/partials/prisonerBanner.njk
This PR overrides default event names which previously contained personal info with `data-id` values.
It also sets a safe default for all clicks originating from outside of our service content.
=> RR-806: Use data ids for unsafe link events names

integration_tests/mockData/timelineData.ts, server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/viewModels/index.d.ts, server/data/mappers/timelineMapper.test.ts, server/filters/formatPrisonMovementEventFilter.test.ts, server/filters/formatPrisonMovementEventFilter.ts, server/routes/timelineResolver.test.ts, server/routes/timelineResolver.ts, server/services/timelineService.test.ts, server/services/timelineService.ts, server/testsupport/timelineEventTestDataBuilder.ts, server/testsupport/timelineResponseTestDataBuilder.ts, server/testsupport/timelineTestDataBuilder.ts
This PR is the UI counterpart to this [API PR](https://github.com/ministryofjustice/hmpps-education-and-work-plan-api/pull/287)
It re-imports the swagger spec to get the latest spec/types; then refactors all the uses of `contextualInfo` as it is now a map rather than a simple string
=> RR-831 - Refactor Timeline Event contextualInfo; now returned from the API as a map

server/views/pages/induction/prePrisonEducation/qualificationLevel.njk
This PR fixes a bug with the qualification options on the Qualification Level screen.
The problem was that the nunjucks view was copied from the CIAG UI, and the CIAG UI and API's approach to qualifications is that if you were not asked Highest Level of Education then the view property `educationLevel` was an empty string.
When we migrated this to our API and UI we decided that it would be better for this view property (and the value sent to the API) to be `NOT_SURE` if you were not asked the question.
=> RR-832 - Fix qualification level options

server/errorHandler.ts, server/middleware/auditMiddleware.ts
I introduced null error bug when adding audits event for the error page since this page can be reached when a user is not logged in.
This change is to add null checks to the user objects.
=> RR-833: Added null check to user object

server/routes/induction/create/reasonsNotToGetWorkCreateController.ts
This PR fixes a small bug that Aliki reported re: Back link navigation from the Reasons Not To Work screen back to Hoping To Work On Release.
From the jira ticket:
* Create a new Induction
* Answer “do they want to work on release” as No or Not Sure to make it a Short question set Induction
* Reasons Not To Work page is displayed
* Select an answer and submit the page to the first Qualification page
* Click the application Back link (not the browser back button)
* Reasons Not To Work page is displayed
* Click the application Back link again (not the browser back button)
* User is taken to the “Do they want to work on release” page
* The “Reasons Not To Work” page is re-displayed
=> RR-834 - Fixed Back navigation from Reasons Not To Get Work

server/routes/overview/educationAndTrainingController.test.ts, server/routes/overview/educationAndTrainingController.ts, server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/overview/supportNeedsController.test.ts, server/routes/overview/supportNeedsController.ts, server/routes/overview/timelineController.test.ts, server/routes/overview/timelineController.ts, server/routes/overview/workAndInterestsController.test.ts, server/routes/overview/workAndInterestsController.ts
This PR refactors the slightly fat controller `OverviewController` into separate controllers for each tab of the Overview page
This refactoring is an enabler for further change we need to make in respect of the controller methods for the "Work & Interests" and "Education & Training" tabs.
We need to make some changes for both of these tabs as part of the Question set changes we are making (data from the completed Induction (aka question set) is shown on these 2 tabs, and we need to make some changes to how it is displayed).
In order to make those changes I intend to remove the code within the controller method that gets the induction via the service class etc, and instead to do it via some middleware. 
The refactoring I am doing here will make the refactoring to use middleware easier 👍
=> RR-839 - Refactor overviewController into separate controllers

integration_tests/e2e/induction/createChangeInductionQuestionSet.cy.ts, integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/e2e/induction/createShortQuestionSetInduction.cy.ts, integration_tests/e2e/induction/updateInductionQuestionSet.cy.ts, integration_tests/e2e/induction/updatePersonalInterests.cy.ts, integration_tests/e2e/induction/updateSkills.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, integration_tests/pages/overview/WorkAndInterestsPage.ts, integration_tests/support/commands.ts, server/data/mappers/createOrUpdateInductionDtoMapper.ts, server/routes/induction/common/personalInterestsController.ts, server/routes/induction/common/skillsController.ts, server/routes/induction/create/additionalTrainingCreateController.test.ts, server/routes/induction/create/additionalTrainingCreateController.ts, server/routes/induction/create/personalInterestsCreateController.test.ts, server/routes/induction/create/personalInterestsCreateController.ts, server/routes/induction/update/additionalTrainingUpdateController.test.ts, server/routes/induction/update/additionalTrainingUpdateController.ts, server/routes/induction/update/personalInterestsUpdateController.test.ts, server/routes/induction/update/personalInterestsUpdateController.ts, server/testsupport/inductionDtoTestDataBuilder.ts, server/testsupport/inductionResponseTestDataBuilder.ts, server/testsupport/updateInductionDtoTestDataBuilder.ts, server/testsupport/updateInductionRequestTestDataBuilder.ts, server/views/pages/induction/checkYourAnswers/index.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
This PR is the 3rd of the Question Set changes. The target branch for this PR is our integration branch feature/RR-810-question-set-epic
---
This PR adds the "Personal Skills" and "Personal Interests" screens to the Short question set immediately after "Additional Training" and before "In Prison Work".
The new screen flow can be seen [in this miro frame](https://miro.com/app/board/uXjVKe-qkvg=/?moveToWidget=3458764591206842029&cot=14).
Whilst we are only adding 2 screens, this change impacts many controllers in the create and induction journeys as the controllers for the screens before and after need to change (to change the "next" page on the screen before, and change the back link on the screen after); plus other places in the journey where you can ultimately end up on these screens. …
=> RR-816 - Add Personal Skills and Interests to the short question set Induction flow

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, server/views/pages/induction/checkYourAnswers/index.njk
This PR is the 5th of the Question Set changes. The target branch for this PR is our integration branch feature/RR-810-question-set-epic
---
This PR adds the Personal Skills & Personal Interests rows to the Check Your Answers page in the case of a short question set
(I forgot to do this as part of my previous PR for RR-816 which added the  Personal Skills & Personal Interests screens to the short question set)
=> RR-816 - Add skills & interests to Check Your Answers page

server/routes/induction/common/qualificationLevelController.ts, server/routes/induction/common/qualificationLevelView.ts, server/routes/induction/create/qualificationLevelCreateController.test.ts, server/routes/induction/update/qualificationLevelUpdateController.test.ts, server/views/pages/induction/prePrisonEducation/qualificationLevel.njk
This PR is the 4th of the Question Set changes. The target branch for this PR is our integration branch feature/RR-810-question-set-epic
---
This is a much simpler change than the others in this epic.
Currently the Qualification Level screen offers choices based on the Highest Level of Education. 
This has now been removed, and all inductions regardless of highest level of education, are now presented with all Qualification Level options
=> RR-821 - Simplify education level options

integration_tests/e2e/induction/createChangeInductionQuestionSet.cy.ts, integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/e2e/induction/createShortQuestionSetInduction.cy.ts, integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts, integration_tests/e2e/induction/updateInductionQuestionSet.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, integration_tests/support/commands.ts, server/routes/induction/create/additionalTrainingCreateController.test.ts, server/routes/induction/create/additionalTrainingCreateController.ts, server/routes/induction/create/inPrisonWorkCreateController.test.ts, server/routes/induction/create/inPrisonWorkCreateController.ts, server/routes/induction/update/additionalTrainingUpdateController.test.ts, server/routes/induction/update/additionalTrainingUpdateController.ts, server/views/pages/induction/checkYourAnswers/index.njk
This PR is the 7th of the Question Set changes. The target branch for this PR is our integration branch feature/RR-810-question-set-epic
---
This PR adds the 'Previous Work Experience' screens to the short question set induction flow (RR-822)
The new screen flow can be seen [in this miro frame](https://miro.com/app/board/uXjVKe-qkvg=/?moveToWidget=3458764591590258704&cot=14).
Whilst we are only moving 3 screens, this change impacts many controllers in the create and induction journeys as the controllers for the screens before and after need to change (to change the "next" page on the screen before, and change the back link on the screen after); plus other places in the journey where you can ultimately end up on these screens.
And because we are changing these controllers, it means the …
=> RR-822 - Add Previous Work Experience to the short question set Induction flow

server/views/pages/overview/partials/educationAndTrainingTab/_inPrisonQualificationsCompletedInLast12Months.njk, server/views/pages/overview/partials/educationAndTrainingTab/_inPrisonQualificationsCompletedInLast12Months.test.ts
This PR fixes a bug with the new In Prison Courses & Qualifications table, where the course grade was incorrectly shown as `N/A`
=> RR-853 - Fixed bug with completed course grade

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/index.d.ts, integration_tests/support/commands.ts, server/routes/induction/common/hopingToWorkOnReleaseController.ts, server/routes/induction/create/hopingToWorkOnReleaseCreateController.test.ts, server/routes/induction/create/hopingToWorkOnReleaseCreateController.ts, server/routes/induction/create/workInterestRolesCreateController.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts
This PR addresses the routing as part of the Create journey where a user has gone all the way through to Check Your Answers and then clicks Change for "Hoping to work"
When they change this answer from Check Your Answers; if they have:
* changed their previous answer of Yes to No or Not Sure
* then we need to clear any previously entered work interests (because they now dont want to work), and take them back to Check Your Answera
* changed their previous answer of No or Not Sure to Yes
* then we need to take them through the Work Interest Roles and Work Interest Details screens so they can enter the details of the work they would like to do
* not changed their answer at all
* take them back to Check Your Answers without changing the induction at all
=> RR-854 - Correct routing from Hoping To Get Work as part of the Create journey

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/e2e/induction/updateHopingToWorkOnRelease.cy.ts, server/routes/induction/common/hopingToWorkOnReleaseController.ts, server/routes/induction/common/workInterestRolesController.ts, server/routes/induction/common/workInterestTypesController.ts, server/routes/induction/create/hopingToWorkOnReleaseCreateController.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts, server/routes/induction/update/workInterestTypesUpdateController.test.ts, server/routes/induction/update/workInterestTypesUpdateController.ts
This PR addresses the routing as part of the Update journey where a prisoner already has an Induction and the CIAG has clicked the Change link for "Hoping to work" on the Work & Interests tab.
When they update the induction by changing this answer; if they have:
* changed the previous answer of Yes to No or Not Sure
* then we need to clear any previously entered work interests (because they now don't want to work), call the API to save the Induction, and take them back to Work & Interests
* changed the previous answer of No or Not Sure to Yes
* then we need to take them through the Work Interest Roles and Work Interest Details screens so they can enter the details of the work they would like to do.
* We should not call the API to update the induction until we have successfully submitted …
=> RR-855 - Correct routing from Hoping To Get Work as part of the Update journey

README.md, helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, server/config.ts
This PR adds a new feature toggle `ARCHIVE_GOALS_ENABLED` to support our current work re: archiving goals (epic RR-824) to allow us to develop this feature without risking releasing early/half-baked code
=> RR-859 - Added `ARCHIVE_GOALS_ENABLED` feature toggle

server/@types/viewModels/index.d.ts, server/views/components/actions-card/_actions-card.scss, server/views/components/actions-card/actionsCard.test.ts, server/views/components/actions-card/macro.njk, server/views/components/actions-card/template.njk, server/views/components/actions-card/test.njk
Re-usable actions card nunjucks component and model. Not currently used but designed to be placed on the overview page with add goal and view archived goal actions.
=> RR-721: Actions card component

server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.test.ts
This PR fixes a bug where Personal Skills and Interests on the Work & Interests tab were always be displayed as "Not recorded." with an "Add" link
=> RR-861 - Fixed bug with personal skills and interests not displaying correctly

server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.test.ts
If the induction was performed on the old question set and they answered no to "hoping to work" then the last updated field was not displaying properly as future work interests are not entered. Change to use the last updated of hoping to work if future work interests are not present.
=> RR-863: Fix Work Interests last updated for old short question set

server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.test.ts
If the induction was performed on the old question set and they answered no to "hoping to work" then the last updated field was not displaying properly for work experience. Now defaults to has worked before last updated and you can also add the work experience if you so choose as you would be able to on a new induction.
=> RR-862: Fix Work has worked before for old short question set induction

integration_tests/e2e/overview/educationAndTrainingTab.cy.ts, integration_tests/pages/overview/EducationAndTrainingPage.ts, server/routes/induction/common/qualificationLevelController.ts, server/routes/induction/update/qualificationLevelUpdateController.ts, server/routes/induction/update/qualificationsListUpdateController.ts, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory.njk
This PR fixes a routing bug with the "Change" link for qualifications on existing inductions (any induction, whether that be new question set, short or long)
If the Induction has qualifications to start with, then clicking the Change link should take the user to the Qualifications List screen where they can add/remove qualifications
If the Induction has no qualifications to start with, then clicking the Change link should take the user to the Qualification Level screen where then can enter the first qualification
=> RR-864 - Fixed bug when updating qualifications where induction has no qualifications to start with

integration_tests/e2e/induction/updateWorkedBefore.cy.ts, server/routes/induction/update/workedBeforeUpdateController.test.ts, server/routes/induction/update/workedBeforeUpdateController.ts, server/testsupport/inductionDtoTestDataBuilder.ts
If selecting yes when answering "has worked before" then we should proceed through work experience types and details screens and update them all together.
=> RR-866: Changing "has worked before" to yes should ask for work experience

README.md, feature.env, helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts, server/routes/induction/create/index.ts, server/routes/induction/update/index.ts, server/utils/nunjucksSetup.ts, server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/educationAndTrainingTab/educationAndTrainingTabContents.njk, server/views/pages/overview/partials/overviewTab/overviewTabPreInduction.njk, server/views/pages/overview/partials/workAndInterestsTab/_inPrisonWorkInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
When we migrated the induction screens from the CIAG UI to the PLP UI we did so strictly on a "like for like" basis, and we used a feature toggle so that we could easily switch between the original CIAG UI or our new PLP screens.
This ticket RR-858 was created to remove the feature toggle once the new screens were deployed and proven to be OK (and we'd not had to switch back! 🤣 )
Since then we have made substantial changes to the PLP version of the induction question set. This has made the original CIAG UI and PLP UI induction screens/journey incompatible. Switching back to the CIAG UI via the feature toggle is now not an option.
This PR removes the feature toggle (there are 2 actually), and all associated logic
=> RR-858 - Remove feature toggles and associated logic re: whether to the original CIAG UI or not

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
Now we've completed all the tickets for archiving we can turn it on in preparation for a release to prod. Keeping the feature toggle for now in the unlikely event we need to rollback it'll be much faster to turn it off.
=> RR-824: turn on archiving feature toggle in all envs

feature.env, helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml, integration_tests/e2e/health.cy.ts, server/applicationInfo.ts, server/config.ts, server/middleware/setUpHealthChecks.ts, server/routes/testutils/appSetup.ts, server/services/healthCheck.test.ts
This PR adds the `activeAgencies` property to the `/info` endpoint in order to support [Establishment Specific Rollouts](https://dsdmoj.atlassian.net/wiki/spaces/ALIGN/pages/4480959439/Adding+changing+services+on+the+common+header+footer+and+the+homepage#Establishment-specific-rollouts)
We need to do this to be able to support further rollouts where the LSA's in prisons will be given the responsibility for assigning our service role to their DPS users.
=> RR-878 - Configure /info endpoint to include activeAgencies

integration_tests/e2e/goal/archiveGoal.cy.ts, integration_tests/e2e/goal/viewArchivedGoals.cy.ts, integration_tests/e2e/overview/overview.cy.ts, integration_tests/pages/goal/ViewArchivedGoalsPage.ts, server/views/pages/overview/viewArchivedGoals.njk
Change the view archived goals page to sort goals by most recently archived which is actually just the last updated date. This is because once it's archived there can be no further updates so the last update would have been marking it as archived.
Refactored the cypress tests a little bit so that view archived goals is now grouped together, we're also asserting the correct goals are loaded for each page rather than updating the wiremock mid test to simulate it.
=> RR-826: Sort archived goals by most recently archived

integration_tests/e2e/goal/viewArchivedGoals.cy.ts, server/@types/viewModels/index.d.ts, server/data/mappers/actionPlanMapper.test.ts, server/data/mappers/actionPlanMapper.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/viewArchivedGoalsController.test.ts, server/routes/unarchiveGoal/unarchiveGoalController.test.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/services/index.ts, server/services/prisonService.test.ts, server/services/prisonService.ts, server/views/components/goal-summary-card-v2/goalSummaryCardV2.test.ts, server/views/components/goal-summary-card-v2/template.njk
Show the name of the prison alongside the name of the person who last updated or archived a goal.
The new getPrisonNamesById method is intended to replace the single prison method as the client code for that became complicated to avoid a race condition where we would submit many requests to the prison api before it is cached.
=> RR-826: Populate prison name onto Goals for summary card

server/views/pages/goal/archive/reason.njk, server/views/pages/goal/archive/review.njk, server/views/pages/goal/unarchive/index.njk
This PR fixes the styling for multiline text for goal titles.
From this:
To this:
=> RR-824 - Add multiline text styling for goal title

server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_ARCHIVED.njk
This PR fixes the rendering of timeline events re: goal archive reasons.
It fixes this:
to this:
=> RR-828 - Fix rendering of goal archived reason

server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/archiveGoal/index.ts, server/services/auditService.ts
PR to send audit event when the user archives a goal.
We need to do this for other events (un-archive goal, update goal, create goals), but I thought I'd get this one in first to introduce and agree the approach, then the others can follow.
=> RR-764 - Send audit event when archiving a goal

server/routes/functionalSkills/functionalSkillsController.test.ts, server/routes/functionalSkills/functionalSkillsController.ts, server/routes/overview/supportNeedsController.test.ts, server/routes/overview/supportNeedsController.ts, server/services/curiousService.test.ts, server/services/curiousService.ts
Simplifying the lookup of multiple prisons per controller/service by instead retrieving them all at once. This is what was happening behind the scenes anyway.
One further change is required to timeline service but that's a little more involved as it's currently passing the entire prison to the template although it only even uses name & id (and id is only used as a fallback if no name)
=> RR-883 - Cleanup use of get prison by

server/errorHandler.ts, server/middleware/auditMiddleware.ts, server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/unarchiveGoal/index.ts, server/routes/unarchiveGoal/unarchiveGoalController.test.ts, server/routes/unarchiveGoal/unarchiveGoalController.ts, server/routes/updateGoal/index.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/services/auditService.test.ts, server/services/auditService.ts
Following on from my last PR which sent an audit event when Archiving a goal, this PR sends audit events when:
* Unarchiving a goal
* Updating a goal
The last event to audit in respect of Goals is the creation of a Goal, but I need to consider whether that is creating a goal (singular), goals (or whether its a series of create goal audit events), or whether the event is creating the action plan (in the case of creating the prisoner's first goal) .
=> RR-764 - Send audit event when unarchiving and updating a goal

server/data/mappers/timelineMapper.test.ts, server/data/mappers/timelineMapper.ts
We map the prison id to a name for prison transfer events in the timeline. Currently, the only contextual info is the prison but if we were to add more it would be lost during mapping. Now it keeps any other context info as well as mapping the prison id to name.
=> RR-883: Keep other context for prison transfer event

package-lock.json, package.json
Revert version of applicationinsights to ^2.9.5 in order to fix apparent breaking change of moving to v3
(with v3 it appeared that express and/or bunyan were not correctly instrumented, resulting in no `trace`, `request` or `exception` messages being logged in app insights)
=> RR-896 - revert version of `applicationinsights` to `^2.9.5`

README.md, server/middleware/auditMiddleware.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/createGoal/index.ts, server/routes/unarchiveGoal/unarchiveGoalController.ts, server/routes/updateGoal/updateGoalController.ts, server/services/auditService.test.ts, server/services/auditService.ts
This PR sends an audit event to HMPPS Audit when the user creates goal(s)
The minor difference between this and the previous PRs that send audit events is that the user journey allows the user to create one or more goals at the same time. Therefore the controller code needs to iterate through each new goal and send an event for each one.
The other difference is that in all previous "goal" related audit events, the context is that of an existing goal (eg: archive, unarchive or update and existing goal). In these cases we have the unique goal reference number so can include it in the `details` object of the event message data.
When creating new goals we do not have a reference number (it is generated by the API as part of creating the goal, and is not returned by the API). Therefore we …
=> RR-764 - Send audit event when creating goals

server/views/pages/induction/prePrisonEducation/qualificationLevel.njk
This PR adds the 'related content' sidebar to Qualification Level page:
=> RR-888 - Add 'related content' sidebar to Qualification Level page

server/views/pages/induction/prePrisonEducation/qualificationLevel.njk
Removed the hint "Add their highest level of qualification first. You can add any others afterwards." from the qualification level page.
Also added a margin to match other pages gap between title and form element. I think this was lost when it was re-structured so that the additional info URL aligns with the top radio (or it never existed).
=> RR-888: Remove hint and minor styling on qualification level

integration_tests/e2e/goal/reviewUpdateGoal.cy.ts, server/@types/express/index.d.ts, server/data/session/prisonerContexts.test.ts, server/data/session/prisonerContexts.ts, server/routes/routerRequestHandlers/checkUpdateGoalFormExistsInSession.test.ts, server/routes/routerRequestHandlers/checkUpdateGoalFormExistsInSession.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts
Avoid issues for users using multiple tabs with different users where session corruption can occur leading to errors and unexpected behaviour when editing & archiving goals.
I tried creating a custom type and using a Map but because of the session serialisation the type info is lost and you don't have access to the associated functions so I opted for a simple helper function instead.
=> Spike into a prisoner context in the session

integration_tests/e2e/goal/viewArchivedGoals.cy.ts, integration_tests/pages/goal/ViewArchivedGoalsPage.ts, server/views/pages/overview/viewArchivedGoals.njk
If there are no archived goals and someone accesses the view archived goals screen, the page should be displayed with the following message in place of where the list of archived goals would otherwise be:
“Firstname Lastname has no archived goals”
=> RR-825: Archived Goals page - no goals message

integration_tests/e2e/induction/createInduction.cy.ts, integration_tests/e2e/induction/updateEducationalQualifications.cy.ts, integration_tests/e2e/induction/updateEducationalQualificationsAddQualification.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts
This PR updates the cypress tests that:
1. create new qualifications as part of a new induction
2. updates an induction by adding & removing qualifications
to assert that the qualification reference number is sent in the relevant API request.
The implement for this was the last PR that introduced the mapping changes (and arguably the changes to these tests should have been in that PR 😬 ), but either way the tests in this PR prove that the qualification reference number is sent in the "update" API requests, and is null when the request involves adding new qualifications.
=> RR-901 - Cypress tests to prove mapping changes

integration_tests/e2e/overview/postInductionOverview.cy.ts, integration_tests/pages/overview/OverviewPage.ts
Changing the method goalSummaryCardAtPositionContains in OverviewPage.ts so that it is 1 indexed.
=> RR-916: Cypress tests - OverviewPage methods to use 1 based indexes

integration_tests/e2e/induction/createInduction.cy.ts, integration_tests/pages/prePrisonEducation/HighestLevelOfEducationPage.ts, integration_tests/support/commands.ts, server/routes/induction/create/highestLevelOfEducationCreateController.test.ts, server/routes/induction/create/highestLevelOfEducationCreateController.ts, server/routes/induction/create/index.ts, server/routes/routerRequestHandlers/createEmptyInductionIfNotInSession.test.ts, server/routes/routerRequestHandlers/createEmptyInductionIfNotInSession.ts
This PR makes use of the prisoners education record if it exists when creating their Induction.
If the prisoner does not have an education record, the induction flow and process as it is currently
If the prisoner has an education record before induction , the Highest Level of Education and Qualifications are pulled though into the Induction so that the CIAG does not need to enter them again.
=> RR-949 - Use prisoner's existing Education record in the Induction if they have one

integration_tests/e2e/prePrisonEducaton/createPrePrisonEducation.cy.ts, server/middleware/auditMiddleware.ts, server/routes/dynamicAriaTextResolver.ts, server/routes/prePrisonEducation/highestLevelOfEducationController.test.ts, server/routes/prePrisonEducation/highestLevelOfEducationController.ts, server/routes/prePrisonEducation/index.ts, server/routes/prePrisonEducation/qualificationDetailsController.test.ts, server/routes/prePrisonEducation/qualificationDetailsController.ts, server/routes/prePrisonEducation/qualificationLevelController.test.ts, server/routes/prePrisonEducation/qualificationLevelController.ts, server/routes/prePrisonEducation/qualificationsListController.test.ts, server/routes/prePrisonEducation/qualificationsListController.ts, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk
This PR refactors the routes for the new "add qualifications" pages (`/prisoner/:prisonNumber/highest-level-of-education` etc) to include the path element `/create-education` (eg: `/prisoner/:prisonNumber/create-education/highest-level-of-education` etc)
This is necessary in order to differentiate the routes between adding qualifications, and updating them (next PR)
Basically we need different routes for adding vs. updating as there will be different controller methods and logic
We already have a similar pattern with Inductions, in that the routes for Inductions are `/prisoner/:prisonNumber/create-induction/.....` for the create journey, and `/prisoner/:prisonNumber/induction/....` for the update journey.
I'm proposing we do the same for the qualifications journey, so this PR makes the …
=> RR-939 - Refactored create qualification routes to allow for us adding the update quals routes in the next PR

server/@types/prisonerSearchApiClient/index.d.ts, server/data/mappers/prisonerSearchSummaryMapper.ts, server/data/mappers/prisonerSummaryMapper.test.ts, server/data/mappers/prisonerSummaryMapper.ts, server/data/prisonerSearchClient.ts, server/services/prisonerListService.ts, server/testsupport/pagedCollectionOfPrisonersTestDataBuilder.ts, server/testsupport/prisonerTestDataBuilder.ts
This PR corrects the prisoner search API client module name
It was originally `prisonRegisterApiClient` (a copy and paste typo from the real Prison Register API Client !), and should be `prisonerSearchApiClient`
Whilst the app works with this incorrect module name, we need to fix this because a) it is wrong/misleading and b) we are about to make some improvements to how Prisoner Search works, so we need this module name to be correct
=> RR-895 - Corrected module name for prisoner search API client

integration_tests/e2e/page-not-found.cy.ts
This PR fixes and improves a couple of cypress tests re: page not found
These tests need to be changed/improved as per this PR because the changes we are about to introduce re: caching prisoner searches ends up breaking one of the tests (because they are actually flawed! 🙄 )
=> RR-895 - Fixed and improved the "page not found" cypress tests

server/routes/prePrisonEducation/create/index.ts, server/routes/routerRequestHandlers/createEmptyEducationDtoIfNotInPrisonerContext.ts
This PR renames the function `createEmptyInductionIfNotInSession` to `createEmptyEducationDtoIfNotInPrisonerContext` which is more reflective of what it actually does! 🤣 
(clearly some copy and paste going on when I originally wrote this function 🤣 , but it has nothing to do with an Induction and it doesnt hold it in the session! 🤣 )
=> Corrected function name for createEmptyEducationDtoIfNotInPrisonerContext

server/data/index.ts, server/data/prisonerSearchStore/prisonerSearchStore.test.ts, server/data/prisonerSearchStore/prisonerSearchStore.ts, server/middleware/auditMiddleware.test.ts, server/services/index.ts, server/services/prisonerSearchService.test.ts, server/services/prisonerSearchService.ts
This PR adds caching to the prisoner search service method
IE. the service method to lookup a prisoner from `prisoner-search-api` and return as a `PrisonerSummary`
This follows our existing patterns where we do similar things (prison lookups via prison-register-api for example), where the service method and it's method signature do not change, but the internal implementation of the method looks in the redis cache first rather than simply calling the API.
=> RR-895 - Cache prisoner searches with a redis backed `prisonerSearchStore`

assets/scss/local.scss, integration_tests/e2e/overview/overview.cy.ts, server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.njk, server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.test.ts
Removing the 'Completed goals' grid item from the Goals summary card on overview page.
=> Rr 954 remove completed goals

server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_CREATED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_CREATED.test.ts, server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_UNARCHIVED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_UNARCHIVED.test.ts, server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_UPDATED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-GOAL_UPDATED.test.ts, server/views/pages/overview/partials/timelineTab/_timelineEvent-MULTIPLE_GOALS_CREATED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-MULTIPLE_GOALS_CREATED.test.ts
PR to fix the text on the timeline entries as per the AC of RR-870
> ## Acceptance Criteria
> * Does the link for a Goal Created event read “View in progress goals”?
> * Does the link for a Multiple Goals Created event read “View in progress goals”?
> * Does the link for a Goal Updated event read “View in progress goals”?
> * Does the link for a Goal Archived event read “View archived goals”?
> * Does the link for a Goal Reactivated (unarchived) event read “View in progress goals”?
=> RR-870 - Corrected link text on timeline entries

assets/scss/local.scss, server/routes/overview/mappers/functionalSkillsMapper.test.ts, server/routes/overview/mappers/functionalSkillsMapper.ts, server/services/curiousService.test.ts, server/services/curiousService.ts, server/views/pages/overview/index.njk, server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.njk, server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.test.ts
- Moved the goals columns to the left
- Changed In progress status tag from green to blue
- For FS initial assessments -  “assessed on… “ aligned to the right and the level next to the subject
- For courses and qualifications - remove column names
- Vertically align 'Add a goal' and target icon in actions card
- Print button activated for pre-induction
=> RR-954: Team test changes

server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
This PR puts the tab content headings on the page, even if the there are no in-progress or archived goals (as per the designs)
=> RR-953 - Fixed headings

assets/scss/local.scss, integration_tests/e2e/overview/goal/archiveGoal.cy.ts, integration_tests/e2e/overview/goal/reviewUpdateGoal.cy.ts, integration_tests/e2e/overview/goal/updateGoal.cy.ts, integration_tests/pages/goal/GoalsPage.ts, server/views/pages/overview/partials/goalsTab/goalsTabContents.njk, server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts
Using custom css for the tab panel. Changed the goal reference in the goal summary card to use the actual reference rather than the index. Added unit tests for the goals view.
=> RR-1002: Use css for tab panel change, change goal ref from index to ref

server/@types/express/index.d.ts, server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts
This PR moves `ArchiveGoalForm` from being held on the session to being held on the prisoner context.
We need this to be done before we go touching the `ArchiveGoalForm` and `ArchiveGoalController` in respect of adding Notes to archiving a goal; so is worth getting this done as a separate change 👍
=> RR-907 - Moved ArchiveGoalForm to the prisoner context

server/views/components/goal-summary-card/_goalSteps.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ACTIVE.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-COMPLETED.njk, server/views/components/goal-summary-card/_goalSummaryCardHeadingAndActions.njk, server/views/components/goal-summary-card/template.njk
This PR refactors the goal-summary-card so that there is a different include/component for each goal status type (active/completed/archived)
This will allow for the design team to change/iterate the designs for each goal type
=> RR-932 - Refactored goal-summary-card to better allow for design changes/iterations

server/testsupport/actionPlanTestDataBuilder.ts, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ACTIVE.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-COMPLETED.njk, server/views/components/goal-summary-card/_goalSummaryCardHeadingAndActions.njk, server/views/components/goal-summary-card/template.njk, server/views/pages/overview/partials/goalsTab/goalsTabContents.njk, server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts
This PR corrects the order in which in-progress goals and archived goals are displayed on their tabs.
In-Progress goals should be displayed in order of target completion date, soonest first
Archived goals should be displayed in the order of archiving date (updatedDate), soonest last
=> RR-1006 / RR-1007 - Correcting the order of archived and in-progress goals

integration_tests/e2e/overview/goal/viewArchivedGoals.cy.ts, integration_tests/pages/overview/GoalsPage.ts, server/@types/viewModels/index.d.ts, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.test.ts, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED_V1.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED_V2.njk, server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-COMPLETED.njk, server/views/components/goal-summary-card/goalSummaryCard.test.ts, server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts
This PR updates the content of the goal summary card for archived goals, to display the goal archived notes (if entered), and also to move the reason the goal was archived (based on current designs)
=> RR-932 - Updated content of goal summary card for archived goals

integration_tests/e2e/induction/updateEducationalQualifications.cy.ts, integration_tests/e2e/prePrisonEducaton/createPrePrisonEducation.cy.ts, integration_tests/pages/overview/EducationAndTrainingPage.ts, server/middleware/auditMiddleware.ts, server/routes/prePrisonEducation/update/index.ts, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk
This PR fixes a user reported bug which prevents qualifications being added to an Induction that has no qualifications to start with.
The basic scenario is that a CIAG has created an Induction for a prisoner, and when they created the Induction that did not enter any qualifications (ie. they answered No to the question "Do you want to add educational qualifications")
The CIAG at some point later comes back to the prisoner's Induction, and on the Education & Training tab, where it correctly displays no qualifications, they click the Change button to retrospectively add the prisoners qualifications.
The bug is that instead of being asked the Qualification Level for the 1st qualification, they are instead redirected back to the Eduction & Training tab.
The problem was that the Change link …
=> RR-1073 - Fix bug which prevents qualifications being added to an Induction that has no qualifications to start with

server/app.ts, server/config.ts, server/middleware/checkWhetherToShowServiceOnboardingBanner.test.ts, server/middleware/checkWhetherToShowServiceOnboardingBanner.ts, server/routes/reviewPlan/index.ts
This PR adds a feature toggle function to determine if a given prison is one of the prisons enabled for the service.
We need this for the middleware (which I've also written) which will be used to set a flag as to whether to show the "prison is not onboarded" banner or not (to be developed in RR-1091)
I've also refactored the `reviewsPrisonsEnabled` feature toggle to be a function that is called in a similar way.
=> RR-991 - Added feature toggle function for enabled prisons

server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.test.ts, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.test.ts, server/views/pages/overview/partials/goalsTab/goalsTabContents.njk, server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts, server/views/pages/overview/partials/overviewTab/overviewTabContents.njk, server/views/pages/overview/partials/overviewTab/overviewTabContents.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_inPrisonWorkInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.test.ts, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
For users without editor role:
- Removed href in create learning and work progress plan paragraph in education and training and work and interests tabs 
- Removed create induction banner and actions card in overview tab
- Removed goal update/complete/archive/unarchive links and actions card in goals tab
- Removed change/add links in Education and training tab
- Removed change/add links in Work and interests tab
NB: Have asked for confirmation with BA that removal of the href, induction banner and actions card is acceptable.
https://github.com/user-attachments/assets/daf04d46-9e98-430d-b3c6-646869f93f43
=> RR-1092: Remove links for read only users

helm_deploy/values-dev.yaml
PR to set the enabled prisons in dev to allow for testing read-only access
For any prison not in the list we would expect to see the new "your prison is not onboarded" banner
Previously the "all prisons wildcard" was set for dev, so we would never be able to test the "your prison is not onboarded" banner
=> RR-1092 - Set enabled prisons in dev to allow for testing read-only access

server/routes/overview/index.ts, server/routes/overview/mappers/functionalSkillsMapper.test.ts, server/routes/overview/mappers/functionalSkillsMapper.ts, server/routes/overview/mappers/prisonerSupportNeedsMapper.test.ts, server/routes/overview/mappers/prisonerSupportNeedsMapper.ts, server/routes/overview/supportNeedsController.test.ts, server/routes/overview/supportNeedsController.ts, server/services/curiousService.test.ts, server/services/curiousService.ts, server/testsupport/learnerEducationPagedResponseTestDataBuilder.ts
Similar refactoring to my last PR, this refactors how the Support Needs data from Curious gets populated, specifically on the Support Needs page.
Previously we had a middleware that retrieved the Prisoner Support Needs from Curious via a method in `CuriousService`. Then in the controller we injected the prison service and used it to look up the prison name. It was all a little bit disjointed.
The PrisonService was already being injected into the CuriousService (to look up prisons for another Curious data set), so it makes sense for the CuriousService method that gets the Prisoner Support Needs data to lookup prison data at the same time.
Thats what this PR does 👍
=> RR-1157 - Refactor how Support Needs page makes curious service calls

server/services/reviewService.test.ts, server/services/reviewService.ts
This PR handles a 404 from the API when retrieving the prisoner's Action Plan Reviews as a happy path.
As designed the API correctly returns a 404 when the prisoner has no Review Schedule.
For the UI though this isn't really an error - it just means the prisoner has no schedule, but more importantly has no previous reviews.
The change in this PR handles the 404 from the API, returning a valid `ActionPlanReviews` object, but with no `latestReviewSchedule` and an empty array of `completedReviews`
=> RR-1157 - Handle 404 from API as a "happy" path

server/routes/functionalSkills/functionalSkillsController.ts, server/routes/functionalSkills/functionalSkillsView.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.test.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.ts, server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsView.ts, server/routes/overview/overviewController.ts, server/routes/overview/overviewView.ts, server/routes/overview/viewGoalsController.ts, server/routes/overview/viewGoalsView.ts, server/routes/prisonerList/prisonerListController.ts, server/routes/prisonerList/prisonerListView.ts
This PR is loosely part of RR-1157 in that it is aiming to tidy up some of the view classes we have, as some of them (especially `OverviewView`) are getting a bit big and bloaty.
We potentially need to add some more stuff to `OverviewView` to support the work we are currently doing (adding Session stats, and controls to manipulate Reviews etc to the page), so I wanted to clean up the view object first.
It turns out that when things are already on `res.locals` via some middleware, then the nunjucks view can automatically see it, and we dont need to explicitly add it to a view object and render it into the view template 👍 
This can simplify many of our view classes as there are several objects that are now retrieved via middlewares and added to `res.locals`.
This PR removes …
=> RR-1157 - Tidy view classes (pt1) by removing showServiceOnboardingBanner

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Tiny change to the helm deployment to configure the modsec WAF (Web Application Firewall) into detection-only mode, as per the decision and agreement in [ADR-004](https://dsdmoj.atlassian.net/wiki/spaces/RR/pages/5304352991/ADR-004+Use+modsec+WAF+in+detection-only+mode+for+PLP+UI)
=> RR-1159 - Configure WAF to be in detection-only mode

integration_tests/e2e/overview/overview.cy.ts, integration_tests/pages/overview/OverviewPage.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewView.ts, server/testsupport/actionPlanReviewsTestDataBuilder.ts, server/testsupport/completedActionPlanReviewTestDataBuilder.ts, server/testsupport/noteTestDataBuilder.ts, server/views/pages/overview/partials/_actionsCard.njk
This PR fixes a bug with the Reviews based actions in the Actions Card (if the prisoner had no Review Schedule at all, the Review was shown as Overdue with no review date)
It also improves the logic, terminology and tests for the code that is responsible for displaying the actions card, including adding a couple of cypress tests.
=> RR-1028 - Improved logic and tests for Reviews based actions in the Actions Card

helm_deploy/values-dev.yaml
This PR sets the list of prisons in dev that can use the Reviews feature.
The list is BXI (Brixton), Wakefield (WDI) and Bristol (BLI) because that matches the list of prisons that I have run the ETL on to create Review Schedules 👍
=> RR-1028 - Set list of prisons enabled for Reviews feature in DEV

server/@types/dto/index.d.ts, server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/educationAndWorkPlanApiClient/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/data/mappers/createActionPlanMapper.test.ts, server/data/mappers/createActionPlanMapper.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/testsupport/actionPlanSummaryResponseTestDataBuilder.ts, server/testsupport/createActionPlanDtoTestDataBuilder.ts, server/testsupport/createActionPlanRequestTestDataBuilder.ts
This PR introduces the client and service methods to be able to call the `createActionPlan` API (rather than the UI calling the `createGoals` method when it wants to create the action plan)
This PR only introduces the methods, it does not wire them in or use them.
My next PR will wire the call to the service method into the relevant points in the user journey 👍
=> RR-227 - Introduced client and service methods to be able to call the createActionPlan API

server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/archiveGoal/index.ts, server/routes/completeOrArchive/completeOrArchiveGoalController.ts, server/routes/completeOrArchive/index.ts, server/routes/completegoal/completeGoalController.ts, server/routes/completegoal/index.ts, server/routes/postInductionCreation/index.ts, server/routes/unarchiveGoal/index.ts, server/routes/unarchiveGoal/unarchiveGoalController.test.ts, server/routes/unarchiveGoal/unarchiveGoalController.ts, server/routes/updateGoal/index.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts
This PR tidies and simplifies the uses of `getActionPlan` in preparation for changing the API to return a 404 when no action plan exists.
`getActionPlan` is an API that exists to return the prisoner's action plan (collection of goals).
There is a TODO on the API service method to make it return a 404 when the UI is calling the new `createActionPlan` API endpoint:
```
/**
* Retrieves a Prisoner's [ActionPlan] based on their prison number.
* Returns a new [ActionPlan] if the [ActionPlan] cannot be found.
*/
fun getActionPlan(prisonNumber: String): ActionPlan {
log.debug { "Retrieving Action Plan for prisoner [$prisonNumber]" }
// TODO RR-227 - return 404 if not found
val actionPlan = persistenceAdapter.getActionPlan(prisonNumber)
?: ActionPlan(
reference = UUID.randomUUID(),
prisonNumber = …
```
=> RR-227 - Tidied and simplified uses of getActionPlan

integration_tests/e2e/overview/goal/archiveGoal.cy.ts, integration_tests/e2e/overview/goal/completeGoal.cy.ts, integration_tests/e2e/overview/goal/reviewUpdateGoal.cy.ts, integration_tests/e2e/overview/goal/unarchiveGoal.cy.ts, integration_tests/e2e/overview/goal/updateGoal.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, server/@types/viewModels/index.d.ts, server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/archiveGoal/index.ts, server/routes/completeOrArchive/completeOrArchiveGoalController.ts, server/routes/completeOrArchive/index.ts, server/routes/completegoal/completeGoalController.ts, server/routes/completegoal/index.ts, server/routes/overview/index.ts, server/routes/overview/overviewController.test.ts, server/routes/overview/overviewController.ts, server/routes/unarchiveGoal/index.ts, server/routes/unarchiveGoal/unarchiveGoalController.test.ts, server/routes/unarchiveGoal/unarchiveGoalController.ts, server/routes/updateGoal/index.ts, server/routes/updateGoal/updateGoalController.test.ts, server/routes/updateGoal/updateGoalController.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts
This PR builds upon my recent PRs re: how the UI gets the action plan & goals.
The changes in this PR are to make use of `retrieveGoals` by status middleware where it makes more sense to do so, rather than getting the entire action plan.
Specifically this is on the controller routes for archiving, completing, unarchiving and updating goals. My previous PR made changes to these routes so that they retrieved all goals for the prisoner then filtered the list to get the specific goal in question.
The changes in this PR add a minor efficiency to this by using the `retrieveGoals` (by status) middleware. So each of these controller routes now only gets a subset of the goals (based on the status that we know the goal should be in for the given operation), and then filters to get the specific …
=> RR-227 - Make use of retrieveGoals by status

integration_tests/e2e/overview/goal/createGoals.cy.ts, integration_tests/e2e/postInductionCreation/postInductionCreation.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts, server/routes/createGoal/index.ts, server/routes/postInductionCreation/index.ts, server/routes/routerRequestHandlers/retrieveActionPlan.test.ts, server/routes/routerRequestHandlers/retrieveActionPlan.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts
I think this is the last of the 'enabler' PRs for the UI to get us in a position for the API to know whether to create a Review Schedule or not.
This is the key change that makes the UI know whether to call the `createGoals` API endpoint (ie. for prisoners who already have an existing Action Plan), or the `createActionPlan` endpoint (for prisoners who do not already have an action plan)
Once the UI is calling `createActionPlan` when it needs to create an action plan, then we can turn to the API and make the action of creating the Action Plan also create the initial Review Schedule
=> RR-227 - Call createGoals or createActionPlan depending on whether prisoner needs an Action Plan creating

server/services/educationAndWorkPlanService.ts, server/services/inductionService.ts
This PR removes the error logging in the service layer for getEducation and getInduction because the error handling and associated logging is handled further up the stack by code calling these service methods.
As it stands currently we get an error logged (logger.error) when getEducation and getInduction return a 404
Whilst a 404 is an error response, in our scenario and user journeys is is perfectly normal for a prisoner to not have an Induction or Education record at various points of the lifecycle, and indeed we use the absence of data to drive the UI down different paths of the journey
At the moment, with the service method logging a 404 as an error, and then the calling code also logging it (but at info because it is a normal/handled situation) we are seeing a lot of noise in the …
=> Removed error logging at the service layer for getInduction and getEducation

server/routes/overview/overviewController.test.ts, server/routes/overview/overviewView.ts, server/views/pages/overview/partials/overviewTab/_sessionHistorySummaryCard.njk, server/views/pages/overview/partials/overviewTab/_sessionHistorySummaryCard.test.ts
This PR corrects the count in the Session history box on the main Overview screen.
The session count is the number of sessions held with a prisoner, where a "session" is their initial Induction, plus any Reviews.
The initial development of this count considered the Induction as simply being that the Induction record exists.
However, the Induction is only considered complete when there is both the Induction + at least 1 goal.
This PR corrects that logic.
=> RR-1027 - Correct the count in the Session history box

server/routes/reviewPlan/exemption/exemptionRecordedController.test.ts, server/routes/reviewPlan/exemption/exemptionRecordedController.ts, server/routes/reviewPlan/exemption/index.ts, server/views/pages/reviewPlan/review/checkYourAnswers/index.njk, server/views/pages/reviewPlan/review/checkYourAnswers/index.test.ts
PR to fix a small bug re: the success banner content.
Basically when the exemption reason is System Issue the banner should simply read:
> Exemption recorded.
If the exemption reason was anything else it should read: 
> Exemption recorded. **You must remove this exemption when the reason no longer applies.**
=> RR-1047 - Corrects success banner message when exemption reason was System Issue

server/routes/overview/overviewController.test.ts, server/routes/overview/overviewView.ts, server/views/pages/overview/partials/_actionsCard.njk
Currently there is a small bug with the Reviews UI stuff we have been doing recently with the Actions menu; in that if the prisoner does not yet have a Review Schedule setup for any reason (perhaps they've not yet had their Induction etc), then we display "no reviews due". Whilst arguably this might be correct, its not what the business intended. They intended the "no reviews due" content to show when the prisoner has had their last review before release, and hence another review is not due. This is why it also shows the release date
=> RR-1028 - No review actions displayed when the prisoner has no scheduled review

integration_tests/e2e/reviewPlan/review/reviewPlan.cy.ts, integration_tests/e2e/reviewPlan/review/reviewPlanCheckYourAnswers.cy.ts, integration_tests/pages/reviewPlan/WhoCompletedReviewPage.ts, integration_tests/support/commands.ts, server/@types/dto/index.d.ts, server/@types/forms/index.d.ts, server/data/mappers/createActionPlanReviewRequestMapper.test.ts, server/data/mappers/createActionPlanReviewRequestMapper.ts, server/enums/reviewPlanCompletedByValue.ts, server/enums/sessionCompletedByValue.ts, server/routes/reviewPlan/review/reviewCheckYourAnswersController.test.ts, server/routes/reviewPlan/review/reviewNoteController.test.ts, server/routes/reviewPlan/review/whoCompletedReviewController.test.ts, server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.test.ts, server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.ts, server/testsupport/reviewPlanDtoTestDataBuilder.ts, server/views/pages/reviewPlan/review/checkYourAnswers/index.test.ts, server/views/pages/reviewPlan/review/reviewNote/index.test.ts
This PR rename the `ReviewPlanCompletedByValue` to `SessionCompletedByValue` because we are about to make use of it elsewhere.
Basically `ReviewPlanCompletedByValue` is the enum for the UI answers "I did it myself" and "someone else did it", and it was introduced as part of the Review UI journey (ie. to support the "who did the review" screen)
We now need to introduce the "who did the induction" screen, which is essentially the same thing, so I want to rename this enum so we can use it in both places 👍
=> RR-1041 - Rename ReviewPlanCompletedByValue to SessionCompletedByValue

server/@types/dto/index.d.ts, server/@types/express/index.d.ts, server/@types/forms/index.d.ts, server/routes/induction/common/inductionNoteController.ts, server/routes/induction/common/inductionNoteView.ts, server/routes/induction/common/whoCompletedInductionController.ts, server/routes/induction/common/whoCompletedInductionView.ts, server/routes/induction/create/inductionNoteCreateController.test.ts, server/routes/induction/create/inductionNoteCreateController.ts, server/routes/induction/create/whoCompletedInductionCreateController.test.ts, server/routes/induction/create/whoCompletedInductionCreateController.ts, server/routes/validators/induction/inductionNoteFormValidator.test.ts, server/routes/validators/induction/inductionNoteFormValidator.ts, server/routes/validators/induction/whoCompletedInductionFormValidator.test.ts, server/routes/validators/induction/whoCompletedInductionFormValidator.ts, server/views/pages/induction/inductionNote/index.njk, server/views/pages/induction/whoCompletedInduction/index.njk, server/views/pages/induction/whoCompletedInduction/index.test.ts
This PR adds the nunjucks templates, controllers, validators, form & DTO changes and unit tests for the 2 new screens that we need to add to the Induction journey (Who completed Induction, & Induction notes)
In this PR I have defined the routes for the new pages yet, and have not wired the new screens into the existing journey. Those changes, along with cypress tests, will come in my next PR
=> RR-1041/RR-1177 - Nunjucks templates & controllers for new Induction screens

server/routes/archiveGoal/archiveGoalController.test.ts, server/routes/archiveGoal/archiveGoalController.ts, server/routes/completegoal/completeGoalController.test.ts, server/routes/completegoal/completeGoalController.ts, server/routes/unarchiveGoal/unarchiveGoalController.test.ts, server/routes/unarchiveGoal/unarchiveGoalController.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/services/reviewService.test.ts
This is the first in a series of PRs for RR-1222
RR-1222 is to change all calls to create/update (POST/PUT) API calls, to use the system token rather than the UI token.
We are now able to start doing this now that we have removed the displayName stuff from the various entities in the API 👍 
Because there are quite a few to do, I'll be splitting them up and doing them over several PRs.
---
This PR uses the system token for API calls to archive, unarchive and complete goals
(the API calls and the relevant code being changed is all very similar for these 3, so I have grouped them into this one PR)
=> RR-1222 - Use the system token for calls to archive, unarchive, and complete goals.

package-lock.json, package.json, server/middleware/setUpCsrf.ts
This PR replaces the `csurf` library with `crsf-sync` which the UI uses for CSRF tokens.
The use of the `csurf` library came from the original typescript template, that this project was originally cloned from.
Since then the `csurf` library has [become deprecated](https://www.npmjs.com/package/csurf) with no obvious or recommended alternative.
At the same time, [dependabot has identified a vulnerability](https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/security/dependabot/25) that it cannot fix because of the dependency on `csurf`
This problem has been addressed in the [typescript-template via this PR](https://github.com/ministryofjustice/hmpps-template-typescript/pull/481), which in turn has been used in other UI projects including [Accredited …
=> Replace csurf with csrf-sync

server/routes/overview/educationAndTrainingController.test.ts, server/routes/overview/educationAndTrainingController.ts, server/routes/overview/educationAndTrainingView.ts, server/routes/overview/index.ts, server/routes/overview/workAndInterestsController.test.ts, server/routes/overview/workAndInterestsController.ts, server/routes/overview/workAndInterestsView.ts, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.test.ts, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.test.ts, server/views/pages/overview/partials/overviewTab/overviewTabContents.njk, server/views/pages/overview/partials/overviewTab/overviewTabContents.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.test.ts, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.test.ts
This PR adds in the UI logic to prevent the user being prompted to create the prisoner's induction when the Induction Schedule has been exempted (on hold)
(A subsequent PR will make similar changes to prevent the user adding goals when the Induction Schedule is on hold)
=> RR-1234 - Prevent creating Induction if Induction Schedule is on hold

server/routes/overview/index.ts, server/routes/overview/viewGoalsController.test.ts, server/routes/overview/viewGoalsController.ts, server/routes/overview/viewGoalsView.ts, server/views/components/actions-card/_goalActions.njk, server/views/components/actions-card/_goalActions.test.ts, server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
This PR adds in the UI logic to prevent the user being prompted to create Goals when the Induction Schedule has been exempted (on hold)
=> RR-1234 - Prevent creating Goals if Induction Schedule is on hold

package-lock.json, package.json, server/app.ts
PR to bring in the latest version of `hmpps-connect-dps-components` and call it with the flag to request the fallback header and footer, resulting in the fallback header and footer being used in all circumstances.
=> RR-1228 - Use fallback header and footer

server/views/pages/overview/partials/timelineTab/_timelineEvent-ACTION_PLAN_REVIEW_SCHEDULE_STATUS_UPDATED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-ACTION_PLAN_REVIEW_SCHEDULE_STATUS_UPDATED.test.ts, server/views/pages/overview/partials/timelineTab/_timelineEvent-INDUCTION_SCHEDULE_STATUS_UPDATED.njk, server/views/pages/overview/partials/timelineTab/_timelineEvent-INDUCTION_SCHEDULE_STATUS_UPDATED.test.ts
PR to fix a problem with the timeline rendering, specifically for Induction Schedule and Review Schedule status change events, where the new status is COMPLETED.
Currently we mis-interpret these events to be an Exemption event (but with a load of missing detail):
What we should do is ignore these events, and not render them at all (because completion of a Review has it's own event type which we correctly render anyway)
=> RR-1179 - Fix timeline rendering of Induction Schedule and Review Schedule "completion" events

server/routes/induction/create/index.ts, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk, server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.test.ts, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.test.ts, server/views/pages/overview/partials/overviewTab/overviewTabContents.njk, server/views/pages/overview/partials/overviewTab/overviewTabContents.test.ts, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.test.ts
This PR replaces the old `hasEditAuthority` permission checks with the new permission checks for creating inductions.
All the places on screen where we offer a link to create the induction now uses the new `userHasPermissionTo('RECORD_INDUCTION')` check; and the route definitions use the new `checkUserHasPermissionTo(ApplicationAction.RECORD_INDUCTION)` check.
=> RR-1240 - Use new permission checks for creating Inductions

server/routes/induction/update/index.ts, server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk, server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_inPrisonWorkInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk, server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.test.ts, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.njk, server/views/pages/overview/partials/workAndInterestsTab/_personalSkillsAndInterestsSummaryCard.test.ts, server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.test.ts
This PR replaces the old `hasEditAuthority` permission checks with the new permission checks for updating inductions.
All the places on screen where we offer a link to update the induction now uses the new `userHasPermissionTo('UPDATE_INDUCTION')` check; and the route definitions use the new `checkUserHasPermissionTo(ApplicationAction.UPDATE_INDUCTION)` check.
=> RR-1240 - Use new permission checks for updating Inductions

server/@types/viewComponents/index.d.ts, server/routes/createGoal/index.ts, server/views/components/actions-card/_goalActions.njk, server/views/components/actions-card/_goalActions.test.ts, server/views/components/actions-card/_inductionActions.test.ts, server/views/components/actions-card/_reviewActions.test.ts, server/views/components/actions-card/actionCards.test.njk, server/views/components/actions-card/actionsCard.test.ts
This PR replaces the old `hasEditAuthority` permission checks with the new permission checks for creating goals.
All the places on screen where we offer a link to create a goal now uses the new `userHasPermissionTo('CREATE_GOALS')` check; and the route definitions use the new `checkUserHasPermissionTo(ApplicationAction.CREATE_GOALS)` check.
=> RR-1240 - Use new permission checks for creating goals

server/routes/overview/index.ts, server/routes/overview/overviewController.ts, server/routes/overview/overviewView.ts, server/routes/routerRequestHandlers/retrievePrisonNamesById.ts
This PR fixes a small problem on the new Sessions History box, where the prison name was not being looked up
=> RR-1242 - Lookup and display prison name in session history box

server/routes/functionalSkills/functionalSkillsController.ts, server/services/curiousService.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/services/prisonerListService.ts, server/services/reviewService.test.ts, server/services/reviewService.ts
Small PR to make a small fix to a coding style re: async method calls.
When a method returns a `Promise`, there are 2 styles / approaches to call it.
The original way was to use `.then` callback methods. The problem with this approach is that it can create "callback hell", where you can end up chaining and nesting several `.then` calls.
A more modern and generally recommended approach is to use `await`, where the `await` keyword basically says "wait for this promise to be resolved"
This PR refactors a coupe of places where we'd implemented both patterns in the same call! 😬 EG: this type of thing:
```
const prisoners: Prisoner[] = await this.prisonerSearchClient
.getPrisonersByPrisonId(prisonId, page, pageSize, systemToken)
.then(pagedCollectionOfPrisoners => …
```
=> Fix async code pattern to not use `.then` callbacks

cypress.config.ts, integration_tests/e2e/prisonerList/prisonerList.cy.ts, integration_tests/e2e/sessionSummary/sessionSummary.cy.ts, integration_tests/index.d.ts, integration_tests/pages/prisonerList/PrisonerListPage.ts, integration_tests/pages/sessionSummary/SessionsSummaryPage.ts, integration_tests/support/commands.ts, server/middleware/auditMiddleware.test.ts, server/routes/index.ts, server/routes/routerRequestHandlers/populateActiveCaseloadPrisonName.test.ts, server/routes/routerRequestHandlers/populateActiveCaseloadPrisonName.ts, server/routes/sessionSummary/index.ts, server/routes/sessionSummary/sessionSummaryController.test.ts, server/routes/sessionSummary/sessionSummaryController.ts, server/routes/sessionSummary/sessionSummaryView.ts, server/views/pages/sessionSummary/_searchBox.njk, server/views/pages/sessionSummary/index.njk
PR to create the basic route, controller and view for the new Sessions Summary landing page & journey; for users who have the new `ROLE_LWP_MANAGER` role.
In this initial commit, the Sessions Summary nunjucks view only has the mini-search box, and does not have the section above that shows the counts (due, overdue and on-hold). This PR is about getting the basic routing etc working. I'll start to add the counts section and integrations in subsequent PRs.
If the user does not have the new `ROLE_LWP_MANAGER` role they get the existing prisoner list landing page.
If the user has the new role they get the new landing page and journey, as per this screen recording:
https://github.com/user-attachments/assets/2db17865-99cb-4d9e-bac4-812c6b40ca39
=> RR-1023 - Basic route, controller and view for Session Summary page

assets/scss/local.scss, server/views/pages/overview/partials/overviewTab/_goalsSummaryCard.njk, server/views/pages/sessionSummary/_sessionsSummaryCountsBox.njk, server/views/pages/sessionSummary/index.njk
PR to add the markup to the nunjucks template to add the session counts to the Session Summary page
(counts are hardcoded at the moment - this PR is about the layout and markup, rather than integrating the API call)
=> RR-1023 - Added the counts section to the Session Summary page

server/@types/educationAndWorkPlanApi/index.d.ts, server/@types/educationAndWorkPlanApiClient/index.d.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/enums/sessionStatusValue.ts, server/enums/sessionTypeValue.ts, server/testsupport/sessionResponseTestDataBuilder.ts
PR to add the API client method to call the new API endpoint to get sessions for a list of prison numbers, inc passing in the mandatory status query string param
=> RR-1024 - Reimport swagger spec; add API client method to get sessions

server/@types/viewModels/index.d.ts, server/routes/prisonerList/pagedPrisonerSearchSummary.ts, server/routes/sessionList/pagedPrisonerSummaryPrisonerSession.test.ts, server/routes/sessionList/pagedPrisonerSummaryPrisonerSession.ts, server/testsupport/prisonerSummaryPrisonerSessionTestDataBuilder.ts
This PR is part of the client side search & filter capability for the session list pages.
Because (at the moment) our search pages need to get data from 2 sources (prisoner list in order to get prisoner summary data, plus our own API for the sessions for those prisoners), **the filtering, sorting and pagination is all done client side** (this will change if we start storing prisoner summary data in our own database/API). But at the moment that's how it has to work 🤷‍♂️ 
This PR introduces the classes and code to support the client side filtering, sorting and pagination (wiring it up into the controller and view will come in my next PR)
The basic idea is that we have a view model class which represents each "row" in the search results. This is the snappily named …
=> RR-1024 - pagedPrisonerSummaryPrisonerSession

helm_deploy/hmpps-education-and-work-plan-ui/values.yaml, helm_deploy/values-dev.yaml
Now that the HAAR team have created the new client and setup the secrets in preprod and prod, we can make this change and deploy to preprod and prod 👍
=> RR-1265 - Enable curious client id secrets in all envs

server/data/prisonerSearchStore/prisonerSearchStore.test.ts, server/data/prisonerSearchStore/prisonerSearchStore.ts, server/services/prisonerSearchService.ts
This PR is part of a bugfix for something that Adam Woollard has raised.
The UI caches the prisoner record from prisoner search api to prevent the need to retrieve it on every page request (that you're working with that prisoner)
The current cache TTL for the prisoner record is 24 hours
Adam has raised a problem where a prisoner is transferred - if someone accesses their PLP just before they are transferred from prison A, that prisoner record (inc. their prison ID) is cached for 24 hours. Within that 24 hour period, after transfer from prison A, if someone were to update their PLP in their new prison, it would be incorrectly recorded as being in prison A (rather than prison B)
The quick fix for this is to reduce the cache TTL. A 1 hour cache TTL still gives the benefit of caching the …
=> RR-1269 - Reduce prisoner cache TTL from 24 hours to 1 hour

assets/scss/print.scss, server/views/pages/overview/partials/overviewTab/_goalsSummaryCard.njk, server/views/pages/overview/partials/overviewTab/_sessionHistorySummaryCard.njk, server/views/pages/overview/partials/overviewTab/overviewTabContents.njk, server/views/pages/prisonerList/partials/searchBox.njk, server/views/pages/prisonerList/partials/searchTable.njk, server/views/pages/sessionList/_searchBox.njk, server/views/pages/sessionList/macros/searchResultsTable.njk, server/views/pages/sessionSummary/_searchBox.njk, server/views/pages/sessionSummary/_sessionsSummaryCountsBox.njk
This PR fixes a small problem thats been kicking around for a while, in that when you print certain pages, any links on the page are displayed in the printed output (which is obviously rubbish because you cant click things on printed paper 😁 )
We have a pattern for this on the rest of the service, in that there is a standard govuk class (`govuk-!-display-none-print`) which hides things when printed. We've applied it to most pages, but a few slipped through the net.
This is what it does currently:
And this is what it does once this PR is merged:
=> RR-1186 - Do not render links when printing page

server/routes/landingPage/index.ts
Make the new sessions summary page dependent on feature toggle as well as user role
This means we can start giving people the new Manager role early (as per the basic steps in RR-1241), but they won't see the new Sessions Summary landing page until we are ready and have turned on the feature toggle 👍
=> RR-1241 - Make the new sessions summary page dependent on feature toggle as well as user role

server/routes/functionalSkillsResolver.test.ts, server/services/timelineService.test.ts, server/testsupport/createGoalDtoTestDataBuilder.ts, server/testsupport/inPrisonCourseTestDataBuilder.ts, server/testsupport/supportNeedsTestDataBuilder.ts, server/testsupport/updateGoalDtoTestDataBuilder.ts, server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.test.ts
This PR pushes the broom around and replaces a few more instances of `moment` with the corresponding `date-fns` functions.
(`moment` is an end-of-life / deprecated library that handles dates. `date-fns` is the modern replacement)
After this PR we'll be down to just 3 files that still use `moment`, but their use cases are a little more complex so I've opted to leave those out of this PR and we'll tackle them separately 👍
=> RR-491 - Replace more instances of moment with date-fns

package-lock.json, package.json, server/filters/formatDateFilter.test.ts, server/filters/formatDateFilter.ts
This is the final PR that replaces `moment` with `date-fns`
It's slightly more complex that the others (even though its still only a couple of files) because of how it's used.
The function in the file is a nunjucks UI filter that formats dates ... and we use it everywhere (most of our nunjucks UI templates render some kind of date field, so we need to format the date). This is typical of how it's used in a nunjucks filter:
```
<p class="moj-timeline__date">
<time datetime="{{ event.timestamp }}">{{ event.timestamp | formatDate('D MMMM YYYY') }}</time>
</p>
```
The problem is that the `moment` API is quite different to the `date-fns` API, especially how it handles null values (some dates are null), and also the date formatting tokens (ie: `D MMMM YYYY` in `moment` is `d MMMM yyyy` in …
=> RR-491 - Removed moment from formatDateFilter

server/@types/express/index.d.ts, server/routes/createGoal/createGoalsController.test.ts, server/routes/createGoal/createGoalsController.ts
This PR moves a form object `CreateGoalsForm` from being directly held on the session, to being held on the `PrisonerContext`
Whilst the `PrisonerContext` is also held on the session, it's a pattern we have been moving to as it's one object so is easier to tidy up/manage etc; plus the main benefit for us is that it is essentially a map keyed by the prisoners NOMS ID, which means our users can work on different prisoners at the same time in different tabs (which is something we know they do)
=> RR-906 - Moved CreateGoalsForm to prisonerContext

server/data/curiousClient.test.ts, server/data/curiousClient.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/routes/routerRequestHandlers/createEmptyInductionIfNotInSession.test.ts, server/routes/routerRequestHandlers/retrieveEducation.test.ts, server/routes/routerRequestHandlers/retrieveEducation.ts, server/routes/routerRequestHandlers/retrieveEducationForUpdate.test.ts, server/routes/routerRequestHandlers/retrieveEducationForUpdate.ts, server/services/curiousService.test.ts, server/services/curiousService.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts
This PR improves the way the UI makes GET requests to some API endpoints.
Some of the endpoints we call return a 404 when resources don't exist. For the most part this isn't an error, and the UI interprets and handles it as meaning no data. IE. the prisoner has no learner profile; or the prisoner has no eduction record. In respect of our UI it's not an error, it's an absence of data.
We have always handled these 404 responses by catching the exception from the REST client, and if the error status is a 404 then handle as "no data"
This is OK , but is messy:
* The REST client logs the error (at `error` level), which means our logs are full of "errors" that are not really errors
* We have to write code and tests to handle exceptions where the status code is 404
The REST client has an …
=> RR-1233 - Use ignore404 flag for Curious learnerProfile and PLP education

server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/routes/routerRequestHandlers/checkInductionDoesNotExist.test.ts, server/routes/routerRequestHandlers/checkInductionDoesNotExist.ts, server/routes/routerRequestHandlers/retrieveInduction.test.ts, server/routes/routerRequestHandlers/retrieveInduction.ts, server/routes/routerRequestHandlers/retrieveInductionIfNotInSession.test.ts, server/routes/routerRequestHandlers/retrieveInductionIfNotInSession.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/services/inductionService.test.ts, server/services/inductionService.ts
Similar to my last PR, this one improves the 404 handling when calling the APIs for retrieving the prisoner goals and prisoner induction.
=> RR-1233 - Use ignore404 flag for getting Goals and Induction

server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/services/educationAndWorkPlanService.test.ts, server/services/educationAndWorkPlanService.ts, server/services/timelineService.test.ts, server/services/timelineService.ts
Similar to my last PR, this one improves the 404 handling when calling the APIs for retrieving the prisoner Action Plan and prisoner Timeline.
=> RR-1233 - Use ignore404 flag for getting Action Plan and Timeline

server/middleware/roleBaseAccessControl.test.ts, server/middleware/roleBasedAccessControl.ts
PR to setup the correct permissions for the LWP_CONTRIBUTOR role based on the setting of the REVIEWS_ENABLED feature toggle.
With the toggle disabled (ie. current production) the Contributor role is the same as the Editor role (ie. prisoner list landing page, can view all details, can create and update inductions, can create and update goals, can create and updated education)
When the new KPI & Review features go live in April we will enable the REVIEWS_ENABLED feature toggle at which point the Contributor role will:
* have the prisoner list landing page
* be able to view all details
* be able to update inductions
* be able to create education
* be able to update education
They will not be able to see the Manager landing page, perform reviews, create inductions, create or update goals.
=> RR-1297 - Setup the correct permissions for the LWP_CONTRIBUTOR role

integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts, integration_tests/e2e/induction/createInduction.cy.ts, integration_tests/e2e/induction/updateInPrisonTrainingInterests.cy.ts, integration_tests/e2e/induction/updateInPrisonWorkInterests.cy.ts, server/routes/induction/common/checkYourAnswersController.ts, server/routes/induction/common/inPrisonTrainingController.ts, server/routes/induction/common/inPrisonTrainingView.ts, server/routes/induction/common/inPrisonWorkController.ts, server/routes/induction/common/inPrisonWorkView.ts, server/routes/induction/create/checkYourAnswersCreateController.ts, server/routes/induction/create/inPrisonTrainingCreateController.test.ts, server/routes/induction/create/inPrisonTrainingCreateController.ts, server/routes/induction/create/inPrisonWorkCreateController.test.ts, server/routes/induction/create/inPrisonWorkCreateController.ts, server/routes/induction/update/inPrisonTrainingUpdateController.test.ts, server/routes/induction/update/inPrisonTrainingUpdateController.ts, server/routes/induction/update/inPrisonWorkUpdateController.test.ts, server/routes/induction/update/inPrisonWorkUpdateController.ts, server/views/pages/induction/inPrisonTraining/index.njk, server/views/pages/induction/inPrisonWork/index.njk
This PR refactors the "back" links on the Induction "In Prison Work" and "In Prison Training" pages:
The designs for the Induction screens from our designers have a "< Back" link at the top of each form page. (GDS guidelines say that form/wizard style pages should have a "back" link to allow users to go back and correct data on previous screens)
To produce a true browser back navigation link that goes back to the previous page in the browser history you need to use the javascript `history` API. And making elements of the page dependant on JS is potentially a bit of a GDS no-no because you cannot guarantee that users have JS enabled .... 🙄  (yes, I know it's not a public website, and that our users are known users with known and managed PC and browser configurations .... but them's the …
=> RR-849 - Refactored back links on In Prison Work and In Prison Training pages

server/views/pages/overview/partials/timelineTab/_timelineEvent-ACTION_PLAN_CREATED.njk
Tiny PR to fix this problem on the timeline
The problem is caused because the rendering of the Action Plan Created timeline event in the UI looks at the event's contextual info fields, and specifically `COMPLETED_INDUCTION_ENTERED_ONLINE_BY` to decide whether to show the new or old layout ("new" layout is for use once we enable the feature toggle that collects the who dunnit and notes fields of the Induction)
This approach worked fine for the `ACTION_PLAN_CREATED_EVENT`, but there was a recent change in the UI where we needed to essentially use the latest of the `INDUCTION_CREATED_EVENT` or the `ACTION_PLAN_CREATED_EVENT`; and treat it as the `ACTION_PLAN_CREATED_EVENT`
In some cases, even whilst we have not gone live with the new Induction questions and process, the …
=> Fix Action Plan Created timeline event

server/routes/induction/create/checkYourAnswersCreateController.ts, server/routes/postInductionCreation/index.ts
Added a little bit more debug code to help diagnose `cannot read properties of undefined` error (RR-1300); but the debug code added earlier has already helped 👍 
It has pointed me at the other change in this PR - the correction to the `induction-created` route.
Basically, when the user presses the green "create induction" button on the Induction Check Your Answers page (which from the logs it looks like they are doing) we redirect to this `/induction-created` route.
The objective of this route is to look to see whether the prisoner already has any goals or not by retrieving their action plan - if they have goals (and by virtue of being on this route, also have an induction), then they have an Action Plan and we should redirect to the Overview page. Else, they do not have any goals (but do …
=> RR-1300 - Fixed induction-created route

integration_tests/mockApis/educationAndWorkPlanApi.ts, server/data/educationAndWorkPlanClient.test.ts, server/data/educationAndWorkPlanClient.ts, server/data/timelineApiFilterOptions.ts, server/services/timelineService.test.ts, server/services/timelineService.ts
This PR adds support to allow the client method that calls the Timeline API to be able to pass the relevant query string params to apply the filtering.
At the moment the params are all sent as `false`, with the filtering still being applied post-response. Subsequent PRs will start to wire this all up 👍
=> RR-1031 - Add filtering options on API client

assets/scss/application.scss, assets/scss/components/_timeline-event-filters.scss, server/@types/viewModels/index.d.ts, server/data/mappers/timelineMapper.test.ts, server/data/mappers/timelineMapper.ts, server/enums/timelineFilterTypeValue.ts, server/routes/overview/prepareTimelineForView.test.ts, server/routes/routerRequestHandlers/retrieveTimeline.test.ts, server/routes/routerRequestHandlers/retrieveTimeline.ts, server/services/timelineService.test.ts, server/services/timelineService.ts, server/testsupport/timelineTestDataBuilder.ts, server/views/pages/overview/partials/historyTab/_filterControls.njk, server/views/pages/overview/partials/historyTab/historyTabContents.njk
PR to add the UI controls for the timeline filtering, and to wire it all up into the service
Whilst the UI includes all options, at the moment it is only wired up for the simply boolean flags (ie. All or Inductions, Goals, Reviews or Prisoner Movements). The UI contains the checkboxes for Current Prison and Last 6 Months, but these are not wired up yet - that will be my next PR 👍 
https://github.com/user-attachments/assets/4c8f0fd9-2444-4f04-9524-f0510ac59c71
=> RR-1031 - Timeline filtering UI & pass to service

server/views/pages/overview/partials/overviewTab/_sessionHistorySummaryCard.njk, server/views/pages/overview/partials/overviewTab/_sessionHistorySummaryCard.test.ts
PR to pre-apply the Induction and Review event types to the History (timeline) link when linking from the Sessions History box on the Overview page.
https://github.com/user-attachments/assets/7725cab1-c20f-4ee0-b24e-a257ce73bd16
=> RR-1299 - Session History link to go to pre-filtered timeline

server/routes/induction/create/checkYourAnswersCreateController.ts, server/routes/routerRequestHandlers/createEmptyInductionIfNotInSession.ts, server/routes/routerRequestHandlers/removeFormDataFromSession.ts
PR to add more debug code to try to work out why users in prod sometimes get their InductionDto reset, which in turn is causing the `cannot read properties of undefined` errors.
Also took the opportunity to prefix debug statements previously added with "RR-1300" so that a) they are easier to query for in the logs, and b) will be easier to find in the code and remove as and when we have fixed this issue
=> RR-1300 - Added more debug code

integration_tests/e2e/overview/overview.cy.ts, server/views/components/actions-card/_reviewActions.njk, server/views/components/actions-card/_reviewActions.test.ts, server/views/components/actions-card/actionsCard.test.ts
PR to fix the Review actions in the Actions Bar, so that it says "No reviews due" when there are no reviews scheduled (currently it says nothing at all)
Currently the Actions Bar looks like this:
Actions Bar with fix:
=> RR-1352 - Fix review actions when there is no review scheduled

server/routes/induction/create/inPrisonTrainingCreateController.test.ts, server/routes/induction/create/inPrisonTrainingCreateController.ts, server/routes/induction/create/index.ts, server/views/pages/induction/checkYourAnswers/partials/_inductionCompletedBy.njk, server/views/pages/induction/checkYourAnswers/partials/_inductionNote.njk, server/views/pages/overview/partials/historyTab/historyTabContents.njk
This PR removes the REVIEWS_ENABLED feature toggle logic for the Induction routes flow (ie. to control whether to include the who dunnit and notes screens in the Induction flow); and also in the timeline (history) view to control whether to include the new filtering functionality
=> RR-1294 - Remove feature toggle logic from induction routes and timeline view

assets/scss/components/_actions-card.scss, integration_tests/e2e/overview/overview.cy.ts, server/views/components/actions-card/_reviewActions.njk, server/views/components/actions-card/_reviewActions.test.ts, server/views/components/actions-card/actionsCard.test.ts
PR to fix the problem where users can conduct reviews and review exemptions when the prisoner has no scheduled review.
If the prisoner has no scheduled review, we now no longer display the links to perform these actions:
=> RR-1402 - remove Review Actions when there is no scheduled review

server/views/components/actions-card/_reviewActions.njk, server/views/components/actions-card/_reviewActions.test.ts
PR to remove the Review Actions when the prisoner has had their last review
(whilst technically it works and we can support it, the business have decided that for consistency they do not want reviews being done/exempted when their is either no Review Scheduled at all (my last PR) or the prisoner has had their last review (this PR))
=> RR-1402 - remove Review Actions when prisoner has had their last review

server/views/components/sortable-table-header/template.njk
This PR fixes a bug that has cropped up since we updated to `moj-frontend-components` v5
From the `moj-frontend-components` library we use the `sortable-table` component on the prisoner-list screen ... but only in so much as the styling.
The functionality of the `sortable-table` component is delivered via client side javascript, enabled when the table has the attribute `data-module="moj-sortable-table"`. The applied sort is client side, and is across all of the `<tr>` elements in the DOM.
This works fine, but not in the case of a paginated table, because client side it only has 1 page of data in the DOM (so therefore it cannot sort the entire result set).
To get round this we have applied sorting (and filtering and pagination) server side, where server side it has access to the entire …
=> RR-1412 - Use SVG column sort direction icons

integration_tests/e2e/prisonerList/prisonerList.cy.ts, server/views/pages/prisonerList/partials/searchBox.njk
PR to fix the href of the "clear filters" link on the prisoner-list page so that it works for all user types
=> RR-1413 - Fix "clear filters" link for all user types

server/middleware/auditMiddleware.ts, server/routes/induction/exemption/exemption/confirmExemptionController.test.ts, server/routes/induction/exemption/exemption/confirmExemptionController.ts, server/routes/induction/exemption/exemption/exemptionReasonController.test.ts, server/routes/induction/exemption/exemption/exemptionReasonController.ts, server/routes/induction/exemption/exemption/index.ts, server/routes/induction/exemption/index.ts, server/routes/induction/exemption/removeExemption/confirmExemptionRemovalController.test.ts, server/routes/induction/exemption/removeExemption/confirmExemptionRemovalController.ts, server/routes/induction/exemption/removeExemption/index.ts
This PR injects the journeyId path element into the Induction Exemption routes.
At the moment the journeyId is not used, but we will soon be using it in all "journey" based screen flows to store the page-to-page form data (keyed by the journeyId)
We already have this pattern and approach established in the main Induction journey 👍 , this adds it to the Induction Exemption journey 👍
=> RR-1435 - Add journeyId to Induction Exemption routes

server/middleware/auditMiddleware.ts, server/routes/induction/create/index.ts, server/routes/induction/update/additionalTrainingUpdateController.test.ts, server/routes/induction/update/additionalTrainingUpdateController.ts, server/routes/induction/update/affectAbilityToWorkUpdateController.test.ts, server/routes/induction/update/affectAbilityToWorkUpdateController.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts, server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts, server/routes/induction/update/inPrisonTrainingUpdateController.test.ts, server/routes/induction/update/inPrisonTrainingUpdateController.ts, server/routes/induction/update/inPrisonWorkUpdateController.test.ts, server/routes/induction/update/inPrisonWorkUpdateController.ts, server/routes/induction/update/index.ts, server/routes/induction/update/personalInterestsUpdateController.test.ts, server/routes/induction/update/personalInterestsUpdateController.ts, server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts, server/routes/induction/update/previousWorkExperienceDetailUpdateController.ts, server/routes/induction/update/previousWorkExperienceTypesUpdateController.test.ts, server/routes/induction/update/previousWorkExperienceTypesUpdateController.ts, server/routes/induction/update/skillsUpdateController.test.ts, server/routes/induction/update/skillsUpdateController.ts, server/routes/induction/update/workInterestRolesUpdateController.test.ts, server/routes/induction/update/workInterestRolesUpdateController.ts, server/routes/induction/update/workInterestTypesUpdateController.test.ts, server/routes/induction/update/workInterestTypesUpdateController.ts, server/routes/induction/update/workedBeforeUpdateController.test.ts, server/routes/induction/update/workedBeforeUpdateController.ts
PR to insert the journeyId into the path of all routes in the Update Induction journey, much the same as we have already done in the Create Induction and Induction Exemptions journeys.
As with the other journeys, this only adds the journeyId into the route paths. It does not use the journeyId for storing/referencing any data in the journeyData yet. That will come in subsequent PRs
=> RR-1441 - Add the journeyId path parameter to all routes in Update Induction journey

server/data/index.ts, server/data/prisonRegisterClient.test.ts, server/data/prisonRegisterClient.ts, server/middleware/auditMiddleware.test.ts, server/routes/functionalSkills/functionalSkillsController.test.ts, server/routes/routerRequestHandlers/populateActiveCaseloadPrisonName.test.ts, server/services/curiousService.test.ts, server/services/educationAndWorkPlanService.test.ts, server/services/index.ts, server/services/prisonService.test.ts, server/services/prisonService.ts, server/services/reviewService.test.ts, server/services/timelineService.test.ts
PR to update `PrisonRegisterClient` to use the new `RestClient` superclass
=> RR-1884 - Update prison-register client to use new RestClient superclass

server/data/curiousClient.test.ts, server/data/curiousClient.ts, server/testsupport/curiousAssessmentsTestDataBuilder.ts
PR to add the Curious API client method to get all assessments for a prisoner (ie. the new Curious V2 endpoint)
This PR simply adds the client method. At the moment nothing is using it. That will be the focus of my next PRs.
=> RR-1884 - Add Curious client method to get All Assessments for a prisoner

integration_tests/e2e/overview/educationAndTrainingTab.cy.ts, integration_tests/pages/overview/EducationAndTrainingPage.ts, server/views/pages/functionalSkills/index.njk, server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.njk, server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.test.ts, server/views/pages/overview/partials/overviewTab/_educationAndTrainingSummaryCard.njk, server/views/pages/overview/partials/overviewTab/_educationAndTrainingSummaryCard.test.ts
This PR is part of the story that reads Functional Skills from Curious APIs as recorded in Curious 1 and Curious 2
Specifically this PR is about simplifying the empty states as thankfully the designs are a little simpler in this respect now.
Previously, when displaying Functional Skills, there were some pages (but not all! 🙄 ) that would ALWAYS display English and Maths, even if the prisoner had not taken those assessments. IE. they were "special" empty states - rather than simply saying "no functional skills recorded", we would render "English - not recorded in Curious" and "Maths - not recorded in Curious"
This odd empty state logic was slightly complicated, not least because it wasnt consistent on all screens! Some screens did it, some didnt!
The good news is that the new designs now …
=> RR-1849 - Simplify empty states for Functional Skills

integration_tests/e2e/induction/createInductionHandleApiError.cy.ts, integration_tests/mockApis/educationAndWorkPlanApi.ts, integration_tests/pages/page.ts, server/middleware/errorMessageMiddleware.ts, server/routes/induction/create/checkYourAnswersCreateController.test.ts, server/routes/induction/create/checkYourAnswersCreateController.ts
PR to improve API error handling when submitting Induction Check Your Answers. This prevents our basic/generic 500 error page being displayed and keeps the user in the journey to be able to try again.
=> RR-1925 - Improve API error handling when submitting Induction Check Your Answers
