- integration_tests/e2e/goal/addNote.cy.ts
- integration_tests/pages/goal/AddNotePage.ts
- server/routes/index.ts
- server/views/pages/goal/add-note/index.njk
> RR-02 Initial basic Add Note page

- integration_tests/e2e/goal/createGoal.cy.ts
- integration_tests/pages/goal/CreateGoalPage.ts
- integration_tests/pages/page.ts
- server/filters/findErrorFilter.ts
- server/routes/createGoal/createGoalController.ts
- server/routes/createGoal/createGoalFormValidator.test.ts
- server/routes/createGoal/createGoalFormValidator.ts
- server/routes/errorFormater.test.ts
- server/routes/errorFormatter.ts
- server/routes/parseDate.test.ts
- server/routes/parseDate.ts
- server/utils/nunjucksSetup.ts
- server/validators/goalReviewDateValidator.test.ts
- server/validators/goalReviewDateValidator.ts
- server/validators/goalTitleValidator.test.ts
- server/validators/goalTitleValidator.ts
- server/views/pages/goal/add-note/index.njk
- server/views/pages/goal/add-step/index.njk
- server/views/pages/goal/create/index.njk
This PR adds validation on the submission of the first Create Goal screen; errors display; and an integration test
> RR-2 - Added validation for Create Goal

- server/routes/createGoal/addStepFormValidator.test.ts
- server/routes/createGoal/addStepFormValidator.ts
- server/routes/createGoal/createGoalFormValidator.test.ts
- server/routes/createGoal/createGoalFormValidator.ts
- server/views/pages/goal/add-step/index.njk
- server/views/pages/goal/create/index.njk
> RR-2 - date field error styling

- integration_tests/e2e/goal/addStep.cy.ts
- integration_tests/e2e/goal/createGoal.cy.ts
- integration_tests/pages/goal/AddStepPage.ts
- server/@types/forms/index.d.ts
- server/routes/createGoal/addStepFormValidator.test.ts
- server/routes/createGoal/createGoalController.test.ts
- server/routes/createGoal/createGoalController.ts
- server/views/pages/goal/add-step/index.njk
This PR adds the basic screen flow and processing to support "Add another step"
All this PR does is address the screen flow - it does not attempt to do anything with the submitted step
> RR-2 - Basic screen routing to support adding other steps

- integration_tests/e2e/goal/addNote.cy.ts
- server/routes/createGoal/index.ts
- server/routes/createGoal/routerRequestHandlers.test.ts
- server/routes/createGoal/routerRequestHandlers.ts
This PR ensures that you cannot navigate to Add Note out of sequence by checking there is an array of AddStepForms in the session and that the array contains at least 1 element
> RR-2 - Session form handling to ensure at least 1 step is added

- server/routes/index.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/views/pages/overview/index.njk
- server/views/pages/overview/partials/navigation.njk
- server/views/pages/overview/partials/overviewTabContents.njk
Very much a basic WIP, but this PR defines the route, controller and basic view for the overview page.
It is based on / modelled on what CIAG Inductions are doing in respect of the tabbed interface and how the views work in this respect (each tab content is a partial)
There is still work to do such as retrieving the prisoner summary to put their name etc on the view; and also adding the Add A Goal button
But as a bare bones skeleton this is a good starter for 10 🤞
> RR-69 - Add the initial basic route, controller and view

- assets/scss/application-ie8.scss
- assets/scss/application.scss
- assets/scss/components/_overview-page.scss
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/views/pages/overview/partials/navigation.njk
- server/views/pages/overview/partials/overviewTabContents.njk
This PR adds the 'Add a goal' button to the overview page
> RR-69 - Add the 'Add a goal' button

- server/routes/overview/index.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/views/pages/overview/index.njk
This PR adds the prisoner search integration to the Overview page and renders the summary field in the prisonerBanner
(the integration has been copied from the Create Goals controller - we will remove it from there in the next PR)
> RR-69 - Added initial prisoner search integration

- cypress.config.ts
- integration_tests/mockApis/curiousApi.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/mockApis/prisonerSearchApi.ts
This PR defines the wiremock stubs for the Curious API in respect of prisoner neuro divergence data
> RR-107 - Initial wiremock stubs for neuro divergence data from Curious API

- server/routes/overview/educationAndTrainingView.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.ts
- server/views/pages/overview/index.njk
- server/views/pages/overview/partials/educationAndTrainingTabContents.njk
- server/views/pages/overview/partials/navigation.njk
This PR creates the basic routing and controller method and very basic view for the Education & Training tab
> RR-116 - Route, controller, and basic view for Education & Training tab

- server/@types/curiousApiClient/index.d.ts
- server/@types/viewModels/index.d.ts
- server/routes/overview/mappers/functionalSkillsMapper.test.ts
- server/routes/overview/mappers/functionalSkillsMapper.ts
- server/services/curiousService.ts
This PR adds the basic service method and mapper to get functional skills
> RR-116 - Service method and mapper

- feature.env
- integration_tests/e2e/overview/educationAndTrainingTab.cy.ts
- integration_tests/mockApis/curiousApi.ts
- integration_tests/pages/overview/OverviewPage.ts
- package-lock.json
- package.json
- server/routes/overview/educationAndTrainingView.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/routes/overview/supportNeedsView.ts
- server/services/curiousService.test.ts
- server/services/curiousService.ts
- server/testsupport/learnerProfileTestDataBuilder.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/overview/partials/educationAndTrainingTabContents.njk
- server/views/pages/overview/partials/educationAndTrainingTabContents.test.ts
This PR adds the service call to the controller method in order to retrieve the functional skills from Curious
It also includes error handling to catch errors from Curious and display a temp error message
And I have added unit tests for the logic in the view; and an integration test for the new tab on the Overview page
> RR-116 - Wired in service; added curious unavailable message; added tests

- integration_tests/e2e/overview/supportNeedsTab.cy.ts
- integration_tests/pages/overview/OverviewPage.ts
- server/views/pages/overview/partials/supportNeedsTabContents.njk
- server/views/pages/overview/partials/supportNeedsTabContents.test.ts
Some additional unit and integration tests for the Support Needs tab.
> RR-132 - Additional tests

- server/views/pages/index.njk
This PR adds a prisoner to our static prisoner list page. This prisoner is know to exist in NOMIS/prisoner-search `dev`; but also is known to have records in Curious `dev`, which should hopefully help our team testing the Curious related tickets
(the other prisoners in our list dont have Curious records!)
> RR-116 - Added prisoner to prisoner list page who is known to have curious records

- server/views/pages/overview/partials/supportNeedsTabContents.njk
> fix a typo on support text

- integration_tests/e2e/goal/addNote.cy.ts
- integration_tests/e2e/goal/addStep.cy.ts
- integration_tests/e2e/goal/createGoal.cy.ts
- integration_tests/e2e/goal/review.cy.ts
- integration_tests/e2e/overview/educationAndTrainingTab.cy.ts
- integration_tests/e2e/overview/overview.cy.ts
- integration_tests/e2e/overview/supportNeedsTab.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/mockData/actionPlanByPrisonNumberData.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/views/pages/overview/partials/overviewTabContents.njk
This PR completes the work for retrieving a prisoner's Action Plan and putting it in the overview screen's "view data", but stops short of displaying it on the overview screen, because we don't yet have an agreed/updated design (sub-task https://dsdmoj.atlassian.net/browse/RR-162).
> RR-160 - Retrieve Action Plan and place in overview screen "view data"

- assets/scss/application.scss
- assets/scss/components/_summary-card.scss
- integration_tests/e2e/overview/overview.cy.ts
- integration_tests/pages/overview/OverviewPage.ts
- server/views/pages/overview/partials/overviewTabContents.njk
- Display functional skills data on the overview page sidebar
> add functional skills sidebar on the overview page

- server/routes/updateGoal/updateGoalFormValidator.test.ts
- server/routes/updateGoal/updateGoalFormValidator.ts
- server/validators/goalStatusValidator.test.ts
- server/validators/goalStatusValidator.ts
- server/validators/stepStatusValidator.test.ts
- server/validators/stepStatusValidator.ts
- server/validators/stepTargetDateRangeValidator.test.ts
- server/validators/stepTargetDateRangeValidator.ts
Validator functions to validate the `UpdateGoalForm`
Also improved existing `stepTargetDateRangeValidator` so that it knows about and validates against the supported set of target date ranges
> RR-3 - Validator functions and tests

- server/@types/express/index.d.ts
- server/routes/updateGoal/index.ts
- server/routes/updateGoal/updateGoalController.test.ts
- server/routes/updateGoal/updateGoalController.ts
- server/routes/updateGoal/updateGoalFormValidator.test.ts
- server/routes/updateGoal/updateGoalFormValidator.ts
- server/views/pages/goal/update/index.njk
> RR-3 - Form submission, call validator, re-render with errors

- server/@types/dto/index.d.ts
- server/data/mappers/createGoalMapper.test.ts
- server/data/mappers/updateGoalMapper.test.ts
- server/data/mappers/updateGoalMapper.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.test.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.ts
- server/routes/updateGoal/updateGoalController.test.ts
- server/routes/updateGoal/updateGoalController.ts
- server/services/educationAndWorkPlanService.test.ts
- server/services/educationAndWorkPlanService.ts
- server/testsupport/updateGoalDtoTestDataBuilder.ts
- server/testsupport/updateGoalRequestTestDataBuilder.ts
This PR adds a couple of DTO classes and mappers, implements the service method, then wires the service method call into the controller method.
All in this provides the end to end express code to Update A Goal
> RR-3 - Call API to update Goal

- integration_tests/e2e/goal/updateGoal.cy.ts
- integration_tests/e2e/overview/overview.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/pages/goal/UpdateGoalPage.ts
- integration_tests/pages/overview/OverviewPage.ts
- server/views/pages/goal/update/index.njk
- server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
Cypress doesn't seem to like the `#steps[0]title` format for selecting elements so I've had to use `data-qa` attributes
> add tests for the update a goal pages

- integration_tests/e2e/goal/updateGoal.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/pages/goal/UpdateGoalPage.ts
Cypress tests for adding a new Step as part of Updating a Goal
> RR-32 - Cypress tests

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
This PR enables the "Edit Goals" feature toggle as part of the helm deployment. This will enable the team to start testing RR-3 and related stories
> RR-3 - Enable feature toggle

- server/errorHandler.test.ts
- server/errorHandler.ts
- server/views/pages/404.njk
https://dsdmoj.atlassian.net/browse/RR-220
> 404 error handling with a 404 page template and content

- server/views/pages/overview/partials/overviewTabContents.njk
https://dsdmoj.atlassian.net/browse/RR-218
> move the functional skills assesment date below the skill title and grade

- integration_tests/e2e/goal/reviewUpdateGoal.cy.ts
- integration_tests/e2e/goal/updateGoal.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/pages/error500.ts
- server/routes/updateGoal/updateGoalController.test.ts
- server/routes/updateGoal/updateGoalController.ts
- server/views/pages/error.njk
Render 500 page when API calls to update a goal fail
> RR-188 - Render 500 page when API calls to update a goal fail

- server/routes/overview/index.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/workAndInterestsView.ts
- server/views/pages/overview/index.njk
- server/views/pages/overview/partials/workAndInterestsTabContents.njk
This PR adds the basic route, controller method and view; for the Work And Interests tab.
The view is very basic/empty at the moment because:
a) I've not wired in the service call etc, so there is no data at the moment
b) I want to hand the main view stuff to Adam as he will do a better job than me 👍
> RR-115 - Basic route, controller and view

- server/@types/viewModels/index.d.ts
- server/data/mappers/prePrisonQualificationsMapper.test.ts
- server/data/mappers/prePrisonQualificationsMapper.ts
- server/routes/overview/educationAndTrainingView.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/services/ciagInductionService.test.ts
- server/services/ciagInductionService.ts
- server/testsupport/ciagInductionTestDataBuilder.ts
This PR maps the relevant `qualificationsAndTraining` data from the CIAG profile into our `PrePrisonQualifications` view model.
The view template and integration tests will be added in a subsequent PR.
> RR-141 - Retrieve pre-prison qualifications from CIAG

- server/@types/viewModels/index.d.ts
- server/data/mappers/workAndInterestMapper.test.ts
- server/data/mappers/workAndInterestMapper.ts
- server/testsupport/ciagInductionTestDataBuilder.ts
This PR defines our SkillsAndInterests view model object and maps into it from the CIAG Induction data
> RR-115 - Define our SkillsAndInterests view model object

- server/@types/viewModels/index.d.ts
- server/filters/formatAbilityToWorkConstraintFilter.test.ts
- server/filters/formatAbilityToWorkConstraintFilter.ts
- server/filters/formatGoalStatusValue.ts
- server/filters/formatJobTypeFilter.test.ts
- server/filters/formatJobTypeFilter.ts
- server/filters/formatStepStatusValue.ts
- server/filters/formatTargetDateRangeValue.ts
- server/filters/formatYesNoFilter.test.ts
- server/filters/formatYesNoFilter.ts
- server/utils/nunjucksSetup.ts
There are a couple of other filters we will need for CIAG enums, but I have some questions about differences in the enums between their UI and their API
> RR-115 - Added a couple of the filters we will need to display the CIAG enum values

- server/views/pages/index.njk
- server/views/pages/overview/partials/workAndInterestsTabContents.njk
This PR adds 4 prisoners to our dummy/stub prisoner list page, that are the prisoners that Gary has setup CIAG Induction data for.
> RR-115 - Added test prisoners that have CIAG Induction data

- integration_tests/e2e/overview/workAndInterestsTab.cy.ts
- integration_tests/mockApis/ciagInducationApi.ts
- integration_tests/pages/overview/OverviewPage.ts
- server/views/pages/overview/partials/workAndInterestsTabContents.njk
Add CIAG profile stub and basic tests for work and interests page
https://dsdmoj.atlassian.net/browse/RR-244
> RR-244 add CIAG profile stub and basic tests for work and interests page

- server/views/pages/overview/partials/workAndInterestsTabContents.njk
Hide change your answer link on print stylesheets.
https://dsdmoj.atlassian.net/browse/RR-212
> RR-212 - Hide the change links print

- server/views/partials/prisonerBanner.njk
Reword release date label in prisoner summary bar
https://dsdmoj.atlassian.net/browse/RR-283
> RR-283 reword release date label in prisoner summary bar

- server/views/pages/functionalSkills/index.njk
- server/views/pages/goal/add-note/index.njk
- server/views/pages/goal/add-step/index.njk
- server/views/pages/goal/create/index.njk
- server/views/pages/goal/review/index.njk
- server/views/pages/goal/update/index.njk
- server/views/pages/goal/update/review.njk
- server/views/pages/overview/index.njk
Update the Overview page title and relevant breadcrumbs that link to the Overview page.
https://dsdmoj.atlassian.net/browse/RR-291
> RR-291 update the overview page title and relevant breadcrumbs

- server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.njk
Update the grade or outcome table heading on prison qualifications table
https://dsdmoj.atlassian.net/browse/RR-292
> RR-292 update the grade or outcome table heading on prison qualifications

- server/views/pages/goal/update/index.njk
Use the correct legend size modifier on the the update a goal step legends
https://dsdmoj.atlassian.net/browse/RR-290
> RR-290 use the correct legend size modifier

- server/views/pages/goal/update/index.njk
Adjust the sizing of the Goal `textarea`s to accomodate character limits
https://dsdmoj.atlassian.net/browse/RR-286
**500 characters for Goal description**
**200 characters Step title/description**
> RR-286 adjust the sizing of the Goal textareas to accomodate character limits

- server/@types/frontendComponentApi/index.d.ts
- server/@types/frontendComponentApiClient/index.d.ts
- server/@types/viewModels/index.d.ts
- server/data/frontendComponentApiClient.test.ts
- server/data/frontendComponentApiClient.ts
- server/data/mappers/frontendComponentMapper.test.ts
- server/data/mappers/frontendComponentMapper.ts
- server/middleware/fetchFrontendComponentMiddleware.ts
- server/services/frontendComponentService.test.ts
- server/services/frontendComponentService.ts
- server/testsupport/frontendComponentTestDataBuilder.ts
- server/views/partials/layout.njk
This PR adds error handling and a mapper to the frontendComponentsService, consistent with our other services
> RR-143 - Improve error handling; patterns consistent with our other services

- server/@types/viewModels/index.d.ts
- server/filters/fallbackMessageFilter.test.ts
- server/filters/fallbackMessageFilter.ts
- server/routes/overview/mappers/prisonerSupportNeedsMapper.test.ts
- server/routes/overview/mappers/prisonerSupportNeedsMapper.ts
- server/services/curiousService.test.ts
- server/testsupport/supportNeedsTestDataBuilder.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/overview/partials/supportNeedsTabContents.njk
- server/views/pages/overview/partials/supportNeedsTabContents.test.ts
This PR restructures the LDD & Health needs panel on the Support Needs page as per the new design (note - this PR only address the LDD & Health needs panel - the next PR will do the same for Neurodiversity).
> RR-315 - Refactor LDD & Health Needs panel based on new design

- server/views/autherror.njk
Update 403 error screen content as per the content doc
https://dsdmoj.atlassian.net/browse/RR-287
> RR-287 update 403 error screen content

- server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.njk
Update In-prison qualification table header text
https://dsdmoj.atlassian.net/browse/RR-298
> RR-298 update in prison qualifications table header text

- server/routes/createGoal/createGoalController.test.ts
- server/routes/createGoal/createGoalController.ts
- server/routes/createGoal/reviewView.ts
- server/views/pages/goal/review/index.njk
Display multiple goals on the review goal screen
https://dsdmoj.atlassian.net/browse/RR-323
> RR-323 display multiple goals on the review goal screen

- helm_deploy/values-dev.yaml
Reverted frontend components URL now that testing of fallbacks is complete
> RR-143 - Reverted frontend components URL now that testing of fallbacks is complete

- integration_tests/e2e/goal/review.cy.ts
- integration_tests/pages/goal/ReviewPage.ts
- server/routes/createGoal/reviewView.ts
Cypress test add scenario for creating 2 goals as part of journey
https://dsdmoj.atlassian.net/browse/RR-328
> RR-328 Cypress test add scenario for creating 2 goals as part of journey

- server/views/pages/overview/partials/supportNeedsTabContents.njk
Empty state messages for Curious on the Support needs tabs
If data does exist, but some fields are empty
If no data at all from the API
> RR-330 add empty state message for Curious if no data return from API

- server/@types/dto/index.d.ts
- server/@types/forms/index.d.ts
Add `targetCompletionDate` field (optional) to `CreateGoalForm` and `CreateGoalDto`
https://dsdmoj.atlassian.net/browse/RR-366
> RR-366 add targetCompletionDate to dtos

- server/views/pages/overview/partials/overviewTabActionPlanColumn.njk
Add goal target dates on the overview screen.
https://dsdmoj.atlassian.net/browse/RR-337
> RR-337 add goal target dates on the overview screen

- server/views/pages/404.njk
- server/views/pages/error.njk
- server/views/pages/functionalSkills/index.njk
- server/views/pages/goal/add-note/index.njk
- server/views/pages/goal/add-step/index.njk
- server/views/pages/goal/create/index.njk
- server/views/pages/goal/review/index.njk
- server/views/pages/goal/update/index.njk
- server/views/pages/goal/update/review.njk
- server/views/pages/index.njk
- server/views/pages/overview/index.njk
- server/views/partials/layout.njk
Use the correct page title format
https://dsdmoj.atlassian.net/browse/RR-386
> RR-386 use the correct page title format

- server/views/pages/goal/update/index.njk
Use the correct button label on update screen
https://dsdmoj.atlassian.net/browse/RR-393
> RR-393 use the correct button label on update screen

- server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.njk
- server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.test.ts
- server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.njk
- server/views/pages/overview/partials/educationAndTrainingInPrisonQualifications.test.ts
Update content for CIAG API being unavailable on the Education and Training tab
https://dsdmoj.atlassian.net/browse/RR-354
> RR-354 update content for CIAG API being unavailable

- integration_tests/e2e/functionalSkills/functionalSkills.cy.ts
- integration_tests/pages/functionalSkills/FunctionalSkillsPage.ts
- server/views/pages/functionalSkills/index.njk
Update the Curious unavailable content on the functional skills page.
This page didn't have any tests for the API being down.
https://dsdmoj.atlassian.net/browse/RR-357
> RR-357 update the Curious unavailable content on the functional skills page

- server/views/pages/overview/partials/educationAndTrainingOtherQualifications.njk
- server/views/pages/overview/partials/educationAndTrainingOtherQualifications.test.ts
Update content for when the CIAG API is down
https://dsdmoj.atlassian.net/browse/RR-355
> RR-355 update content for the CIAG API being down

- integration_tests/pages/overview/OverviewPage.ts
- server/views/pages/overview/partials/workAndInterestsTabContents.njk
Update content for the CIAG API being down
https://dsdmoj.atlassian.net/browse/RR-356
> RR-356 update content for the CIAG API being down

- server/views/pages/overview/partials/supportNeedsTabContents.njk
Use the correct colour on the recorded on date text in the Neurodiversity section
https://dsdmoj.atlassian.net/browse/RR-402
> RR-402 use the correct colour on the recorded on date text

- server/views/pages/goal/update/review.njk
Align the step status to the right of the table column
https://dsdmoj.atlassian.net/browse/RR-416
> RR-416 align the step status to the right of the table column

- server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.njk
- server/views/pages/overview/partials/educationAndTrainingFunctionalSkills.test.ts
Content changes for the functional skills summary card on the Education and Training tab
https://dsdmoj.atlassian.net/browse/RR-412
> RR-412 content changes for the functional skills summary card

- server/views/pages/overview/partials/workAndInterestsTabContents.njk
Hide prison staff name on print for work and interests
https://dsdmoj.atlassian.net/browse/RR-420
Screenshot of print preview:
> RR-420 hide prison staff name on print for work and interests

- assets/scss/components/_summary-card.scss
- server/views/pages/overview/partials/functionalSkillsSidebar.njk
- server/views/pages/overview/partials/qualificationsAndAchievementsSidebar.njk
Update the styling of the qualifications sidebar
(Don't ask me why its green)
https://dsdmoj.atlassian.net/browse/RR-364
> RR-364 update the styling of the qualifications sidebar

- server/data/mappers/prisonerSearchSummaryMapper.test.ts
- server/data/mappers/prisonerSearchSummaryMapper.ts
- server/routes/routerRequestHandlers.test.ts
- server/routes/routerRequestHandlers.ts
- server/services/prisonerListService.test.ts
- server/services/prisonerListService.ts
- server/services/prisonerSearchService.test.ts
- server/services/prisonerSearchService.ts
This PR fleshes out the `PrisonerListService` class by introducing the method `getPrisonerSearchSummariesForPrisonId`
It also does a little tidying in a closely related class
> RR-395 - Fleshed out `PrisonerListService` and associated classes

- assets/scss/components/_summary-card.scss
- server/views/pages/overview/partials/educationAndTrainingTab/_otherQualifications_inductionShortQuestionSet.njk
Create the UI template for the short question set, with placeholders for the data to populated.
Values that need to be populated with data are indicated by `{# TODO #}` and `[Subject value]`
https://dsdmoj.atlassian.net/browse/RR-441
> RR-441 create the UI template for the short question set

- server/filters/formatQualificationLevelFilter.test.ts
- server/filters/formatQualificationLevelFilter.ts
- server/routes/overview/overviewController.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_inductionShortQuestionSet.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_otherQualifications.njk
Populate the UI with the data for the short route answers
https://dsdmoj.atlassian.net/browse/RR-441
`A8335DY` 
```
{
"problemRetrievingData": false,
"inductionQuestionSet": "SHORT_QUESTION_SET",
"data": {
"updatedBy": "KROONEY_GEN",
"updatedAt": "2023-10-19T10:39:30.080Z",
"shortQuestionSetAnswers": {
"additionalTraining": [
"HGV_LICENCE"
],
"otherAdditionalTraining": "",
"educationalQualifications": []
}
}
}
```
`A8408DY`
```
{
"problemRetrievingData": false,
"inductionQuestionSet": "SHORT_QUESTION_SET",
"data": {
"updatedBy": "KROONEY_GEN",
"updatedAt": "2023-10-19T10:39:30.080Z",
"shortQuestionSetAnswers": {
"additionalTraining": [
"HGV_LICENCE"
],
"otherAdditionalTraining": "",
"educationalQualifications": []
}
}
}
```
> RR-441 populate UI with data and remove temporary code

- server/filters/formatInPrisonEducationFilter.test.ts
- server/filters/formatInPrisonEducationFilter.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
Education and training tab short route answers for "Training and eduction interests in prison"
This is just for the UI, which currently is commented out, the next PR will include the correct data
https://dsdmoj.atlassian.net/browse/RR-441
> Rr 441 education and training tab short route answers

- server/@types/viewModels/index.d.ts
- server/data/mappers/educationAndTrainingMapper.test.ts
- server/data/mappers/educationAndTrainingMapper.ts
- server/testsupport/ciagInductionTestDataBuilder.ts
- server/testsupport/educationAndTrainingTestDataBuilder.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
- server/views/pages/overview/partials/educationAndTrainingTab/educationAndTrainingTabContents.njk
Populate the training and education summary card with data
https://dsdmoj.atlassian.net/browse/RR-441
> RR-441 populate the training and education interests data

- server/data/mappers/enumComparator.test.ts
- server/data/mappers/enumComparator.ts
Create a generic enum comparator function to sort various ENUMs from different parts of the service
> Note: This comparator function is not currently used anywhere
https://dsdmoj.atlassian.net/browse/RR-463
> RR-463 create a generic enum comparator function to sort

- server/views/pages/functionalSkills/index.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.test.ts
- server/views/pages/overview/partials/overviewTab/functionalSkillsSidebar.njk
- server/views/pages/overview/partials/overviewTab/functionalSkillsSidebar.test.ts
Corrected wording when prisoner has no Functional Skills in curious (again !!! 😢 )
> RR-464 - Corrected wording when prisoner has no Functional Skills in curious

- server/routes/prisonerList/prisonerListController.test.ts
- server/routes/prisonerList/prisonerListView.ts
Persist the query parameters on the pagination items href values (`searchTerm` and `statusFilter`)
> RR-438 persist the query parameters on the pagination items href value

- server/routes/prisonerList/prisonerListController.ts
- server/routes/prisonerList/prisonerListView.ts
Add logic for setting the current page number
Fix issue with the Previous link not showing on the page 2 of results
Persist the query parameters on the 'Next' and 'Previous' links in the pagination
> RR-438 add logic for setting the current page number

- server/routes/prisonerList/prisonerListView.ts
Fix issue with pagination not showing the correct amount of pages on the first 10 pages and last 10 pages
Matches CIAG.
> RR-438 fix issue with pagination not showing the correct amount of pages

- .circleci/config.yml
- helm_deploy/hmpps-education-and-work-plan-ui/Chart.yaml
- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- helm_deploy/values-dev.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
2 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons,private_prisons`
- The size of the allowlist defined in this file will change: `45 => 2 (43 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- sodexo1,80.86.46.16/32
- sodexo2,80.86.46.17/32
- sodexo3,80.86.46.18/32
- …
> Migrating project to use groups in allowlist

- server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk
Content change Highest level of education -> Highest level of education before prison
https://dsdmoj.atlassian.net/browse/RR-471
> RR-471 highest level of education wording improvements

- server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
Content improvements for hoping to work on release
https://dsdmoj.atlassian.net/browse/RR-472
> RR-472 content improvements for hoping to work on release

- integration_tests/e2e/prisonerList/prisonerList.cy.ts
- integration_tests/pages/prisonerList/PrisonerListPage.ts
Cypress tests for the pagination controls
https://dsdmoj.atlassian.net/browse/RR-468
> RR-468 cypress tests for the pagination controls

- server/config.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
This PR removes GA/GTM in preparation for adding App insights instead (adding App Insights code will be my next PR)
> RR-484 - Remove GA/GTM

- README.md
- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- server/config.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/timelineView.ts
- server/views/pages/overview/index.njk
- server/views/pages/overview/partials/navigation.njk
- server/views/pages/overview/partials/timelineTab/timelineTabContents.njk
- server/views/partials/layout.njk
Initial Timeline views and tab on the Overview screen with a feature toggle to disable the feature until its fully developed
> RR-126 initial timeline views with feature toggle

- server/views/pages/overview/partials/navigation.njk
Use the correct feature toggle name for the Timeline tab
🤦🏻
> RR-126 use the correct feature toggle name for the Timeline tab

- server/filters/formatTimelineEvent.test.ts
- server/filters/formatTimelineEvent.ts
- server/routes/overview/overviewController.test.ts
- server/services/timelineService.test.ts
- server/services/timelineService.ts
- server/views/pages/overview/partials/timelineTab/timelineTabContents.njk
Display "Goal updated" event on the Timeline UI.
Also add some tests for the Timeline view and Timeline service.
https://dsdmoj.atlassian.net/browse/RR-475
> RR-475 display goal updated event on the timeline

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Enable the Timeline feature toggle in the dev environment
> RR-126 enable the Timeline feature toggle in the dev environment

- integration_tests/e2e/goal/addStep.cy.ts
- integration_tests/e2e/goal/review.cy.ts
- integration_tests/pages/goal/AddStepPage.ts
- integration_tests/pages/goal/CreateGoalPage.ts
- server/routes/createGoal/createGoalController.test.ts
- server/routes/createGoal/createGoalController.ts
This PR updates `createGoalController` to start making use of the goal and step indexes that are in the route paths
> RR-514 - Logic to use the goal and step indexes

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
PR to switch over to the PLP version of the CIAG API in all envs.
> RR-516 - Switch over to PLP version of CIAG API

- integration_tests/e2e/goal/createAndEditGoal.cy.ts
- integration_tests/pages/goal/ReviewPage.ts
- server/routes/createGoal/createGoalController.originalBehaviour.test.ts
- server/routes/createGoal/createGoalController.originalBehaviour.ts
- server/routes/createGoal/createGoalController.test.ts
- server/routes/createGoal/createGoalController.ts
- server/routes/createGoal/createGoalView.ts
- server/views/pages/goal/create/index.njk
- server/views/pages/goal/review/index.njk
Functionality to change goal description and target date
https://dsdmoj.atlassian.net/browse/RR-500
https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/assets/11615501/433c9637-01f5-4e56-bbe6-d4f361539b65
> RR-500 functionality to change goal description and target date

- server/routes/createGoal/mappers/createGoalFormToCreateGoalDtoMapper.test.ts
- server/routes/createGoal/mappers/createGoalFormToCreateGoalDtoMapper.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.test.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.ts
- server/testsupport/createGoalFormTestDataBuilder.ts
- server/testsupport/updateGoalFormTestDataBuilder.ts
Fix issue with `momentjs` daylight saving time dates
The fix is `moment` to `moment.utc`
https://dsdmoj.atlassian.net/browse/RR-532
> RR-532 fix issue with momentjs daylight saving time

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Add the farsight-devs GH team to the modsec rules config so we can hopefully see the errors in the logs
> RR-538 - Add the farsight-devs GH team to the modsec rules config

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Enable the timeline across all environments
https://dsdmoj.atlassian.net/browse/RR-203
> RR-203 enable the timeline across all environments

- helm_deploy/values-dev.yaml
- server/views/pages/overview/partials/educationAndTrainingTab/educationAndTrainingTabContents.njk
- server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
Fix broken links to create an induction in the CIAG service, also use `https` on the dev CIAG induction URL
https://dsdmoj.atlassian.net/browse/RR-549
> RR-549 fix broken links to create an induction in the CIAG service

- helm_deploy/values-dev.yaml
This PR handles modsec false positives for rule 942440 **in dev only**. I am not proposing this goes anywhere near `prod` this close to the code freeze, but we can test it in `dev` in the run up to Xmas and NY
For reference, these are the relevant modsec logs that we are trying to mitigate with this change:
```
{
"message": "SQL Comment Sequence Detected",
"details": {
"match": "Matched \"Operator `Rx' with parameter `(?:/\\*!?|\\*/|[';]--|--[\\s\\r\\n\\v\\f]|--[^-]*?-|[^&-]#.*?[\\s\\r\\n\\v\\f]|;?\\\\x00)' against variable `REQUEST_COOKIES:connect.sid' (Value: `s%3Ad93u8slJqP--lEjvuXCKRAz2AXWIXVR-.kIFH5gtR3R51gmWcWWlpx6KYYbtnvjFMb1HwF8g4U1s' )",
"reference": "o12,22v1120,80t:urlDecodeUni",
"ruleId": "942440",
"file": "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-S …
```
> RR-538 - Handle modsec false positives for rule 942440

- integration_tests/e2e/goal/addAndEditStep.cy.ts
- integration_tests/pages/goal/ReviewPage.ts
- server/routes/createGoal/createGoalController.test.ts
- server/routes/createGoal/createGoalController.ts
- server/testsupport/addStepFormTestDataBuilder.ts
- server/views/pages/goal/add-step/index.njk
Add another step whilst editing a goal
https://dsdmoj.atlassian.net/browse/RR-506
https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/assets/11615501/6e890b8b-1b6b-4334-b1e0-28bff9967f32
> RR-506 Add another step whilst editing a goal

- server/views/pages/overview/partials/overviewTab/overviewTabPreInduction.njk
This PR updates the pre-induction Overview content based on whether the prisoner has goals or not.
> RR-545 - Update pre-induction Overview content based on whether the prisoner has goals or not

- server/routes/createGoal/createGoalController.ts
Fix bug for checking for the step index on step view
Bug comment: https://dsdmoj.atlassian.net/browse/RR-501?focusedCommentId=356513
> RR-501 fix bug for checking for the step index on step view

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Enable new create/edit goal routes across all environments
https://dsdmoj.atlassian.net/browse/RR-558
> RR-558 enable new create/edit goal routes across all environments

- server/routes/overview/index.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/services/index.ts
- server/services/prisonService.test.ts
- server/services/prisonService.ts
- server/services/timelineService.test.ts
- server/services/timelineService.ts
- server/testsupport/supportNeedsTestDataBuilder.ts
- server/views/pages/overview/partials/supportNeedsTab/supportNeedsTabContents.test.ts
Display the prison name from the prison search register API
https://dsdmoj.atlassian.net/browse/RR-392
> RR-392 display the prison name from the prison search register api

- server/views/pages/functionalSkills/index.njk
- server/views/pages/overview/partials/overviewTab/functionalSkillsSidebar.njk
Update the functional skills content
https://dsdmoj.atlassian.net/jira/software/c/projects/RR/boards/1214
> RR-625 update the functional skills content

- server/views/pages/overview/partials/educationAndTrainingTab/_functionalSkills.njk
Content change to functional skills headers, including the visuall hidden texts
https://dsdmoj.atlassian.net/browse/RR-625
> RR-625 content change to functional skills headers and hidden texts

- server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionLongQuestionSet.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_qualificationsAndEducationHistory_inductionShortQuestionSet.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
Use a smaller font size on the last updated field
https://dsdmoj.atlassian.net/browse/RR-413
> RR-413 use a smaller font size on the last updated field

- assets/scss/local.scss
- server/views/pages/goal/update/index.njk
Make the section break thicker
https://dsdmoj.atlassian.net/browse/RR-415
> RR-415 make the section break thicker

- server/routes/functionalSkills/functionalSkillsController.ts
- server/routes/functionalSkills/functionalSkillsView.ts
- server/routes/functionalSkillsResolver.test.ts
- server/routes/functionalSkillsResolver.ts
Create a new resolver to get functional skills by type, to allow us to pass separate skill types into the functional skills view page.
Adding the views and using this data will be done in a following PR.
https://dsdmoj.atlassian.net/browse/RR-567
> RR-567 add the separate skill type filters/data to the functional skills view

- server/routes/functionalSkills/functionalSkillsController.test.ts
- server/routes/functionalSkillsResolver.ts
Unit test for functionalSkillsController; destructure arrays in functionalSkillsResolver
> RR-567 - Unit test for functionalSkillsController

- assets/js/mojukFrontendInit.js
- assets/scss/local.scss
- integration_tests/e2e/functionalSkills/functionalSkills.cy.ts
- integration_tests/pages/functionalSkills/FunctionalSkillsPage.ts
- server/routes/functionalSkills/functionalSkillsController.test.ts
- server/routes/functionalSkills/functionalSkillsController.ts
- server/routes/functionalSkills/functionalSkillsView.ts
- server/routes/functionalSkills/index.ts
- server/views/pages/functionalSkills/index.njk
- server/views/pages/functionalSkills/macros/sortableTable.njk
- server/views/pages/prisonerList/index.njk
- server/views/partials/layout.njk
UI for the history of functional skills assessments
https://dsdmoj.atlassian.net/browse/RR-567
Prisoner with data
Prisoner with no data
> RR-567 UI for the history of functional skills assessments

- integration_tests/e2e/induction/updateInduction.cy.ts
- server/data/mappers/createOrUpdateInductionDtoMapper.test.ts
- server/data/mappers/createOrUpdateInductionDtoMapper.ts
- server/routes/induction/update/inPrisonWorkUpdateController.test.ts
- server/routes/induction/update/inPrisonWorkUpdateController.ts
- server/routes/induction/update/index.ts
The disabled IT will be fixed once we've merged this to main.
> RR-647 - Update Induction API call

- server/views/pages/induction/inPrisonWork/index.njk
- server/views/pages/induction/personalInterests/index.njk
- server/views/pages/induction/skills/index.njk
- server/views/partials/layout.njk
Basic views for skills and personal interests pages
https://dsdmoj.atlassian.net/browse/RR-645
> RR-645 basic views for skills and personal interests pages

- server/views/pages/induction/personalInterests/index.njk
Add missing commas to nunjucks views
> RR-645 Add missing commas to nunjucks views

- integration_tests/e2e/goal/createAndEditGoal.cy.ts
- server/routes/createGoal/createGoalFormValidator.test.ts
PR to fix a couple of tests that use 26 Feb 2024 as their date values.
These tests started failing today (because today is 26th Feb 2024 !!! 🤣 )
> NO_JIRA - fix the build by removing hard coded dates

- server/routes/induction/update/index.ts
- server/routes/induction/update/personalInterestsUpdateController.test.ts
- server/routes/induction/update/personalInterestsUpdateController.ts
Handle personal interests form submission
https://dsdmoj.atlassian.net/browse/RR-655
> RR-645 handle personal interests form submission

- integration_tests/e2e/induction/updatePersonalInterests.cy.ts
- integration_tests/e2e/induction/updateSkills.cy.ts
- integration_tests/e2e/overview/workAndInterestsTab.cy.ts
- integration_tests/pages/induction/PersonalInterestsPage.ts
- integration_tests/pages/overview/WorkAndInterestsPage.ts
- server/views/pages/induction/personalInterests/index.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR adds the cypress tests for updating Personal Interests in the Induction
> RR-645 - Cypress tests for updating Personal Interests

- server/@types/express/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/induction/update/typeOfWorkExperienceFormValidator.test.ts
- server/routes/induction/update/typeOfWorkExperienceFormValidator.ts
PR for the definition of the Type Of Work Experience form, and it's validator
> RR-646 - Type Of Work Experience form and validator

- server/views/pages/induction/workInterests/index.njk
Nunjucks template for the work interests page
https://dsdmoj.atlassian.net/browse/RR-648
> RR-648 nunjucks template for the work interests page

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Reverting https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/pull/448
> Revert modsec log level

- server/@types/express/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/induction/common/previousWorkExperienceDetailController.ts
- server/routes/induction/common/previousWorkExperienceDetailView.ts
- server/routes/induction/update/index.ts
- server/routes/induction/update/previousWorkExperienceDetailFormValidator.test.ts
- server/routes/induction/update/previousWorkExperienceDetailFormValidator.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.ts
- server/routes/induction/update/previousWorkExperienceTypesFormValidator.test.ts
- server/routes/induction/update/previousWorkExperienceTypesFormValidator.ts
- server/views/pages/induction/previousWorkExperience/workExperienceDetail.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
This PR adds the form, controller and validator for Previous Work Experience Detail
> RR-646 - Previous Work Experience Detail form, controller and validator

- integration_tests/e2e/induction/updatePreviousWorkExperienceDetail.cy.ts
- integration_tests/e2e/overview/workAndInterestsTab.cy.ts
- integration_tests/pages/induction/PreviousWorkExperienceDetailPage.ts
- integration_tests/pages/overview/WorkAndInterestsPage.ts
This PR adds the cypress tests for updating the Previous Work Experience Detail on an Induction
> RR-646 - Cypress tests for updating Previous Work Experience Detail

- server/routes/induction/common/previousWorkExperienceDetailController.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.ts
This PR refactors the induction mapping and session handling to support being able to redirect to Details page
> RR-646 - Refactored induction mapping and session handling to support being able to redirect to Details page

- integration_tests/e2e/induction/updatePreviousWorkExperienceTypes.cy.ts
- integration_tests/e2e/overview/workAndInterestsTab.cy.ts
- integration_tests/pages/induction/PreviousWorkExperienceTypesPage.ts
- integration_tests/pages/overview/WorkAndInterestsPage.ts
Cypress tests for the update screens/flow for Previous Work Experiences on the Induction
> RR-646 - Initial cypress tests for Previous Work Experience Types

- server/views/pages/induction/additionalTraining/index.njk
This PR adds the nunjucks template for the _"Other Training or Qualifications"_ page.
> RR-695 - Other training or qualifications nunjucks template

- assets/scss/local.scss
- server/routes/induction/common/qualificationsListController.ts
- server/routes/induction/common/qualificationsListView.ts
- server/routes/induction/update/index.ts
- server/routes/induction/update/qualificationsListUpdateController.test.ts
- server/routes/induction/update/qualificationsListUpdateController.ts
- server/views/pages/induction/prePrisonEducation/qualificationsList.njk
This PR migrates the Qualifications List nunjucks template from CIAG UI to our codebase, and introduces a basic controller and route for the GET endpoint to prove it is working (we'll need the GET route anyway, so might as well do it now)
This page is slightly different from the other Induction pages we are migrating because:
* there is no form object - the CIAG is not expected to enter any data and submit anything on this page
* the page needs to render the most recent Functional Skills assessments from Curious if there are any
The various permutations are perhaps best seen with screenshots:
> RR-694 - Initial GET handler and view for Induction "qualifications list" screen

- server/views/pages/inPrisonCoursesAndQualifications/index.njk
- server/views/pages/inPrisonCoursesAndQualifications/macros/sortableTable.njk
- server/views/partials/layout.njk
Boilerplate nunjucks template for the courses and qualifications page, ready to be populated when we have answers on the data for different status of courses.
https://dsdmoj.atlassian.net/browse/RR-673
> RR-673 boilerplate nunjucks template for the courses and qualifications page

- assets/scss/application.scss
- assets/scss/components/_mini-profile-header.scss
- server/views/pages/functionalSkills/index.njk
- server/views/pages/overview/index.njk
- server/views/partials/layout.njk
- server/views/partials/prisonerBanner.njk
Add the mini profile header component and change placement on the page.
https://dsdmoj.atlassian.net/browse/RR-689
**Standard layout page**
**Individual page layout**
> RR-689 add the mini profile header and change placement on page

- server/views/pages/inPrisonCoursesAndQualifications/index.njk
- server/views/pages/inPrisonCoursesAndQualifications/macros/sortableTable.njk
Nunjucks template for the withdrawn courses tab, with the additonal columns in the macro.
https://dsdmoj.atlassian.net/browse/RR-676
> RR-676 nunjucks template for the withdrawn courses tab

- integration_tests/e2e/induction/updateEducationalQualifications.cy.ts
- integration_tests/pages/induction/QualificationsListPage.ts
- server/routes/induction/update/qualificationsListUpdateController.test.ts
- server/routes/induction/update/qualificationsListUpdateController.ts
- server/views/pages/induction/prePrisonEducation/qualificationsList.njk
This PR handles the submission of the Qualification List page to remove a qualification from the list
> RR-694 - Implemented submit handling for removal of qualifications

- integration_tests/pages/induction/HopingToWorkOnReleasePage.ts
- server/views/pages/induction/hopingToWorkOnRelease/index.njk
This PR migrates the Hoping To Work On Release nunjucks template from the CIAG UI
Plus also adds the cypress page class for as and when we get there 👍
> RR-736 - Migrated nunjucks template for Hoping To Work On Release

- integration_tests/e2e/overview/workAndInterestsTab.cy.ts
- integration_tests/pages/overview/WorkAndInterestsPage.ts
- server/@types/express/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/induction/common/hopingToWorkOnReleaseController.ts
- server/routes/induction/common/hopingToWorkOnReleaseView.ts
- server/routes/induction/update/hopingToWorkOnReleaseUpdateController.test.ts
- server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts
- server/routes/induction/update/index.ts
- server/routes/routerRequestHandlers.test.ts
- server/routes/routerRequestHandlers.ts
- server/views/pages/induction/hopingToWorkOnRelease/index.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionLongQuestionSet.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionShortQuestionSet.njk
This PR adds the basic controller with a GET handler for "Hoping to get work on release"
> RR-736 - Basic controller with GET handler

- helm_deploy/values-dev.yaml
> Revert modsec snippet

- helm_deploy/values-dev.yaml
SecRuleUpdateTargetById -> SecRuleUpdateActionById
> Update modsec rule

- helm_deploy/values-dev.yaml
> Reverting modsec rule

- README.md
- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- server/config.ts
Add feature toggle for new goals journey, the toggle will be used in the following PRs..
https://dsdmoj.atlassian.net/browse/RR-743
> RR-743 add feature toggle for new goals journey

- helm_deploy/values-dev.yaml
Enable the feature toggle in dev to show the new Courses & Qualifications screens
> RR-630 - Enable feature toggle in dev

- server/views/pages/induction/prePrisonEducation/qualificationsList.njk
Fixes minor accessibility bug raised in accessibility audit:
https://uv2986-moj-learning-and-work-progress-accessibility-audit.uservisionaccessibility.co.uk/remove-link-not-associated-with-context-observation.html
> RR-756: Fixed remove qualifications accessiblity bug

- server/views/pages/createGoals/index.njk
Use the correct form field values from viewModel, we will need to update these values to add a loop once the session data is setup properly.
> RR-743 use the correct form field values from viewModel

- server/@types/express/index.d.ts
- server/routes/createGoal/createGoalsController.ts
- server/routes/createGoal/createGoalsView.ts
- server/views/pages/createGoals/index.njk
Populate the session with the new CreateGoalsForm and update templates
> RR-746 populate the session with the new CreateGoalsForm and update templates

- server/views/pages/prisonerList/macros/sortableTableHeader.njk
Fix for accessibility issue 2.3 raised in accessibility audit, https://uv2986-moj-learning-and-work-progress-accessibility-audit.uservisionaccessibility.co.uk/problematic-column-headers-low.html
> RR-765: Fixed table header accessibility issue

- server/@types/forms/index.d.ts
- server/routes/createGoal/createGoalsController.ts
- server/routes/createGoal/createGoalsFormValidator.test.ts
- server/routes/createGoal/createGoalsFormValidator.ts
Implement the new `createGoalsForm` form validator with tests (don't be too shocked!)
> RR-748 implement the createGoalsForm validator

- README.md
- feature.env
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/manageUsersApi.ts
- server/@types/express/index.d.ts
- server/config.ts
- server/data/index.ts
- server/data/manageUsersApiClient.test.ts
- server/data/manageUsersApiClient.ts
- server/services/index.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/testutils/createUserToken.ts
Manage users API integration changes from the template merge.
> RR-760: Manage users API integration

- integration_tests/e2e/goal/createGoals.cy.ts
- integration_tests/pages/goal/CreateGoalsPage.ts
- server/@types/forms/index.d.ts
- server/config.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/createGoals/index.njk
This PR continues the fine work Adam started re: the new screen/journey for creating goal(s); but implementing the code behind the "Add another step" button
> RR-734 - Ability to add steps when creating goal

- cypress.config.ts
- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- integration_tests/e2e/health.cy.ts
- server/applicationInfo.ts
- server/config.ts
- server/data/healthCheck.test.ts
- server/data/healthCheck.ts
- server/middleware/setUpHealthChecks.ts
- server/routes/testutils/appSetup.ts
- server/services/healthCheck.test.ts
- server/services/healthCheck.ts
Health check endpoint updates from TypeScript template
> Health check endpoint updates

- server/middleware/authorisationMiddleware.test.ts
- server/middleware/authorisationMiddleware.ts
- server/middleware/setUpAuthentication.ts
PR for some minor auth changes from the template.
> Added auth updates from template

- integration_tests/e2e/goal/createGoals.cy.ts
- integration_tests/pages/goal/CreateGoalsPage.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/createGoals/index.njk
This PR adds the "add another goal" button and functionality to the new Create Goals journey
https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/assets/94835226/1d637757-7e04-4fbd-b905-589ae4ef7140
> RR-735 - Add "add another goal" button and functionality

- integration_tests/e2e/induction/updateInductionQuestionSet.cy.ts
- integration_tests/pages/induction/CheckYourAnswersPage.ts
- server/routes/induction/common/inPrisonTrainingController.ts
This PR implements the cypress test for updating an induction from long question set to short question set
(this is the functionality that Matt completed before he left, but didnt get time to write this cypress test for)
> RR-736 - Cypress test for updating an induction from long question set to short question set

- server/app.ts
- server/utils/azureAppInsights.ts
Small update to application insights code from template to support path params.
More info here, https://dsdmoj.atlassian.net/browse/PI-1789
> Application insights updates

- integration_tests/e2e/goal/createGoals.cy.ts
- integration_tests/pages/goal/CreateGoalsPage.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/createGoals/index.njk
This PR adds the "remove step" functionality to the new Create Goals screen (that I forgot to do when I did the screen! 😬 )
https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/assets/94835226/ce782600-3e48-484b-ae2e-b713e8935a5b
> RR-734 - Add "remove step" functionality

- integration_tests/e2e/goal/createGoals.cy.ts
- integration_tests/pages/goal/CreateGoalsPage.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/createGoals/index.njk
This PR adds the "remove goal" functionality to the new Create Goals screen (that I forgot to do when I did the screen! 😬 )
https://github.com/ministryofjustice/hmpps-education-and-work-plan-ui/assets/94835226/95b1c22d-ea66-47c5-8ab1-abff11362d9c
> RR-735 - Add "remove goal" functionality

- feature.env
- integration_tests/e2e/health.cy.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/common.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/mockApis/manageUsersApi.ts
- integration_tests/mockApis/prisonRegisterApi.ts
- integration_tests/mockApis/prisonerListApi.ts
- integration_tests/mockApis/prisonerSearchApi.ts
- integration_tests/mockApis/tokenVerification.ts
- integration_tests/mockData/prisonerByIdData.ts
- server/config.ts
- server/services/healthCheck.ts
Updates health check endpoint to include all dependant services.
> Health check updates

- integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts
- integration_tests/pages/induction/CheckYourAnswersPage.ts
- server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts
- server/routes/induction/update/highestLevelOfEducationUpdateController.ts
- server/routes/induction/update/qualificationsListUpdateController.ts
- server/views/pages/induction/checkYourAnswers/partials/_educationAndTraining.njk
This PR adds the change links for Highest Level of Education.
Strictly speaking this is a Long Question Set question, but its so tightly related to the other education questions it made sense for me to do it.
> RR-736 - Change links for Highest Level of Education

- integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts
- integration_tests/pages/induction/CheckYourAnswersPage.ts
- server/@types/express/index.d.ts
- server/routes/induction/update/personalInterestsUpdateController.test.ts
- server/routes/induction/update/personalInterestsUpdateController.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.ts
- server/routes/induction/update/skillsUpdateController.test.ts
- server/routes/induction/update/skillsUpdateController.ts
- server/routes/induction/update/workInterestRolesUpdateController.test.ts
- server/routes/induction/update/workInterestRolesUpdateController.ts
- server/routes/induction/update/workInterestTypesUpdateController.test.ts
- server/routes/induction/update/workInterestTypesUpdateController.ts
- server/routes/induction/update/workedBeforeUpdateController.test.ts
- server/routes/induction/update/workedBeforeUpdateController.ts
- server/routes/pageFlowQueue.test.ts
- server/routes/pageFlowQueue.ts
- server/views/pages/induction/checkYourAnswers/partials/_abilityToWork.njk
- server/views/pages/induction/checkYourAnswers/partials/_skillsAndInterests.njk
- server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk
Adds functionality for check your answers change links when updating Hoping to work on release and taking the long question set journey.
> RR-736: Long question set change answers

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/e2e/induction/createLongQuestionSetInduction.cy.ts
- integration_tests/index.d.ts
- integration_tests/support/commands.ts
- server/routes/induction/common/additionalTrainingController.ts
- server/routes/induction/common/affectAbilityToWorkController.ts
- server/routes/induction/common/inductionController.ts
- server/routes/induction/common/personalInterestsController.ts
- server/routes/induction/common/skillsController.ts
- server/routes/induction/create/additionalTrainingCreateController.test.ts
- server/routes/induction/create/additionalTrainingCreateController.ts
- server/routes/induction/create/affectAbilityToWorkCreateController.test.ts
- server/routes/induction/create/affectAbilityToWorkCreateController.ts
- server/routes/induction/create/checkYourAnswersCreateController.test.ts
- server/routes/induction/create/checkYourAnswersCreateController.ts
- server/routes/induction/create/personalInterestsCreateController.test.ts
- server/routes/induction/create/personalInterestsCreateController.ts
- server/routes/induction/create/skillsCreateController.test.ts
- server/routes/induction/create/skillsCreateController.ts
- server/routes/induction/dynamicAriaTextResolver.ts
- server/views/pages/induction/checkYourAnswers/index.njk
- server/views/pages/induction/checkYourAnswers/partials/_abilityToWork.njk
- server/views/pages/induction/checkYourAnswers/partials/_educationAndTraining.njk
- server/views/pages/induction/checkYourAnswers/partials/_educationAndTrainingLite.njk
- server/views/pages/induction/checkYourAnswers/partials/_inPrisonInterests.njk
- server/views/pages/induction/checkYourAnswers/partials/_skillsAndInterests.njk
- server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk
- server/views/pages/induction/checkYourAnswers/partials/_workOnRelease.njk
This PR implements the Change link from Check Your Answers for "factors affecting ability to work"
This is the last question in the long question set flow, and is the easiest to do because no matter what the journey (create or change link) the next page is always Check Your Answers.
All the other pages we do a Change link for will need a little bit of logic to go to the correct page, but we have plenty of tests to protect us 👍
> RR-775 - Change link for Factors Affecting Ability To Work

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- server/routes/induction/common/workInterestRolesController.ts
- server/routes/induction/common/workInterestTypesController.ts
- server/routes/induction/create/workInterestRolesCreateController.test.ts
- server/routes/induction/create/workInterestRolesCreateController.ts
- server/routes/induction/create/workInterestTypesCreateController.test.ts
- server/routes/induction/create/workInterestTypesCreateController.ts
This PR implements the Change link for future work interests (work interests types and work interest roles screens)
> RR-775 - Change link for Future Work Interests

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- server/routes/induction/common/inductionController.ts
- server/routes/induction/common/previousWorkExperienceDetailController.ts
- server/routes/induction/common/previousWorkExperienceTypesController.ts
- server/routes/induction/common/workedBeforeController.ts
- server/routes/induction/create/previousWorkExperienceDetailCreateController.test.ts
- server/routes/induction/create/previousWorkExperienceDetailCreateController.ts
- server/routes/induction/create/previousWorkExperienceTypesCreateController.test.ts
- server/routes/induction/create/previousWorkExperienceTypesCreateController.ts
- server/routes/induction/create/workInterestTypesCreateController.ts
- server/routes/induction/create/workedBeforeCreateController.test.ts
- server/routes/induction/create/workedBeforeCreateController.ts
- server/routes/induction/update/workedBeforeUpdateController.ts
This PR implements the Change link for previous work experience (have they worked before, previous work experience types, and previous work experience detail screens)
> RR-775 - Change link for Previous Work Experience

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- server/routes/induction/common/highestLevelOfEducationController.ts
- server/routes/induction/common/inductionController.ts
- server/routes/induction/create/highestLevelOfEducationCreateController.test.ts
- server/routes/induction/create/highestLevelOfEducationCreateController.ts
- server/routes/induction/create/qualificationDetailsCreateController.ts
- server/routes/induction/create/qualificationsListCreateController.test.ts
- server/routes/induction/create/qualificationsListCreateController.ts
This PR implements the Change link for Qualifications (Highest Level of Education, Qualifications List, adding and removing Qualifications)
> RR-775 - Change link for Qualifications

- integration_tests/e2e/induction/createShortQuestionSetInduction.cy.ts
- integration_tests/e2e/induction/updateCheckYourAnswersChangeLinks.cy.ts
- integration_tests/pages/induction/WantToAddQualificationsPage.ts
- server/routes/induction/common/additionalTrainingController.ts
- server/routes/induction/common/wantToAddQualificationsController.ts
- server/routes/induction/create/additionalTrainingCreateController.ts
- server/views/pages/induction/prePrisonEducation/wantToAddQualifications.njk
Now that all the pages are complete for the short question set induction, this PR completes the cypress test for creating a short question set induction
> RR-774 - Completion of cypress tests for creating Short Question Set Induction

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/index.d.ts
- integration_tests/support/commands.ts
- server/routes/induction/common/inPrisonTrainingController.ts
- server/routes/induction/common/inPrisonWorkController.ts
- server/routes/induction/common/reasonsNotToGetWorkController.ts
- server/routes/induction/create/inPrisonTrainingCreateController.test.ts
- server/routes/induction/create/inPrisonTrainingCreateController.ts
- server/routes/induction/create/inPrisonWorkCreateController.test.ts
- server/routes/induction/create/inPrisonWorkCreateController.ts
- server/routes/induction/create/reasonsNotToGetWorkCreateController.test.ts
- server/routes/induction/create/reasonsNotToGetWorkCreateController.ts
This PR implements the cypress test for the Change links on the Check Your Answers page when creating a Short Question Set Induction (and a few changes to the relevant controllers to support it)
> RR-782 - Change links from Check Your Answers for creating Short Question Set Induction

- integration_tests/e2e/induction/createChangeInductionQuestionSet.cy.ts
- integration_tests/e2e/induction/updateInductionQuestionSet.cy.ts
- server/routes/induction/common/hopingToWorkOnReleaseController.ts
- server/routes/induction/create/hopingToWorkOnReleaseCreateController.ts
- server/routes/induction/create/qualificationsListCreateController.ts
- server/routes/induction/create/reasonsNotToGetWorkCreateController.test.ts
- server/routes/induction/create/reasonsNotToGetWorkCreateController.ts
- server/routes/induction/update/hopingToWorkOnReleaseUpdateController.ts
This PR implements the cypress tests (and some minor code changes to support) to test and assert the "Do you want to work on release" change link on Check Your Answers which results in a changed question set and therefore having to go through the journey again
> RR-782 - Change question set from Check Your Answers

- helm_deploy/values-dev.yaml
This PR enables the Create Induction and Update Induction feature toggles in `dev`
> RR-636 - Enable feature toggles in dev

- server/views/pages/prisonerList/partials/searchBox.njk
Small content change on the Prisoner List screen:
> RR-755 - Updated label for prisoner name/number on prisoner list screen

- server/views/pages/createGoals/index.njk
Small content change on the Create Goals screen:
> RR-777 - Updated text on create goals screen

- server/@types/express/index.d.ts
- server/app.ts
- server/middleware/setUpAuthentication.ts
- server/middleware/successMiddleware.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/overview/index.njk
- server/views/partials/layout.njk
This adds a new success middleware which configures a new response helper method, `redirectWithSuccess()`. This method will redirect to a page and show a success banner with the desired success message.
> RR-787: Success middleware

- renovate.json
Minor update to align our Renovate config with the template
> RR-794: Updated Renovate config to align with template

- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/views/pages/createGoals/index.njk
This change removes the form initalisation code from the controller and updates the view so that if the form is not initialised it will loop once to add the initial goal and step inputs.
> RR-788: Removes form initalisation from controller

- integration_tests/pages/goal/CreateGoalsPage.ts
- server/@types/forms/index.d.ts
- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/routes/createGoal/index.ts
- server/views/pages/createGoals/index.njk
This PR separates out form action logic from form submission logic with new controller method.
> RR-798: Seperated form action logic with new controller method

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/e2e/induction/createInduction.cy.ts
- integration_tests/e2e/induction/updateWorkedBefore.cy.ts
- integration_tests/pages/induction/CheckYourAnswersPage.ts
- integration_tests/pages/induction/WorkedBeforePage.ts
- server/@types/dto/index.d.ts
- server/@types/educationAndWorkPlanApi/index.d.ts
- server/@types/forms/index.d.ts
- server/data/mappers/createOrUpdateInductionDtoMapper.ts
- server/routes/induction/common/workedBeforeController.ts
- server/routes/induction/create/workedBeforeCreateController.test.ts
- server/routes/validators/induction/workedBeforeFormValidator.test.ts
- server/routes/validators/induction/workedBeforeFormValidator.ts
- server/views/pages/induction/checkYourAnswers/partials/_workExperience.njk
- server/views/pages/induction/workedBefore/index.njk
- server/views/pages/overview/partials/workAndInterestsTab/_inductionQuestionSet.njk
This PR adds the conditional "reason" field for "Has worked before" when the user answers it as Not Relevant
> RR-865 - Added question to capture reason why "has worked before" is "not relevant"

- integration_tests/e2e/goal/archiveGoal.cy.ts
- integration_tests/e2e/goal/createGoals.cy.ts
- integration_tests/pages/overview/OverviewPage.ts
- server/routes/archiveGoal/archiveGoalController.test.ts
- server/routes/archiveGoal/archiveGoalController.ts
- server/views/partials/layout.njk
Should show a success message on the overview page when archiving a goal.
> RR-869: Show success on archiving goal

- server/views/pages/accessibilityStatement/index.njk
This PR updates the content of the accessibility statement page (`http://localhost:3000/accessibility-statement`)
> RR-876 - Updated accessibility statement

- assets/scss/components/_summary-card.scss
- integration_tests/e2e/goal/viewArchivedGoals.cy.ts
- server/views/components/goal-summary-card-v2/goalSummaryCardV2.test.ts
- server/views/components/goal-summary-card-v2/template.njk
Increase padding all around to 3 (15px) and add a margin to the subtitle so it aligns correctly with the target image.
Also removed the colon from last updated/archived on label.
> RR-826: Minor UI tweaks to view archived goals

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Added 3 new prisons to the active agencies so the PLP tile appears for them.
Isle of Wight - IWI
Long Lartin - LLI
Maidstone - MSI
> RR-897: Add IWI, LLI and MSI to active agencies

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Added Downview prison (DWI) to the active agencies so the PLP tile appears for it.
> RR-924: Add DWI to active agencies

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Added Leicester prison (LCI) to the active agencies so the PLP tile appears for it.
> RR-925: Add LCI to active agencies

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Add Askham Grange (AGI), Foston Hall (FHI), Huntercombe (HCI), Norwich (NWI) and Exeter (EXI) to the active agencies.
> RR-926: Add 5 prisons to tile

- helm_deploy/values-dev.yaml
- server/config.ts
Add feature toggle for allowing qualifications to be managed outside of an Induction.
> RR-936: UI-add feature toggle for qualifications

- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistoryWithInduction.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistoryWithInduction.test.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistoryWithoutInduction.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistoryWithoutInduction.test.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndTrainingTabWithInductionContents.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndTrainingTabWithInductionContents.test.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndTrainingTabWithoutInductionContents.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndTrainingTabWithoutInductionContents.test.ts
Creating the views for the education and qualifications section of the education and training tab. Content displayed depends on whether the feature flag 'QUALIFICATIONS_ENABLED' is enabled and whether the prisoner has qualifications inside or outside of an induction.
> RR-893: New qualifications entry point-Part 1

- helm_deploy/values-dev.yaml
Disable QUALIFICATIONS_ENABLED flag
> Disable QUALIFICATIONS_ENABLED flag

- server/@types/dto/index.d.ts
- server/data/mappers/achievedQualificationComparator.test.ts
- server/data/mappers/achievedQualificationComparator.ts
- server/data/mappers/educationMapper.ts
- server/filters/achievedQualificationObjectsSortedInScreenOrderFilter.test.ts
- server/filters/achievedQualificationObjectsSortedInScreenOrderFilter.ts
- server/routes/induction/common/qualificationsListController.ts
- server/routes/induction/common/qualificationsListView.ts
- server/routes/induction/create/qualificationsListCreateController.test.ts
- server/routes/induction/create/wantToAddQualificationsCreateController.test.ts
- server/routes/induction/update/highestLevelOfEducationUpdateController.test.ts
- server/routes/induction/update/qualificationsListUpdateController.test.ts
- server/testsupport/achievedQualificationDtoTestDataBuilder.ts
- server/testsupport/educationDtoTestDataBuilder.ts
More changes in the area of education DTOs to better support what we need to do re: qualifications before induction
> RR-939 - More education DTO refactoring

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
> RR-927: Add Drake Hall to tile by 9 Sept

- integration_tests/e2e/prePrisonEducaton/createPrePrisonEducation.cy.ts
- server/@types/express/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/induction/common/qualificationDetailsController.ts
- server/routes/prePrisonEducation/index.ts
- server/routes/prePrisonEducation/qualificationDetailsController.test.ts
- server/routes/prePrisonEducation/qualificationDetailsController.ts
- server/routes/prePrisonEducation/qualificationDetailsView.ts
- server/routes/prePrisonEducation/qualificationLevelController.test.ts
- server/routes/routerRequestHandlers/removeInductionFormsFromSession.test.ts
- server/routes/validators/induction/qualificationDetailsFormValidator.test.ts
- server/routes/validators/induction/qualificationDetailsFormValidator.ts
PR to add the Qualification Details controller and associated code (which is the next screen in the new "create education before an induction" process we are working on)
> RR-939 - Added qualificationDetailsController and supporting code

- server/@types/dto/index.d.ts
- server/@types/educationAndWorkPlanApi/index.d.ts
- server/@types/educationAndWorkPlanApiClient/index.d.ts
- server/data/educationAndWorkPlanClient.test.ts
- server/data/educationAndWorkPlanClient.ts
- server/data/mappers/createEducationMapper.test.ts
- server/data/mappers/createEducationMapper.ts
- server/data/mappers/createOrUpdateInductionDtoMapper.test.ts
- server/data/mappers/updateInductionMapper.test.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.test.ts
- server/routes/induction/update/qualificationsListUpdateController.test.ts
- server/services/educationAndWorkPlanService.test.ts
- server/services/educationAndWorkPlanService.ts
- server/services/inductionService.test.ts
- server/services/inductionService.ts
- server/testsupport/achievedQualificationDtoTestDataBuilder.ts
- server/testsupport/createAchievedQualificationRequestTestDataBuilder.ts
- server/testsupport/createEducationDtoTestDataBuilder.ts
- server/testsupport/createEducationRequestTestDataBuilder.ts
- server/testsupport/educationDtoTestDataBuilder.ts
- server/testsupport/updateInductionDtoTestDataBuilder.ts
This PR creates the client and service methods for Create Education, and associated code.
> RR-939 - Client and service methods for Create Education, and associated code

- integration_tests/e2e/prePrisonEducaton/createPrePrisonEducation.cy.ts
- integration_tests/pages/overview/EducationAndTrainingPage.ts
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk
Activating the link to add education outside an induction.
> RR-939: Activate the link to add education

- server/filters/formatQualificationLevelHintFilter.test.ts
- server/filters/formatQualificationLevelHintFilter.ts
Updating the descriptions for Level 1 and Level 2 qualifications.
> RR-940: Update copy for qualifications

- server/routes/overview/timelineController.test.ts
- server/routes/overview/timelineController.ts
- server/services/index.ts
- server/services/timelineService.test.ts
- server/services/timelineService.ts
Changing from user token to system token in GET timeline.
> RR-914: Change from user to system token for timeline

- server/routes/overview/index.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/routes/routerRequestHandlers/retrieveGoals.test.ts
- server/routes/routerRequestHandlers/retrieveGoals.ts
Creating new middleware to retrieve goals and store them on res.locals.
> RR-953: Create middleware for retrieving goals

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Enable service for prisons LNI and STI
> RR-945 - Enable service for prisons LNI and STI

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
RR-946 - Enabled prisons HCI, SKI, BNI
RR-982 - Enabled prisons WCI, NMI, TCI
> RR-946 & RR-982 - Enable 6 new prisons

- server/views/autherror.njk
- server/views/pages/404.njk
- server/views/pages/error.njk
- server/views/partials/layout.njk
This PR updates the content for the authorisation error page (RR-985) and the general error page (RR-986)
> RR-985 & RR-986 - Updated error page content

- integration_tests/e2e/reviewPlan/reviewPlan.cy.ts
- integration_tests/pages/reviewPlan/ReviewNotePage.ts
- server/@types/dto/index.d.ts
- server/@types/express/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/reviewPlan/index.ts
- server/routes/reviewPlan/reviewNoteController.test.ts
- server/routes/reviewPlan/reviewNoteController.ts
- server/routes/reviewPlan/reviewNoteView.ts
- server/routes/reviewPlan/whoCompletedReviewController.test.ts
- server/routes/reviewPlan/whoCompletedReviewController.ts
- server/routes/routerRequestHandlers/checkReviewPlanDtoExistsInPrisonerContext.test.ts
- server/routes/routerRequestHandlers/checkReviewPlanDtoExistsInPrisonerContext.ts
- server/routes/routerRequestHandlers/createEmptyReviewPlanDtoIfNotInPrisonerContext.test.ts
- server/routes/routerRequestHandlers/createEmptyReviewPlanDtoIfNotInPrisonerContext.ts
- server/testsupport/reviewPlanDtoTestDataBuilder.ts
- server/views/pages/reviewPlan/reviewNote/index.njk
This PR adds the "Add note to review" screen to the Review journey:
https://github.com/user-attachments/assets/f98e9b26-0aa7-439a-85ba-4d86c75f5c86
> RR-965 - 'Add note to review' screen

- server/views/pages/overview/partials/supportNeedsTab/supportNeedsTabContents.njk
- server/views/pages/overview/partials/supportNeedsTab/supportNeedsTabContents.test.ts
Changing label, hint and descriptions.
> RR-979: Support needs content updates

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Onboarding the following prisons:
Exeter - EXI
Eastwood Park - EWI
> RR-992: Adding EXI and EWI

- server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
> RR-953 - Corrected wording

- assets/scss/local.scss
- server/views/components/actions-card/template.njk
- server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.njk
Remove padding around 'Add a new goal' in Action card
Slight increase in space above 'Courses and qualifications completed in the last 12 months'
> RR-1003: Overview page changes

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Add Deerbolt (DTI) and Manchester (MRI) to tile.
> RR-993: Add 2 prisons to tile

- server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
> Remove completed goals tab from prod

- integration_tests/e2e/overview/goal/archiveGoal.cy.ts
- integration_tests/e2e/overview/goal/reviewUpdateGoal.cy.ts
- integration_tests/e2e/overview/goal/unarchiveGoal.cy.ts
- integration_tests/e2e/overview/goal/updateGoal.cy.ts
- integration_tests/e2e/overview/goal/viewArchivedGoals.cy.ts
- integration_tests/e2e/overview/timeline.cy.ts
- integration_tests/pages/overview/GoalsPage.ts
- integration_tests/pages/overview/OverviewPage.ts
- integration_tests/pages/overview/TimelinePage.ts
- server/views/components/goal-summary-card/_goalSteps.test.ts
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ACTIVE.njk
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ACTIVE.test.ts
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.njk
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-ARCHIVED.test.ts
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-COMPLETED.njk
- server/views/components/goal-summary-card/_goalSummaryCardContent-goalInStatus-COMPLETED.test.ts
- server/views/components/goal-summary-card/_goalSummaryCardHeadingAndActions.njk
- server/views/components/goal-summary-card/_goalSummaryCardHeadingAndActions.test.ts
- server/views/components/goal-summary-card/goalSummaryCard.test.ts
- server/views/components/goal-summary-card/test.njk
- server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
- server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts
This PR refactors the goal summary component summary cards, and more specifically the unit tests
> RR-974 - Refactored nunjucks components and unit & integration tests

- server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.njk
- server/views/pages/overview/partials/overviewTab/overviewTabContentsV2.test.ts
Heading and hint text for the courses and qualifications is now displayed in all cases.
> RR-1035: Heading and hint text

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- helm_deploy/values-dev.yaml
PR to enable feature toggles for Completing Goals and Archive Goal Notes in all envs.
**Note:** It is OK to review and merge this PR, and deploy to `dev`; but do not promote to `prod` until Monday 28/10/24
> RR-971/RR-956 - Enable feature toggles for Completing Goals and Archive Goal Notes

- integration_tests/e2e/reviewPlan/reviewPlan.cy.ts
- integration_tests/pages/reviewPlan/WhoCompletedReviewPage.ts
- server/@types/dto/index.d.ts
- server/@types/forms/index.d.ts
- server/routes/reviewPlan/whoCompletedReviewController.test.ts
- server/routes/reviewPlan/whoCompletedReviewController.ts
- server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.test.ts
- server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.ts
- server/testsupport/reviewPlanDtoTestDataBuilder.ts
- server/views/pages/reviewPlan/whoCompletedReview/index.njk
Adding 'Who completed review' screen.
https://github.com/user-attachments/assets/d6780d09-ca49-48d7-ba8c-14b5433f0c96
> RR-1036: Who completed review screen

- integration_tests/e2e/reviewPlan/reviewPlan.cy.ts
- integration_tests/pages/reviewPlan/ReviewNotePage.ts
- server/routes/reviewPlan/index.ts
- server/routes/reviewPlan/reviewCheckYourAnswersController.ts
- server/routes/reviewPlan/reviewCheckYourAnswersView.ts
- server/routes/reviewPlan/reviewNoteController.test.ts
- server/routes/reviewPlan/reviewNoteController.ts
- server/routes/validators/reviewPlan/reviewNoteValidator.test.ts
- server/routes/validators/reviewPlan/reviewNoteValidator.ts
- server/views/pages/reviewPlan/checkYourAnswers.njk
- server/views/pages/reviewPlan/reviewNote/index.njk
Added 'Add note to this review' screen
Added validation for the note
Created dummy 'Check your answers' page and controller, view, to evidence next page navigation
Updated integration tests
https://github.com/user-attachments/assets/6cbe10e5-cef3-46b6-878b-fe2322e974ab
> RR-1037: Review notes page

- server/routes/functionalSkills/functionalSkillsController.ts
- server/routes/functionalSkills/functionalSkillsView.ts
- server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.test.ts
- server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsController.ts
- server/routes/inPrisonCoursesAndQualifications/inPrisonCoursesAndQualificationsView.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/routes/overview/viewGoalsController.ts
- server/routes/overview/viewGoalsView.ts
- server/routes/prisonerList/prisonerListController.ts
- server/routes/prisonerList/prisonerListView.ts
- server/views/pages/functionalSkills/index.njk
- server/views/pages/inPrisonCoursesAndQualifications/plpTemplate.njk
- server/views/pages/overview/index.njk
- server/views/pages/overview/partials/goalsTab/goalsTabContents.njk
- server/views/pages/overview/partials/goalsTab/goalsTabContents.test.ts
- server/views/pages/prisonerList/index.njk
- server/views/partials/serviceOnboardingBanner.njk
https://github.com/user-attachments/assets/bfe43639-b214-4701-bafa-9ff1aa114f5b
> Rr-1091: Service onboarding banner

- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
- server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
https://github.com/user-attachments/assets/244cd755-82ea-4ec8-b439-a60bfe6378ca
> Rr-1112: Read-only content changes

- server/@types/viewModels/index.d.ts
- server/data/mappers/actionPlanMapper.ts
- server/data/mappers/actionPlanReviewsMapper.test.ts
- server/data/mappers/actionPlanReviewsMapper.ts
- server/data/mappers/completedActionPlanReviewMapper.test.ts
- server/data/mappers/completedActionPlanReviewMapper.ts
- server/data/mappers/inductionScheduleMapper.test.ts
- server/data/mappers/inductionScheduleMapper.ts
- server/data/mappers/noteMapper.test.ts
- server/data/mappers/noteMapper.ts
- server/data/mappers/scheduledActionPlanReviewMapper.test.ts
- server/data/mappers/scheduledActionPlanReviewMapper.ts
- server/services/inductionService.test.ts
- server/services/inductionService.ts
- server/services/reviewService.test.ts
- server/services/reviewService.ts
- server/testsupport/inductionScheduleTestDataBuilder.ts
Service methods for getting reviews and induction schedules, and associated view models and mappers
> RR-1151 - Service methods for getting reviews and induction schedules

- server/@types/dto/index.d.ts
- server/@types/viewModels/index.d.ts
- server/data/mappers/createActionPlanReviewRequestMapper.test.ts
- server/data/mappers/createActionPlanReviewRequestMapper.ts
- server/data/mappers/createdActionPlanMapper.test.ts
- server/data/mappers/createdActionPlanMapper.ts
- server/routes/reviewPlan/reviewCheckYourAnswersController.test.ts
- server/routes/reviewPlan/reviewNoteController.test.ts
- server/routes/reviewPlan/whoCompletedReviewController.test.ts
- server/routes/reviewPlan/whoCompletedReviewController.ts
- server/services/reviewService.test.ts
- server/services/reviewService.ts
- server/testsupport/reviewPlanDtoTestDataBuilder.ts
This PR adds the service method to be able to create an action plan review
> RR-1151 - Service method for creating review, and associated mappers etc

- assets/scss/components/_confirm-exemption.scss
- integration_tests/e2e/reviewPlan/exemption/confirmExemption.cy.ts
- integration_tests/e2e/reviewPlan/exemption/exemptionRecorded.cy.ts
- integration_tests/pages/reviewPlan/exemption/confirmExemptionPage.ts
- integration_tests/pages/reviewPlan/exemption/exemptionRecordedPage.ts
- server/middleware/auditMiddleware.ts
- server/routes/reviewPlan/confirmExemptionController.test.ts
- server/routes/reviewPlan/confirmExemptionController.ts
- server/routes/reviewPlan/exemptionRecordedController.test.ts
- server/routes/reviewPlan/exemptionRecordedController.ts
- server/routes/reviewPlan/exemptionRecordedView.ts
- server/routes/reviewPlan/index.ts
- server/views/pages/reviewPlan/confirmExemption/index.njk
- server/views/pages/reviewPlan/confirmExemption/index.test.ts
- server/views/pages/reviewPlan/exemptionRecorded/index.njk
- server/views/pages/reviewPlan/exemptionRecorded/index.test.ts
- server/views/partials/layout.njk
Creating the 'Exemption Recorded' page and minor updates to the 'Confirm Exemption' page.
https://github.com/user-attachments/assets/801a6e82-bf98-4045-baee-685d2e02abee
> RR-1047: Exemption recorded page + minor tweaks

- integration_tests/e2e/overview/overview.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- server/routes/overview/index.ts
- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewController.ts
- server/routes/overview/overviewView.ts
- server/routes/routerRequestHandlers/retrieveActionPlanReviews.test.ts
- server/routes/routerRequestHandlers/retrieveActionPlanReviews.ts
- server/routes/routerRequestHandlers/retrieveAllGoalsForPrisoner.test.ts
- server/services/index.ts
- server/testsupport/actionPlanReviewsTestDataBuilder.ts
This PR adds the middleware to get the prisoner's action plan reviews, and calls it as part of the route to get the overview page.
> RR-1157 - Add middleware etc to make call to get action plan reviews

- server/routes/overview/overviewController.test.ts
- server/routes/overview/overviewView.ts
Refactoring from RR-1028 branch
> RR-1028: PR comments

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
PR to add Aylesbury, Moorland, and Cookham Wood as enabled prisons
> RR-115 - Added Aylesbury, Moorland, and Cookham Wood as enabled prisons

- server/views/pages/reviewPlan/exemption/exemptionReason/index.njk
Minor design tweak identified by Aliki - added the "or" separator :
> RR-1045 - Added "or" separator

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
PR to enable service for 4 new prisons, ready for Monday 13/01/2025:
* Bristol - BLI
* Onley - ONI
* Warren Hill - WII
* Whitemoor - WRI
> RR-1200 - Enabled service for 4 more prisons

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/pages/induction/CheckYourAnswersPage.ts
- server/views/pages/induction/checkYourAnswers/index.njk
- server/views/pages/induction/checkYourAnswers/partials/_inductionCompletedBy.njk
- server/views/pages/induction/checkYourAnswers/partials/_inductionNote.njk
This PR adds Induction Completed By, Date, & Notes to the Check Your Answers page
> RR-1178 - Added Induction Completed By, Date, & Notes to Check Your Answers page

- server/routes/archiveGoal/archiveGoalController.test.ts
- server/routes/completegoal/completeGoalController.test.ts
- server/routes/prePrisonEducation/create/qualificationsListCreateController.test.ts
- server/routes/prePrisonEducation/create/qualificationsListCreateController.ts
- server/routes/prePrisonEducation/update/highestLevelOfEducationUpdateController.test.ts
- server/routes/prePrisonEducation/update/highestLevelOfEducationUpdateController.ts
- server/routes/prePrisonEducation/update/qualificationsListUpdateController.test.ts
- server/routes/prePrisonEducation/update/qualificationsListUpdateController.ts
- server/routes/unarchiveGoal/unarchiveGoalController.test.ts
- server/services/educationAndWorkPlanService.test.ts
- server/services/educationAndWorkPlanService.ts
This PR uses the system token for API calls to create and update education
(the API calls and the relevant code being changed is all very similar for these 2, so I have grouped them into this one PR)
> RR-1222 - Use the system token for API calls to create and update education.

- server/routes/createGoal/createGoalsController.test.ts
- server/routes/createGoal/createGoalsController.ts
- server/routes/updateGoal/updateGoalController.test.ts
- server/routes/updateGoal/updateGoalController.ts
- server/services/educationAndWorkPlanService.test.ts
- server/services/educationAndWorkPlanService.ts
This PR uses the system token for API calls to create and update goals
(the API calls and the relevant code being changed is all very similar for these 2, so I have grouped them into this one PR)
> RR-1222 - Use the system token for API calls to create and update goals.

- integration_tests/e2e/induction/exemptInduction.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/pages/overview/OverviewPage.ts
This PR adds the Cypress tests for the Exempt Induction journey
https://github.com/user-attachments/assets/8395d0fb-5105-4854-8ab5-9e403a1f6f7b
> RR-1180 - Cypress tests for the Exempt Induction journey

- integration_tests/e2e/induction/exemptInduction.cy.ts
- integration_tests/e2e/induction/removeInductionExemption.cy.ts
- integration_tests/pages/induction/ConfirmExemptionPage.ts
- integration_tests/pages/induction/ConfirmExemptionRemovalPage.ts
- integration_tests/pages/induction/ExemptionRemovedPage.ts
- integration_tests/pages/overview/OverviewPage.ts
- integration_tests/pages/reviewPlan/exemption/confirmExemptionPage.ts
- server/routes/induction/exemption/index.ts
- server/routes/induction/exemption/removeExemption/confirmExemptionRemovalController.test.ts
- server/routes/induction/exemption/removeExemption/confirmExemptionRemovalController.ts
- server/routes/induction/exemption/removeExemption/confirmExemptionRemovalView.ts
- server/routes/induction/exemption/removeExemption/exemptionRemovedController.test.ts
- server/routes/induction/exemption/removeExemption/exemptionRemovedController.ts
- server/routes/induction/exemption/removeExemption/exemptionRemovedView.ts
- server/routes/induction/exemption/removeExemption/index.ts
- server/views/pages/induction/exemption/confirmExemption/index.njk
- server/views/pages/induction/removeExemption/confirmRemoval/index.njk
- server/views/pages/induction/removeExemption/exemptionRemoved/index.njk
- server/views/pages/reviewPlan/exemption/exemptionReason/index.njk
- server/views/pages/reviewPlan/exemption/exemptionReason/index.test.ts
- server/views/pages/reviewPlan/removeExemption/confirmRemoval/index.njk
This PR implements the screens, controllers and cypress tests to clear/remove the exemption from an Induction
https://github.com/user-attachments/assets/41b702ba-3bc4-407a-971c-5d2feab5c922
> RR-1183 - Remove exemption from induction

- server/@types/dto/index.d.ts
- server/@types/forms/index.d.ts
- server/@types/viewModels/index.d.ts
- server/enums/stepStatusValue.ts
- server/routes/updateGoal/mappers/goalToUpdateGoalFormMapper.test.ts
- server/routes/updateGoal/mappers/goalToUpdateGoalFormMapper.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.test.ts
- server/routes/updateGoal/mappers/updateGoalFormToUpdateGoalDtoMapper.ts
- server/routes/updateGoal/updateGoalController.test.ts
- server/routes/updateGoal/updateGoalFormValidator.test.ts
- server/testsupport/updateGoalDtoTestDataBuilder.ts
- server/testsupport/updateGoalFormTestDataBuilder.ts
- server/views/pages/goal/update/index.njk
PR to fix the bug re: the Goal status field on the Update Goal review page
> RR-1184 - Correct the status on the update goal review page

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
PR to enable the service for:
- Brinsford - BSI
- Brixton - BXI
- Channings Wood - CWI
- Coldingley - CLI
- Frankland - FKI
- Hatfield - HDI
- Leeds. - LEI
- Lowdham Grange - LGI
- Pentonville - PVI
- Swinfen Hall - SNI
> RR-1231 - Enabled 10 more prisons

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Enable service for Littlehey (LTI) and Woodhill (WHI)
> RR-1244 - Enable service for Littlehey and Woodhill

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
PR to enable the service for:
* Belmarsh - BAI
* Doncaster - DNI
* Whatton - WTI
* Wormwood Scrubs - WSI
> RR-1251 - Enable service for Belmarsh, Doncaster, Whatton and Wormwood Scrubs

- cypress.config.ts
- integration_tests/e2e/sessionList/dueSessionsList.cy.ts
- integration_tests/e2e/sessionList/onHoldSessionsList.cy.ts
- integration_tests/e2e/sessionList/overdueSessionsList.cy.ts
- integration_tests/mockApis/educationAndWorkPlanApi.ts
- integration_tests/mockData/sessionResponseMockDataGenerator.ts
- integration_tests/pages/sessionSummary/SessionsSummaryPage.ts
- server/routes/sessionList/sessionListController.test.ts
- server/routes/sessionList/sessionListController.ts
Unit and cypress tests for the Session List (due/overdue/on-hold) screens
> RR-1024 - Added unit and cypress tests

- server/views/pages/sessionList/macros/searchResultsTable.njk
- server/views/pages/sessionList/onHoldSessions.njk
PR to add the "remove exemption" link to the rows on the On Hold tab (forgot to do it when I did the main dev for this tab 😬 🙄 🤣 )
> RR-1026 - Added remove exemption links

- server/routes/prisonerList/pagedPrisonerSearchSummary.test.ts
- server/routes/prisonerList/pagedPrisonerSearchSummary.ts
- server/views/pages/prisonerList/partials/searchBox.njk
- server/views/pages/prisonerList/partials/searchTable.njk
PR to:
* Make the existing "Needs plan" status yellow (from red)
* Add a new "Plan created" status in green
* Ensure sorting works
* Add the new "Plan created" option to the status filter
https://github.com/user-attachments/assets/9620675c-6fe9-492d-a58e-fa88e0d983cc
> RR-1254 - Added 'plan created' status

- package-lock.json
- package.json
- renovate.json
- server/middleware/checkWhetherToShowServiceOnboardingBanner.test.ts
- server/middleware/checkWhetherToShowServiceOnboardingBanner.ts
- server/routes/testutils/appSetup.ts
- server/views/pages/prisonerList/index.njk
- server/views/pages/prisonerList/index.test.ts
This PR adds the breadcrumb links to the Manager's landing page (session summary page) when the user is a Manager and they are on the prisoner-list page (ie. allowing them to get back to their landing page)
> RR-1272 - Added breadcrumb links for manager on prisoner-list page

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Enable service for Birmingham (BMI) and Durham (DMI)
> RR-1274 - Enable service for Birmingham and Durham

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
PR to enable the service for 2 new prisons - Morton Hall (MHI) and Thameside (TSI)
> RR-1275 - Enabled service for Morton Hall (MHI) and Thameside (TSI)

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/e2e/induction/createInduction.cy.ts
- integration_tests/e2e/induction/updatePersonalInterests.cy.ts
- integration_tests/e2e/induction/updateSkills.cy.ts
- server/routes/induction/common/personalInterestsController.ts
- server/routes/induction/common/personalInterestsView.ts
- server/routes/induction/common/skillsController.ts
- server/routes/induction/common/skillsView.ts
- server/routes/induction/create/personalInterestsCreateController.test.ts
- server/routes/induction/create/personalInterestsCreateController.ts
- server/routes/induction/create/skillsCreateController.test.ts
- server/routes/induction/create/skillsCreateController.ts
- server/routes/induction/update/personalInterestsUpdateController.test.ts
- server/routes/induction/update/personalInterestsUpdateController.ts
- server/routes/induction/update/skillsUpdateController.test.ts
- server/routes/induction/update/skillsUpdateController.ts
- server/views/pages/induction/personalInterests/index.njk
- server/views/pages/induction/skills/index.njk
PR to refactor the Back links on the Induction journey "Personal Interests" and "Personal Skills" pages to the Javascript back links.
> RR-849 - Refactored back links on Personal Interests and Skills pages

- integration_tests/e2e/induction/createCheckYourAnswersChangeLinks.cy.ts
- integration_tests/e2e/induction/createInduction.cy.ts
- integration_tests/e2e/induction/updatePreviousWorkExperienceDetail.cy.ts
- integration_tests/e2e/induction/updatePreviousWorkExperienceTypes.cy.ts
- integration_tests/e2e/induction/updateWorkedBefore.cy.ts
- server/routes/induction/common/previousWorkExperienceDetailController.ts
- server/routes/induction/common/previousWorkExperienceDetailView.ts
- server/routes/induction/common/previousWorkExperienceTypesController.ts
- server/routes/induction/common/previousWorkExperienceTypesView.ts
- server/routes/induction/common/workedBeforeController.ts
- server/routes/induction/common/workedBeforeView.ts
- server/routes/induction/create/previousWorkExperienceDetailCreateController.test.ts
- server/routes/induction/create/previousWorkExperienceDetailCreateController.ts
- server/routes/induction/create/previousWorkExperienceTypesCreateController.test.ts
- server/routes/induction/create/previousWorkExperienceTypesCreateController.ts
- server/routes/induction/create/workedBeforeCreateController.test.ts
- server/routes/induction/create/workedBeforeCreateController.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceDetailUpdateController.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.test.ts
- server/routes/induction/update/previousWorkExperienceTypesUpdateController.ts
- server/routes/induction/update/workedBeforeUpdateController.test.ts
- server/routes/induction/update/workedBeforeUpdateController.ts
- server/views/pages/induction/previousWorkExperience/workExperienceDetail.njk
- server/views/pages/induction/previousWorkExperience/workExperienceTypes.njk
- server/views/pages/induction/workedBefore/index.njk
PR to refactor the Back links on the Induction journey "Have you worked before" and "Previous Work Experience" pages to the Javascript back links.
> RR-849 - Refactored back links on Have You Worked Before and Previous Work Experience pages

- server/filters/formatInductionExemptionReasonFilter.test.ts
- server/filters/formatInductionExemptionReasonFilter.ts
- server/filters/formatReviewExemptionReasonFilter.test.ts
- server/filters/formatReviewExemptionReasonFilter.ts
- server/views/components/actions-card/_inductionActions.njk
- server/views/pages/createGoals/index.njk
- server/views/pages/goal/archive/reason.njk
- server/views/pages/goal/archive/review.njk
- server/views/pages/goal/complete/index.njk
- server/views/pages/goal/update/review.njk
- server/views/pages/induction/exemption/confirmExemption/index.njk
- server/views/pages/induction/exemption/exemptionRecorded/index.njk
- server/views/pages/induction/inductionNote/index.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_educationAndQualificationsHistory.njk
- server/views/pages/overview/partials/educationAndTrainingTab/_trainingAndEducationInterestsInPrison.njk
- server/views/pages/overview/partials/overviewTab/overviewTabContents.njk
- server/views/pages/overview/partials/timelineTab/_timelineEvent-ACTION_PLAN_CREATED.njk
- server/views/pages/overview/partials/timelineTab/_timelineEvent-INDUCTION_UPDATED.njk
- server/views/pages/overview/partials/workAndInterestsTab/workAndInterestsTabContents.njk
- server/views/pages/reviewPlan/exemption/confirmExemption/index.njk
- server/views/pages/reviewPlan/exemption/exemptionReason/index.test.ts
- server/views/pages/reviewPlan/removeExemption/confirmRemoval/index.njk
- server/views/pages/reviewPlan/removeExemption/exemptionRemoved/index.njk
- server/views/pages/reviewPlan/review/reviewComplete/index.njk
- server/views/pages/reviewPlan/review/whoCompletedReview/index.njk
- server/views/pages/reviewPlan/review/whoCompletedReview/index.test.ts
PR to change the language/wording from "learning and work progress" to "learning and work plan" 🙄
> RR-1273 - Changed language from "learning and work progress" to "learning and work plan"

- server/routes/induction/create/checkYourAnswersCreateController.ts
- server/routes/routerRequestHandlers/createEmptyInductionIfNotInSession.ts
Added debug code to help diagnose the `cannot read properties of undefined` problem (RR-1300)
> RR-1300 - Added debug code

- server/views/pages/induction/exemption/exemptionReason/index.njk
- server/views/pages/reviewPlan/exemption/exemptionReason/index.njk
Updated exemption reason info message content
> RR-1347 - Updated content

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
This PR is the one that enables the feature toggle for our April 1st go live 🚀
> RR-1291 - Enable the reviews feature toggle in all envs

- integration_tests/e2e/reviewPlan/review/reviewPlan.cy.ts
- integration_tests/pages/reviewPlan/WhoCompletedReviewPage.ts
- integration_tests/support/commands.ts
- server/@types/forms/index.d.ts
- server/routes/reviewPlan/review/whoCompletedReviewController.test.ts
- server/routes/reviewPlan/review/whoCompletedReviewController.ts
- server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.test.ts
- server/routes/validators/reviewPlan/whoCompletedReviewFormValidator.ts
- server/views/pages/reviewPlan/review/whoCompletedReview/index.njk
- server/views/partials/layout.njk
This PR changes the date picker on the Review page from the govUk date picker, to the moj date picker
> RR-1391 - Use moj date picker component for Review date

- server/views/pages/createGoals/index.njk
Fixes problem with the date picker - basically I was incorrectly referencing to the field in the formObject when populating the view!
> RR-1520 - Fix problem with date picker when rendering the form

- integration_tests/pages/goal/ArchiveGoalPage.ts
- integration_tests/pages/goal/CompleteGoalPage.ts
- integration_tests/pages/goal/CreateGoalsPage.ts
- integration_tests/pages/goal/UpdateGoalPage.ts
- integration_tests/pages/induction/AdditionalTrainingPage.ts
- integration_tests/pages/induction/AffectAbilityToWorkPage.ts
- integration_tests/pages/induction/ExemptionPage.ts
- integration_tests/pages/induction/FutureWorkInterestRolesPage.ts
- integration_tests/pages/induction/FutureWorkInterestTypesPage.ts
- integration_tests/pages/induction/InPrisonTrainingPage.ts
- integration_tests/pages/induction/InPrisonWorkPage.ts
- integration_tests/pages/induction/InductionNotePage.ts
- integration_tests/pages/induction/PersonalInterestsPage.ts
- integration_tests/pages/induction/PreviousWorkExperienceDetailPage.ts
- integration_tests/pages/induction/PreviousWorkExperienceTypesPage.ts
- integration_tests/pages/induction/SkillsPage.ts
- integration_tests/pages/induction/WhoCompletedInductionPage.ts
- integration_tests/pages/induction/WorkedBeforePage.ts
- integration_tests/pages/prePrisonEducation/QualificationDetailsPage.ts
- integration_tests/pages/prisonerList/PrisonerListPage.ts
- integration_tests/pages/reviewPlan/ReviewNotePage.ts
- integration_tests/pages/reviewPlan/WhoCompletedReviewPage.ts
- integration_tests/pages/reviewPlan/exemption/exemptionPage.ts
- integration_tests/pages/sessionSummary/SessionsSummaryPage.ts
PR to remove the delay between characters when cypress "types" into fields - this has reduced the time it takes for the cypress tests to run by over 1 minute 👍
> RR-1635 - Remove delay between characters when cypress "types" into fields

- helm_deploy/hmpps-education-and-work-plan-ui/values.yaml
Replaces link to LWP feedback survey from SurveyMonkey to SmartSurvey
> RR-1645 - update link to feedback survey

- server/views/pages/functionalSkills/index.njk
- server/views/pages/functionalSkills/macros/sortableTable.njk
New layout on the main Functional Skills page
> RR-1849 - New layout on the main Functional Skills page
